Repository commercetools/merchant-center-application-kit, pull requests merged in 2018-10, with the labels that each got.

#1 fix(app-shell/quick-access): missing dep, log if component cannot be loaded
  packages/application-shell/package.json
  packages/application-shell/src/components/quick-access/butler-container/butler-container.js
  yarn.lock
Labels: 🐛Type: Bug, 🙏Status: Dev Review

#2 chore(navbar/feature-toggles): remove PRODUCT_TYPE_ADMINISTRATION
  packages/application-shell/src/components/navbar/config.js
  packages/application-shell/src/components/navbar/feature-toggles.js
Labels: 👶 good first contribution, 🔮 Type: Chore, 🙏 Status: Dev Review

#5 chore: add travis config
  .travis.yml
  package.json
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#3 Add script to output lerna changelog
  .env.template
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  jest.eslint.config.js
  lerna.json
  lint-staged.config.js
  package.json
  scripts/changelog.js
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#6 refactor(create-webpack-config-for-*): correct naming of color-mod, change order of execution
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
Labels: 🔮 Type: Chore

#7 Improve CONTRIBUTING doc
  CONTRIBUTING.md
Labels: ✍️ Type: Documentation, 🙏 Status: Dev Review

#13 Update translations for quick filters
  packages/i18n/data/core.json
  packages/i18n/data/de.json
  packages/i18n/data/en.json
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#12 fix(navbar): adds Scrollable and FixedMenu
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.mod.css
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: 👨‍🎨 Status: UI/UX Review, 💅 Type: Enhancement

#15 fix(nav-bar): widen expanded navbar to fit spanish support text
  packages/application-shell/src/components/navbar/navbar.mod.css
Labels: 🐛 Type: Bug

#16 chore: upgrade ui-kit and commitlint
  package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#19 chore(travis): add step to push translations to tx (master branch only)
  .travis.yml
  scripts/push_translations.sh
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#22 [application-shell]: Allow passing project key as variable on operation
  packages/application-shell/src/apollo-links/__snapshots__/header-link.spec.js.snap
  packages/application-shell/src/apollo-links/header-link.js
  packages/application-shell/src/apollo-links/header-link.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#24 fix(application-shell): to use expiry not expired in project list
  packages/application-shell/src/components/project-switcher/project-switcher-fragments.graphql
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#18 feat(quick-access): support opening quick access when link has focus
  packages/application-shell/src/components/quick-access/index.js
Labels: 🐛 Type: Bug

#25 refactor(navbar): fetch only active applications from project extension
  packages/application-shell/src/components/navbar/fetch-project-extensions-navbar.graphql
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#34 chore: define peer deps for other packages, ref #20
  packages/application-shell-connectors/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review
