Repository commercetools/merchant-center-application-kit, pull requests merged in 2018-11, with the labels that each got.

#38 Update dependencies
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  playground/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#39 Add nullish-coalescing-operator to babel-preset-mc-app
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#48 fix(components/notification-kinds): do not report error to sentry for `invalid_scope`
  packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.js
  packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.js
Labels: 🙏 Status: Dev Review

#49 docs(changelog): document new release (v1.0.0-rc-3)
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#50 chore: move to named exports
  .gitignore
  packages/application-shell/README.md
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.js
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login/login.js
  packages/application-shell/src/components/performance-timing/actions.js
  packages/application-shell/src/components/version-check-subscriber/version-check-subscriber.js
  packages/application-shell/src/index.js
  packages/i18n/async-locale-data/async-locale-data.spec.js
  packages/i18n/index.js
  packages/l10n/README.md
  packages/l10n/index.js
  packages/l10n/package.json
  packages/l10n/register-moment-locales.js
  packages/l10n/utils/index.js
  packages/sdk/README.md
  playground/src/components/channels-list-connector/actions.js
  playground/src/components/entry-point/entry-point.js
  playground/src/components/entry-point/entry-point.spec.js
Labels: 💥 Type: Breaking Change, 🔮 Type: Chore, 🙏 Status: Dev Review

#53 chore: fix this undefined due to malformed react components
  packages/application-shell/src/components/project-expired/__snapshots__/project-expired.spec.js.snap
  packages/application-shell/src/components/project-expired/project-expired.js
  packages/application-shell/src/from-core/page-not-found/__snapshots__/page-not-found.spec.js.snap
  packages/application-shell/src/from-core/page-not-found/page-not-found.js
Labels: 🔮 Type: Chore

#55 chore: accidentally added text to page-not-found
  packages/application-shell/src/from-core/page-not-found/__snapshots__/page-not-found.spec.js.snap
  packages/application-shell/src/from-core/page-not-found/page-not-found.js
Labels: 🔮 Type: Chore

#56 chore: update deps
  packages/application-shell/package.json
  packages/eslint-config-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#57 chore: don't mix named and default exports on code splitting
  packages/application-shell/src/components/login-locked/async.js
  packages/application-shell/src/components/login-sso-callback/async.js
  packages/application-shell/src/components/login-sso/async.js
  packages/application-shell/src/components/login/async.js
  packages/application-shell/src/components/quick-access/quick-access.js
Labels: 🔮 Type: Chore

#59 chore: rework code splitting for l10n
  packages/l10n/country-information.js
  packages/l10n/currency-information.js
  packages/l10n/language-information.js
  packages/l10n/time-zone-information.js
Labels: 🔮 Type: Chore

#58 chore: refactor i18n for better code splitting
  packages/i18n/README.md
  packages/i18n/load-i18n.js
  packages/i18n/locale-data/de.js
  packages/i18n/locale-data/en.js
  packages/i18n/locale-data/es.js
  packages/i18n/moment-data/de.js
  packages/i18n/moment-data/en-gb.js
  packages/i18n/moment-data/es.js
Labels: 🔮 Type: Chore

#60 Add ApplicationState to test-utils
  .eslintrc.yaml
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/test-utils.js
  packages/application-shell/src/test-utils.spec.js
Labels: 👨‍⚕️ Type: Tests, 💅 Type: Enhancement, 🙏 Status: Dev Review

#66 chore: simplify lint-staged globs
  jest.eslint.config.js
  jest.stylelint.config.js
  lint-staged.config.js
  package.json
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#65 refactor(app-shell): pass userId to getCorrelationId to avoid circular dependency
  packages/application-shell/src/apollo-links/header-link.js
  packages/application-shell/src/apollo-links/header-link.spec.js
  packages/application-shell/src/configure-store.js
  packages/application-shell/src/utils/get-correlation-id/__snapshots__/get-correlation-id.spec.js.snap
  packages/application-shell/src/utils/get-correlation-id/get-correlation-id.js
  packages/application-shell/src/utils/get-correlation-id/get-correlation-id.spec.js
  packages/application-shell/src/utils/select-user-id/select-user-id.js
  packages/application-shell/src/utils/select-user-id/select-user-id.spec.js
  packages/sdk/middleware/middleware.js
Labels: 🙏 Status: Dev Review

#62 fix: circular dependency fix
  packages/application-shell/package.json
  packages/application-shell/src/apollo-links/header-link.js
  packages/application-shell/src/apollo-links/header-link.spec.js
  packages/application-shell/src/configure-store.js
  packages/application-shell/src/utils/get-correlation-id/__snapshots__/get-correlation-id.spec.js.snap
  packages/application-shell/src/utils/get-correlation-id/get-correlation-id.js
  packages/application-shell/src/utils/get-correlation-id/get-correlation-id.spec.js
  packages/application-shell/src/utils/select-user-id/select-user-id.js
  packages/application-shell/src/utils/select-user-id/select-user-id.spec.js
  packages/sdk/middleware/middleware.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#67 Fix TX installation on Travis
  .travis.yml
  scripts/push_translations.sh
Labels: 🐛 Type: Bug, 🔮 Type: Chore, 🙏 Status: Dev Review

#69 refactor(assets): move image assets to `assets` package
  package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/application-loader/application-loader.js
  packages/application-shell/src/components/error-apologizer/error-apologizer.js
  packages/application-shell/src/components/failed-authentication/failed-authentication.js
  packages/application-shell/src/components/login-box/login-box.js
  packages/application-shell/src/components/login-locked/login-locked.js
  packages/application-shell/src/components/project-expired/project-expired.js
  packages/application-shell/src/components/project-not-found/project-not-found.js
  packages/application-shell/src/components/project-suspended/project-suspended.js
  packages/application-shell/src/from-core/page-not-found/page-not-found.js
  packages/assets/LICENSE
  packages/assets/README.md
  packages/assets/images/chevron-down.png
  packages/assets/images/ct-logo.svg
  packages/assets/images/ct_logo_bw.svg
  packages/assets/images/ct_logo_bw_white.svg
  packages/assets/images/failed-authentication.svg
  packages/assets/images/failed-authorization.svg
  packages/assets/images/image__broken.svg
  packages/assets/images/image__missing_image.svg
  packages/assets/images/image__no-image.svg
  packages/assets/images/link-external__broken.svg
  packages/assets/images/link-external__working.svg
  packages/assets/images/logo.svg
  packages/assets/images/page-not-found.svg
  packages/assets/images/project-expired.svg
  packages/assets/images/project-suspended.svg
  packages/assets/images/radio-check-icons.png
  packages/assets/images/unexpected-error.svg
  packages/assets/index.js
  packages/assets/package.json
  rollup.config.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#70 chore: remove empty file from app-shell
  packages/application-shell/src/locale-data.js
Labels: 🔮 Type: Chore

#71 QuickAccess: allow opening in new tab by cmd+click or cmd+enter
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: 💅 Type: Enhancement

#74 Update dependencies
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/project-switcher/project-switcher.js
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/utils.js
  packages/babel-preset-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/l10n/scripts/generate-l10n-data.js
  packages/mc-http-server/package.json
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/extract-intl.js
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/permissions/src/components/authorized/authorized.js
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  playground/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#76 refactor: drop downshift
  packages/application-shell/src/components/menu-state-container/index.js
  packages/application-shell/src/components/menu-state-container/menu-state-container.js
  packages/application-shell/src/components/menu-state-container/menu-state-container.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#75 refactor: self contained styles
  packages/application-shell/src/components/application-shell/global-style-imports.js
  packages/application-shell/src/components/application-shell/grid.mod.css
  packages/application-shell/src/components/application-shell/reset.mod.css
Labels: ⛑ Type: Refactoring

#78 refactor(navbar): remnove `CAN_VIEW_PRODUCTS` feature toggle
  packages/application-shell/src/components/navbar/config.js
  packages/application-shell/src/components/navbar/feature-toggles.js
Labels: 🙏 Status: Dev Review

#73 feat(app-context): add forward-compatible useApplicationContext 🎉
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell-connectors/src/components/application-context/index.js
  packages/application-shell-connectors/src/index.js
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#64 Add TEST_UTILS docs
  packages/application-shell/README.md
  packages/application-shell/TEST_UTILS.md
  packages/application-shell/src/test-utils.js
  packages/application-shell/src/test-utils.spec.js
Labels: ✍️ Type: Documentation, 🙏 Status: Dev Review

#77 refactor(assets): remove named exports
  package.json
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/application-loader/application-loader.js
  packages/application-shell/src/components/error-apologizer/error-apologizer.js
  packages/application-shell/src/components/failed-authentication/failed-authentication.js
  packages/application-shell/src/components/login-box/login-box.js
  packages/application-shell/src/components/login-locked/login-locked.js
  packages/application-shell/src/components/project-expired/project-expired.js
  packages/application-shell/src/components/project-not-found/project-not-found.js
  packages/application-shell/src/components/project-suspended/project-suspended.js
  packages/application-shell/src/from-core/page-not-found/page-not-found.js
  packages/assets/README.md
  packages/assets/index.js
  packages/assets/package.json
  rollup.config.js
  yarn.lock
Labels: 🔮 Type: Chore

#79 refactor(test-utils): reorganize folder structure
  .eslintrc.yaml
  packages/application-shell/README.md
  packages/application-shell/package.json
  packages/application-shell/src/components/quick-access/butler-container/butler-container.js
  packages/application-shell/src/from-core/deprecate-component/deprecate-component.spec.js
  packages/application-shell/src/test-utils/README.md
  packages/application-shell/src/test-utils/index.js
  packages/application-shell/src/test-utils/test-utils.js
  packages/application-shell/src/test-utils/test-utils.spec.js
  packages/mc-scripts/bin/mc-scripts.js
  packages/mc-scripts/webpack-plugins/final-stats-writer-plugin.js
  packages/react-notifications/src/components/notifications-list/notifications-list.spec.js
  packages/sdk/middleware/middleware.spec.js
Labels: ⛑ Type: Refactoring

#80 Playground now deployments 🚀
  playground/.gitignore
  playground/Dockerfile
  playground/README.md
  playground/csp.prod-eu.json
  playground/csp.prod-us.json
  playground/env.prod-eu.json
  playground/env.prod-us.json
  playground/now.eu.json
  playground/now.us.json
  playground/package.json
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#61 Changelog for release v2.0.0
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
Labels: ✍️ Type: Documentation

#88 fix(jest-preset-mc-app): to look up root dir
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/setup-tests.js
  yarn.lock
Labels: 🙏 Status: Dev Review

#87 chore: update deps
  package.json
  packages/eslint-config-mc-app/package.json
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#90 fix: deprecated withProject fix
  packages/application-shell/src/components/fetch-project/fetch-project.js
Labels: 🐛 Type: Bug

#91 chore: revert mini css update
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#92 chore: update changelog for `2.0.1` release
  CHANGELOG.md
Labels: 👶 good first contribution

#93 fix(application-shell): expose test-utils
  .gitignore
  CHANGELOG.md
  packages/application-shell/package.json
Labels: 🐛 Type: Bug

#95 fix: revert uglify js update
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#98 refactor(login-sso): avoid query params in authorize url, use session storage and state nonce
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login-sso/login-sso.spec.js
Labels: ⛑ Type: Refactoring, 🐛 Type: Bug, 🙏 Status: Dev Review

#101 fix(login-sso): objects saved in storage need to be serialized/deserialized
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login-sso/login-sso.spec.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#103 fix(i18n): exports to not include default key
  packages/i18n/index.js
  packages/i18n/load-i18n.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#104 refactor(login-sso): use new /tokens/sso endpoint
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login-sso/login-sso.spec.js
  packages/application-shell/src/components/login/login.js
  packages/application-shell/src/components/logout/logout.js
  packages/application-shell/src/components/logout/logout.spec.js
  packages/application-shell/src/constants.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#108 docs(changelog): for v2.1.0
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#109 Update dependencies (incl. and importantly flopflip)
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#102 refactor(quick-access): correctly apply permissions to all commands and queries
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.graphql
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/quick-access/sub-commands.js
  packages/permissions/src/index.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#114 chore: update @flopflip version
  packages/application-shell/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#115 Replace ProjectSwitcher with a "Back to project" link in AppBar
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/app-bar/messages.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/i18n/data/core.json
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#118 fix(app-shell): add back-to-project data test target
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#117 feat(i18n): fix code splitting for mc-app-kit messages
  packages/i18n/README.md
  packages/i18n/index.js
  packages/i18n/package.json
Labels: 🙏 Status: Dev Review

#119 fix(app-shell): update support link
  packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap
  packages/application-shell/src/constants.js
Labels: 🙏 Status: Dev Review

#121 fix: app crashing when project is not found
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/index.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/permissions/src/utils/has-permissions.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#123 docs(playground): update and improve README about developing custom applications
  CONTRIBUTING.md
  package.json
  playground/README.md
  playground/package.json
Labels: ✍️ Type: Documentation

#125 chore(i18n): pull translations from transifex
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
Labels: 🔮 Type: Chore

#124 chore: sync en.json -> core.json after pulling messages from tx
  package.json
  packages/i18n/data/core.json
  scripts/pull-i18n.js
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#128 feat: add badges.
  README.md
  packages/actions-global/README.md
  packages/application-shell-connectors/README.md
  packages/application-shell/README.md
  packages/assets/README.md
  packages/babel-preset-mc-app/README.md
  packages/browser-history/README.md
  packages/constants/README.md
  packages/eslint-config-mc-app/README.md
  packages/i18n/README.md
  packages/jest-preset-mc-app/README.md
  packages/l10n/README.md
  packages/mc-html-template/README.md
  packages/mc-http-server/README.md
  packages/mc-scripts/README.md
  packages/notifications/README.md
  packages/permissions/README.md
  packages/react-notifications/README.md
  packages/sdk/README.md
  packages/sentry/README.md
  packages/storage/README.md
  packages/url-utils/README.md
Labels: ✍️ Type: Documentation

#89 refactor: use React.lazy and React.Suspense within the AppShell
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/failed-authentication/index.js
  packages/application-shell/src/components/login-locked/async.js
  packages/application-shell/src/components/login-sso-callback/async.js
  packages/application-shell/src/components/login-sso/async.js
  packages/application-shell/src/components/login/async.js
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/project-expired/index.js
  packages/application-shell/src/components/project-not-found/index.js
  packages/application-shell/src/components/project-suspended/index.js
  packages/application-shell/src/components/quick-access/butler-container/butler-container.js
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
  packages/application-shell/src/components/quick-access/index.js
  packages/react-notifications/package.json
  playground/package.json
  playground/src/components/entry-point/entry-point.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#136 chore: update deps
  package.json
  packages/application-shell/package.json
  packages/jest-preset-mc-app/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#137 chore: publish to next dist-tag by default, add command to move to latest
  CONTRIBUTING.md
  package.json
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#140 chore: update changelog in prep for `v3.0.0` [skip-ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#141 fix: rearrange postcss plugins
  packages/mc-scripts/config/create-webpack-config-for-production.js
Labels: 🙏 Status: Dev Review

#144 Fix double dependency bundling
  packages/application-shell/package.json
  packages/application-shell/src/index.js
  yarn.lock
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#145 chore: update docs to include build step
  README.md
Labels: ✍️ Type: Documentation

#142 feat(app-shell/navbar): add menu item for custom apps
  packages/application-shell/src/components/navbar/config.js
  packages/application-shell/src/components/navbar/feature-toggles.js
  packages/application-shell/src/components/navbar/messages.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/messages.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/i18n/data/core.json
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#143 feat(test-utils): run tests agains actual ApolloProvider
  packages/application-shell/src/configure-apollo.js
  packages/application-shell/src/test-utils/test-utils.js
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#149 refactor(navbar): use IconSwitcher to statically render icons based on icon names
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#150 fix(mc-scripts/extract-intl): do not overwrite existing core messages by default
  packages/mc-scripts/extract-intl.js
Labels: 🐛 Type: Bug, 💅 Type: Enhancement, 🙏 Status: Dev Review

#148 docs(changelog): for v3.1.0 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#153 Remove `Avatar` from `application-shell`
  packages/application-shell/src/components/avatar/__snapshots__/avatar.spec.js.snap
  packages/application-shell/src/components/avatar/avatar.js
  packages/application-shell/src/components/avatar/avatar.mod.css
  packages/application-shell/src/components/avatar/avatar.spec.js
  packages/application-shell/src/components/avatar/index.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/application-shell/src/index.js
Labels: 💥 Type: Breaking Change

#154 Make locale data work with CJS bundle
  packages/l10n/country-information.js
  packages/l10n/currency-information.js
  packages/l10n/language-information.js
  packages/l10n/time-zone-information.js
Labels: 🚀 Type: New Feature

#158 Add new permissions to project query of app-shell
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#159 chore(http-server): update favicon images for different resolutions
  packages/mc-html-template/index.js
  packages/mc-http-server/public-assets/favicon.ico
  packages/mc-http-server/public-assets/favicon.png
  packages/mc-http-server/public-assets/favicon_144x144px.png
  packages/mc-http-server/public-assets/favicon_57x57px.png
  packages/mc-http-server/public-assets/favicon_72x72px.png
  packages/mc-http-server/server.js
Labels: 🔮 Type: Chore

#155 feat(test-utils): wrap rendered component with React.Suspense, include modals container, document renderWithRedux
  .travis.yml
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/test-utils/README.md
  packages/application-shell/src/test-utils/test-utils.js
  yarn.lock
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#162 Improve permission names
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#165 fix(navbar): keep WorldIcon for backwards compatibility
  packages/application-shell/src/components/navbar/navbar.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review
