Repository commercetools/merchant-center-application-kit, pull requests merged in 2018-12, with the labels that each got.

#167 docs(changelog): for release v4.0.1
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#177 chore(playground): remove ui-kit materials transpilation
  playground/webpack.config.dev.js
  playground/webpack.config.prod.js
Labels: 🔮 Type: Chore

#178 chore: update deps
  lerna.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/jest-preset-mc-app/package.json
  packages/sdk/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#179 Fail fast on CI
  .travis.yml
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#151 [MCD-1509] Refactor dropdown user settings menu
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 👶 good first contribution, 🙏 Status: Dev Review

#182 MCD-1509(user-settings-menu): address UX review
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap
  packages/application-shell/src/components/user-settings-menu/messages.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/i18n/data/core.json
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#181 refactor(login): validate same origin for redirect target url after login
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/login/login.js
  packages/application-shell/src/components/login/login.spec.js
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#175 fix(test-utils): improve test setup
  packages/application-shell/src/configure-apollo.js
  packages/application-shell/src/from-core/modal-container/modal-container.js
  packages/application-shell/src/middleware/logger.js
  packages/application-shell/src/test-utils/test-utils.js
Labels: 🐛 Type: Bug, 💅 Type: Enhancement, 🙏 Status: Dev Review

#183 MCD-1523 : Refactor CT logo to be 🏠button
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#195 Add core-ws graphql target to constants
  packages/constants/index.js
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#192 Update dependencies
  package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/login-sso/__snapshots__/login-sso.spec.js.snap
  packages/babel-preset-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-scripts/package.json
  yarn.lock
Labels: Semver: UNRELATED

#161 Remove Quick Access feature toggle
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/feature-toggles.js
Labels: Semver: UNRELATED, 🙏 Status: Dev Review

#196 docs(changelog): for v4.3.0 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#198 Add array wrapping to showApiErrorNotification (through .isArray)
  packages/actions-global/global.js
  packages/actions-global/global.spec.js
Labels: Semver: FEATURE, 🙏 Status: Dev Review

#207 chore: update deps
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  playground/package.json
  yarn.lock
Labels: Semver: FIX, 🙏 Status: Dev Review

#212 Remove visibility overwrites from permissions
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
Labels: Semver: BREAKING, 🧟 Type: Technical Debt

#215 [i18n] Do not sync en.json -> core.json 🚨
  package.json
  scripts/pull-i18n.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#213 Add `allAppliedPermissions` and remove `permissions`
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell-connectors/src/components/application-context/application-context.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
Labels: 🙏 Status: Dev Review

#224 chore: update deps
  examples/starter/package.json
  lerna.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#227 Move sdk mocks into sdk/test-utils
  .eslintrc.yaml
  packages/application-shell/src/test-utils/test-utils.js
  packages/sdk/index.js
  packages/sdk/package.json
  packages/sdk/src/actions/actions.js
  packages/sdk/src/actions/actions.spec.js
  packages/sdk/src/actions/index.js
  packages/sdk/src/components/sdk-get/README.md
  packages/sdk/src/components/sdk-get/index.js
  packages/sdk/src/components/sdk-get/sdk-get.js
  packages/sdk/src/components/sdk-get/sdk-get.spec.js
  packages/sdk/src/middleware/client.js
  packages/sdk/src/middleware/index.js
  packages/sdk/src/middleware/middleware.js
  packages/sdk/src/middleware/middleware.spec.js
  packages/sdk/src/test-utils/README.md
  packages/sdk/src/test-utils/index.js
  packages/sdk/src/test-utils/test-utils.js
  packages/sdk/src/test-utils/test-utils.spec.js
  packages/sdk/src/utils/index.js
  packages/sdk/src/utils/utils.js
  packages/sdk/src/utils/utils.spec.js
  packages/sdk/test-utils.js
Labels: Semver: FEATURE, ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Type: New Feature

#217 Refactor `Authorized` in permissions pkg to not rely on constants
  packages/application-shell/src/test-utils/test-utils.spec.js
  packages/permissions/src/components/authorized/authorized.js
  packages/permissions/src/components/authorized/authorized.spec.js
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.js
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.js
  packages/permissions/src/utils/has-permissions.js
  packages/permissions/src/utils/has-permissions.spec.js
Labels: 💅 Type: Enhancement, 💥 Type: Breaking Change, 🙏 Status: Dev Review, 🚀 Type: New Feature

#231 chore: use consistent deps versions, regenerate lockfile
  packages/application-shell-connectors/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review
