Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-10, with the labels that each got.

#1079 fix: modal page header title spacing
  packages/application-components/src/components/modal-pages/internals/modal-page-header-title.tsx
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1080 data locale should be one of the project languages
  packages/application-shell/src/test-utils/test-utils.js
  packages/application-shell/src/test-utils/test-utils.spec.js
Labels: 🐛 Type: Bug

#1085 chore: update deps
  cypress/.eslintrc.yaml
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/create-mc-app/src/steps/update-package-info.js
  packages/eslint-plugin-testing-library-react/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/l10n/scripts/generate-l10n-data.js
  packages/mc-html-template/lib/load-env.js
  packages/mc-scripts/extract-intl.js
  packages/mc-scripts/package.json
  packages/mc-scripts/webpack-plugins/final-stats-writer-plugin.js
  packages/mc-scripts/webpack-plugins/local-html-webpack-plugin.js
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  playground/config/transformer-now.js
  playground/src/mocks/apply-ui-kit-mocks.js
  website/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1091 fix(app-shell): use first input delay
  packages/application-shell/package.json
  packages/application-shell/src/components/performance-timing/measure-first-paint.js
  packages/application-shell/src/components/performance-timing/measure-first-paint.spec.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#1097 feat(i18n): expose some common messages
  packages/i18n/data/core.json
  packages/i18n/src/common-messages.ts
  packages/i18n/src/index.ts
Labels: 🚀 Type: New Feature

#1098 refactor: drop custom eslint plugin for rtl
  .eslintignore
  .eslintrc.yaml
  CONTRIBUTING.md
  package.json
  packages/eslint-plugin-testing-library-react/.gitignore
  packages/eslint-plugin-testing-library-react/LICENSE
  packages/eslint-plugin-testing-library-react/README.md
  packages/eslint-plugin-testing-library-react/babel.config.js
  packages/eslint-plugin-testing-library-react/docs/rules/prefer-expect-query-by.md
  packages/eslint-plugin-testing-library-react/package.json
  packages/eslint-plugin-testing-library-react/src/configs/all.json
  packages/eslint-plugin-testing-library-react/src/configs/recommended.json
  packages/eslint-plugin-testing-library-react/src/index.ts
  packages/eslint-plugin-testing-library-react/src/rules/index.ts
  packages/eslint-plugin-testing-library-react/src/rules/prefer-expect-query-by.ts
  packages/eslint-plugin-testing-library-react/src/utils.ts
  packages/eslint-plugin-testing-library-react/test/rules.spec.ts
  packages/eslint-plugin-testing-library-react/test/rules/prefer-expect-query-by.spec.ts
  packages/eslint-plugin-testing-library-react/tsconfig.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1101 fix(i18n): keep correct file format
  packages/i18n/data/fr_FR.json
  packages/i18n/data/zh-CN.json
  packages/i18n/src/load-i18n.ts
Labels: 🚀 Status: ship it

#1102 feat(permissions): allow appliedPermission with Manage to bypass dataFence
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1107 chore(app-shell): update flopflip to allow passing `featureFlags`
  application-templates/starter/src/components/entry-point/entry-point.js
  application-templates/starter/src/constants.js
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
  packages/application-shell/src/test-utils/test-utils.spec.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1109 fix(permissions/has-permissions): use `hasExactPermission` in `hasAppliedDataFences`
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1111 docs(changelog): add v15.1.8 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1110 fix(percy): to add idle timeout to allow assets to be properly loaded
  website/.percy.yml
Labels: 🛠 Type: Tooling

#1108 feat(app-connectors): expose mock functions for image-regex settings as test-utils
  .eslintignore
  .gitignore
  .prettierignore
  packages/application-shell-connectors/package.json
  packages/application-shell-connectors/src/test-utils/README.md
  packages/application-shell-connectors/src/test-utils/index.ts
  packages/application-shell-connectors/src/test-utils/test-utils.spec.ts
  packages/application-shell-connectors/src/test-utils/test-utils.ts
  packages/application-shell-connectors/test-utils.ts
Labels: 🚀 Type: New Feature

#1113 chore: update flopflip
  packages/application-shell/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1114 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1116 chore(mc-http-server): to expose prefixed metric
  packages/mc-http-server/server.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review, 🚀 Status: ship it

#1117 refactor(mc-http-server): startup logic
  packages/mc-http-server/bin/start-mc.js
  packages/mc-http-server/server.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Status: ship it

#1119 chore(mc-http-server): remove duplicate prom metric
  packages/mc-http-server/server.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1130 refactor(components): use common messages from i18n package
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/README.md
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.mdx
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx
  packages/application-components/src/components/dialogs/form-dialog/README.md
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.mdx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx
  packages/application-components/src/components/modal-pages/form-modal-page/README.md
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.mdx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx
  packages/application-components/src/components/modal-pages/tabular-modal-page/README.md
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.mdx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
  packages/application-components/src/utils/button-messages.ts
  packages/i18n/README.md
  packages/i18n/data/core.json
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
  packages/i18n/data/fr-FR.json
  packages/i18n/data/zh-CN.json
  packages/i18n/src/index.ts
  packages/i18n/src/shared-messages.ts
Labels: ⛑ Type: Refactoring

#1124 PCM-1473: add revert message to Form Modal button messages
  packages/i18n/data/core.json
  packages/i18n/src/shared-messages.ts
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#1134 fix: remove first input delay
  packages/application-shell/src/components/performance-timing/measure-first-paint.js
  packages/application-shell/src/components/performance-timing/measure-first-paint.spec.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it
