Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-01, with the labels that each got.

#242 chore: drop deprecated components
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/index.js
  packages/application-shell/src/components/fetch-user/fetch-user.js
  packages/application-shell/src/components/fetch-user/index.js
  packages/application-shell/src/index.js
  packages/permissions/README.md
  packages/sdk/src/test-utils/README.md
Labels: Semver: BREAKING, 💥 Type: Breaking Change, 🔮 Type: Chore, 🙏 Status: Dev Review

#199 chore: update ui-kit to v5
  .travis.yml
  packages/application-shell/package.json
  packages/create-mc-app/templates/starter/package.json
  packages/create-mc-app/templates/starter/yarn.lock
  packages/react-notifications/package.json
  playground/package.json
  playground/src/components/state-machines-list/state-machines-list.spec.js
  yarn.lock
Labels: Semver: UNRELATED, 🚧 Status: WIP

#241 docs(changelog): for release v5.0.0
  CHANGELOG.md
Labels: Semver: UNRELATED, ✍️ Type: Documentation

#245 refactor(application-shell): permission prop-type form navbar
  packages/application-shell/src/components/navbar/navbar.js
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#244 chore: include create-mc-app templates in yarn workspaces
  package.json
  packages/create-mc-app/templates/starter/package.json
Labels: Semver: FIX, 🐛 Type: Bug

#246 docs(changelog): for release v5.0.1
  CHANGELOG.md
Labels: Semver: UNRELATED, ✍️ Type: Documentation

#247 fix(rollup): rename lodash import to lodash-es only for es bundle
  rollup.config.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#250 docs(changelog): for release v5.0.2
  CHANGELOG.md
Labels: Semver: UNRELATED, ✍️ Type: Documentation, 🙏 Status: Dev Review

#249 chore: update deps
  package.json
  packages/babel-preset-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#243 chore: publish canary releases on CI for master branch
  .travis.yml
  CONTRIBUTING.md
  package.json
Labels: Semver: UNRELATED, 🏕 Technical Exploration, 💡 Type: Idea, 🙏 Status: Dev Review

#254 docs(changelog): for release v5.0.3
  CHANGELOG.md
Labels: Semver: FIX, ✍️ Type: Documentation

#253 chore: configure npm to release canary builds with automation bot account
  .travis.yml
  scripts/release_canary.sh
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🙏 Status: Dev Review

#256 build(travis): skip canary release if build is triggered by a pull request
  scripts/release_canary.sh
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🙏 Status: Dev Review

#266 feat(create-mc-app): use fancy logger
  packages/create-mc-app/bin/create-mc-app.js
  packages/create-mc-app/package.json
  packages/create-mc-app/src/logger.js
  packages/create-mc-app/src/steps/download-template.js
  packages/create-mc-app/src/steps/index.js
  packages/create-mc-app/src/steps/install-dependencies.js
  packages/create-mc-app/src/steps/parse-arguments.js
  packages/create-mc-app/src/steps/success.js
  packages/create-mc-app/src/steps/update-package-info.js
  yarn.lock
Labels: 🏕 Technical Exploration

#267 chore: update deps
  package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/login/countdown.js
  packages/babel-preset-mc-app/package.json
  packages/create-mc-app/templates/starter/package.json
  packages/create-mc-app/templates/starter/src/components/main-view/main-view.js
  packages/eslint-config-mc-app/index.js
  packages/eslint-config-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-html-template/package.json
  packages/mc-scripts/package.json
  packages/sdk/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🙏 Status: Dev Review

#265 refactor(create-mc-app): how to install template
  .travis.yml
  application-templates/starter/.gitignore
  application-templates/starter/README.md
  application-templates/starter/env.json
  application-templates/starter/jest.test.config.js
  application-templates/starter/package.json
  application-templates/starter/src/components/entry-point/entry-point.js
  application-templates/starter/src/components/entry-point/entry-point.spec.js
  application-templates/starter/src/components/entry-point/index.js
  application-templates/starter/src/components/main-view/index.js
  application-templates/starter/src/components/main-view/main-view.js
  application-templates/starter/src/components/main-view/main-view.mod.css
  application-templates/starter/src/components/main-view/main-view.spec.js
  application-templates/starter/src/components/main-view/messages.js
  application-templates/starter/src/components/view-one/index.js
  application-templates/starter/src/components/view-one/messages.js
  application-templates/starter/src/components/view-one/view-one.js
  application-templates/starter/src/components/view-two/index.js
  application-templates/starter/src/components/view-two/messages.js
  application-templates/starter/src/components/view-two/view-two.js
  application-templates/starter/src/i18n/data/core.json
  application-templates/starter/src/i18n/data/de.json
  application-templates/starter/src/i18n/data/en.json
  application-templates/starter/src/i18n/data/es.json
  application-templates/starter/src/i18n/index.js
  application-templates/starter/src/index.js
  application-templates/starter/src/routes.js
  application-templates/starter/webpack.config.dev.js
  application-templates/starter/webpack.config.prod.js
  package.json
  packages/create-mc-app/bin/create-mc-app.js
  packages/create-mc-app/package.json
  packages/create-mc-app/src/logger.js
  packages/create-mc-app/src/steps/download-template.js
  packages/create-mc-app/src/steps/hint-outdated-version.js
  packages/create-mc-app/src/steps/index.js
  packages/create-mc-app/src/steps/install-dependencies.js
  packages/create-mc-app/src/steps/parse-arguments.js
  packages/create-mc-app/src/steps/success.js
  packages/create-mc-app/src/steps/update-package-info.js
  packages/create-mc-app/src/utils.js
  packages/create-mc-app/src/validations.js
  scripts/install_app_template.sh
  scripts/push_translations.sh
  yarn.lock
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#270 fix: template starter missing dependency
  application-templates/starter/package.json
  application-templates/starter/src/index.js
  scripts/install_app_template.sh
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#269 chore: update ui-kit to v6
  application-templates/starter/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/login-sso/__snapshots__/login-sso.spec.js.snap
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login-sso/login-sso.spec.js
  packages/application-shell/src/components/login/login.js
  packages/application-shell/src/components/login/password-field.js
  packages/application-shell/src/components/password-requirement/password-requirement.mod.css
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🙏 Status: Dev Review

#271 chore: update ui-kit and make login submit on enter
  application-templates/starter/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/login-sso/__snapshots__/login-sso.spec.js.snap
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login/login.js
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: Semver: FIX

#251 Add `menuVisibilities` and `allAppliedMenuVisibilities`
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/navbar/__snapshots__/navbar.spec.js.snap
  packages/application-shell/src/components/navbar/config.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
  packages/application-shell/src/components/project-container/project-container.spec.js
  packages/application-shell/src/test-utils/test-utils.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#274 chore(app-shell): remove unused components 🚮
  packages/application-shell/src/components/menu-state-container/index.js
  packages/application-shell/src/components/menu-state-container/menu-state-container.js
  packages/application-shell/src/components/menu-state-container/menu-state-container.spec.js
  packages/application-shell/src/components/password-requirement/__snapshots__/password-requirement.spec.js.snap
  packages/application-shell/src/components/password-requirement/index.js
  packages/application-shell/src/components/password-requirement/password-requirement.js
  packages/application-shell/src/components/password-requirement/password-requirement.mod.css
  packages/application-shell/src/components/password-requirement/password-requirement.spec.js
  packages/application-shell/src/components/password-requirements/__snapshots__/password-requirements.spec.js.snap
  packages/application-shell/src/components/password-requirements/index.js
  packages/application-shell/src/components/password-requirements/password-requirements.js
  packages/application-shell/src/components/password-requirements/password-requirements.mod.css
  packages/application-shell/src/components/password-requirements/password-requirements.spec.js
  packages/application-shell/src/components/project-without-settings/__snapshots__/project-without-settings.spec.js.snap
  packages/application-shell/src/components/project-without-settings/index.js
  packages/application-shell/src/components/project-without-settings/project-without-settings.js
  packages/application-shell/src/components/project-without-settings/project-without-settings.spec.js
  packages/application-shell/src/components/version-check-subscriber/index.js
  packages/application-shell/src/components/version-check-subscriber/version-check-subscriber.js
  packages/application-shell/src/components/version-check-subscriber/version-check-subscriber.spec.js
  packages/application-shell/src/constants.js
  packages/application-shell/src/from-core/deprecate-component/deprecate-component.js
  packages/application-shell/src/from-core/deprecate-component/deprecate-component.spec.js
  packages/application-shell/src/from-core/deprecate-component/index.js
  packages/application-shell/src/from-core/label-field/index.js
  packages/application-shell/src/from-core/label-field/label-field.js
  packages/application-shell/src/from-core/label-field/label-field.mod.css
  packages/application-shell/src/from-core/label-field/label-field.spec.js
  packages/application-shell/src/from-core/required-indicator/__snapshots__/required-indicator.spec.js.snap
  packages/application-shell/src/from-core/required-indicator/index.js
  packages/application-shell/src/from-core/required-indicator/required-indicator.js
  packages/application-shell/src/from-core/required-indicator/required-indicator.mod.css
  packages/application-shell/src/from-core/required-indicator/required-indicator.spec.js
  packages/application-shell/src/from-core/title/index.js
  packages/application-shell/src/from-core/title/title.js
  packages/application-shell/src/from-core/title/title.mod.css
Labels: 🔮 Type: Chore

#272 feat(babel-preset-mc-app): disable console on production
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  playground/webpack.config.prod.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#275 fix(mc-scripts): add dynamic import plugin to fix vendor optimizations
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
Labels: Semver: FIX, 🐛 Type: Bug

#277 chore(eslint-config-mc-app): use only peer deps
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/eslint-config-mc-app/README.md
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  yarn.lock
Labels: Semver: BREAKING, 💥 Type: Breaking Change, 🔮 Type: Chore, 🙏 Status: Dev Review

#278 fix(mc-scripts): use unfetch as polyfill
  packages/application-shell/src/configure-apollo.js
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/setup-test-framework.js
  packages/mc-scripts/config/polyfills.js
  packages/sdk/src/middleware/client.js
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#286 refactor: disable loggers based on runtime configuration
  packages/application-shell/src/configure-apollo.js
  packages/application-shell/src/middleware/logger.js
  packages/application-shell/src/utils/logger.js
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  packages/sdk/src/utils/logger.js
  packages/sdk/src/utils/utils.js
  playground/package.json
  playground/webpack.config.prod.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🏕 Technical Exploration, 💅 Type: Enhancement, 🙏 Status: Dev Review

#290 fix(l10n): return correct localized information
  packages/l10n/country-information.js
  packages/l10n/currency-information.js
  packages/l10n/language-information.js
  packages/l10n/time-zone-information.js
Labels: Semver: FIX, 🐛 Type: Bug

#294 docs(readme): update getting started and local development sections
  README.md
Labels: ✍️ Type: Documentation

#292 feat: add handleApolloErrors HOC to automatically dispatch query errors
  packages/application-shell/src/components/handle-apollo-errors/README.md
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.js
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.spec.js
  packages/application-shell/src/components/handle-apollo-errors/index.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
  packages/application-shell/src/index.js
Labels: 🏕 Technical Exploration, 🙏 Status: Dev Review, 🚀 Type: New Feature

#289 External menu configurations
  application-templates/starter/menu.json
  application-templates/starter/src/components/entry-point/entry-point.js
  packages/application-shell/README.md
  packages/application-shell/src/apollo-links/__snapshots__/header-link.spec.js.snap
  packages/application-shell/src/apollo-links/header-link.js
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/handle-apollo-errors/README.md
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.js
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.spec.js
  packages/application-shell/src/components/handle-apollo-errors/index.js
  packages/application-shell/src/components/navbar/config.js
  packages/application-shell/src/components/navbar/feature-toggles.js
  packages/application-shell/src/components/navbar/messages.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
  packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap
  packages/application-shell/src/components/user-settings-menu/messages.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql
  packages/application-shell/src/components/with-applications-menu/index.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
  packages/application-shell/src/configure-apollo.js
  packages/application-shell/src/index.js
  packages/i18n/data/core.json
  packages/mc-scripts/config/webpack-dev-server.config.js
  playground/menu.json
  playground/src/components/entry-point/entry-point.js
Labels: Semver: FEATURE, ⛑ Type: Refactoring, 💅 Type: Enhancement, 🙏 Status: Dev Review

#296 docs(changelog): for release v7.0.0 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#304 chore: update deps
  .prettierrc
  application-templates/starter/package.json
  package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  playground/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#306 chore: build template app within monorepo, to use linked dependencies
  .travis.yml
  jest.test.config.js
Labels: 🔮 Type: Chore, 🧟 Type: Technical Debt

#307 docs(changelog): for release v7.1.0 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#308 fix(app-shell): to pick menu label based on user locale language tag only
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
Labels: 🐛 Type: Bug

#309 docs(changelog): for release v7.1.1 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#313 fix(template/starter): add missing react-select css import [skip ci]
  application-templates/starter/src/index.js
Labels: 🐛 Type: Bug

#314 Refactor to not `ReconfigureFlopflip` but pass `projectKey` from url
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/setup-flop-flip-provider/__snapshots__/setup-flop-flip-provider.spec.js.snap
  packages/application-shell/src/components/setup-flop-flip-provider/index.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
  yarn.lock
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#326 chore: update reps
  application-templates/starter/package.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#325 chore: update ui-kit deps to 8.0.0
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#329 fix(application-components): name file correctly
  packages/application-components/package.json
Labels: 🐛 Type: Bug

#331 chore: add setupFilesAfterEnv (for jest@24)
  packages/jest-preset-mc-app/jest-preset.js
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review
