Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-06, with the labels that each got.

#678 chore: update deps
  .circleci/config.yml
  CONTRIBUTING.md
  package.json
  visual-testing-app/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#679 chore: remove note and usage of dev mode in webpack for vrt app
  visual-testing-app/webpack.config.js
Labels: 🔮 Type: Chore

#683 feat(assets): add ct logos
  application-templates/starter/README.md
  packages/application-components/.storybook/config.js
  packages/assets/logos/commercetools_navy-logo_horizontal_RGB.png
  packages/assets/logos/commercetools_navy-logo_horizontal_RGB.svg
  packages/assets/logos/commercetools_navy-logo_vertical_RGB.png
  packages/assets/logos/commercetools_navy-logo_vertical_RGB.svg
  packages/assets/logos/commercetools_primary-logo_horizontal_RGB.png
  packages/assets/logos/commercetools_primary-logo_horizontal_RGB.svg
  packages/assets/logos/commercetools_primary-logo_horizontal_white-text_RGB.png
  packages/assets/logos/commercetools_primary-logo_horizontal_white-text_RGB.svg
  packages/assets/logos/commercetools_primary-logo_vertical_RGB.png
  packages/assets/logos/commercetools_primary-logo_vertical_RGB.svg
  packages/assets/logos/commercetools_primary-logo_vertical_white-text_RGB.png
  packages/assets/logos/commercetools_primary-logo_vertical_white-text_RGB.svg
  packages/assets/logos/commercetools_white-logo_horizontal_RGB.png
  packages/assets/logos/commercetools_white-logo_horizontal_RGB.svg
  packages/assets/logos/commercetools_white-logo_vertical_RGB.png
  packages/assets/logos/commercetools_white-logo_vertical_RGB.svg
  playground/README.md
Labels: 🚀 Type: New Feature

#681 docs(website): fix issuer and audience example
  website/content/api-gateway/proxy-to-external-api.mdx
Labels: ✍️ Type: Documentation

#682 refactor(http-server): to unset cookie only for local development
  packages/mc-http-server/README.md
  packages/mc-http-server/routes/logout.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#686 fix(mc-scripts): do not assume that the application entry point is at src/index.js
  packages/mc-scripts/build.js
  packages/mc-scripts/start.js
Labels: 🐛 Type: Bug

#696 fix: setup of custom user agent
  packages/application-shell/src/configure-apollo.js
  packages/sdk/package.json
  packages/sdk/src/middleware/client.js
Labels: 🔮 Type: Chore

#695 feat(app-shell): add version tracker
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/version-tracker/actions.js
  packages/application-shell/src/components/version-tracker/index.js
  packages/application-shell/src/components/version-tracker/version-tracker.js
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#697 feat(app-shell): add reporting react version
  packages/application-shell/src/components/version-tracker/version-tracker.js
Labels: Semver: FEATURE, 💅 Type: Enhancement

#702 fix(rollup): to use mainfields
  rollup.config.js
Labels: Semver: FIX, 🙏 Status: Dev Review

#703 fix(mc-scripts): browserlist config
  packages/mc-scripts/config/browserslist.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  rollup.config.js
Labels: Semver: FIX, 🙏 Status: Dev Review

#707 docs(changelog): for v13.9.0 [skip ci]
  CHANGELOG.md
Labels: Semver: UNRELATED

#710 fix(app-shell): do not re-export the version field from flopflip
  packages/application-shell/src/index.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#714 feat: lint css for website
  .stylelintignore
  jest.stylelint.config.js
  website/src/components/code-block.js
  website/src/layouts/internals/globals.js
  website/src/templates/markdown.js
Labels: 👨‍⚕️ Type: Tests

#717 refactor(url-utils): use typescript
  packages/url-utils/index.ts
  packages/url-utils/package.json
  packages/url-utils/src/index.ts
  packages/url-utils/src/url.spec.ts
  packages/url-utils/src/url.ts
  packages/url-utils/src/version.ts
  packages/url-utils/tsconfig.declarations.json
  packages/url-utils/tsconfig.json
Labels: ⛑ Type: Refactoring

#728 chore: update deps
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/create-mc-app/src/validations.js
  packages/jest-preset-mc-app/package.json
  packages/l10n/scripts/generate-l10n-data.js
  packages/mc-scripts/config/webpack-dev-server.config.js
  packages/mc-scripts/package.json
  packages/mc-scripts/webpack-plugins/final-stats-writer-plugin.js
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.js
  packages/react-notifications/src/components/notifications-list/notifications-list.js
  packages/sdk/src/middleware/middleware.js
  scripts/run-percy.js
  visual-testing-app/package.json
  website/package.json
  website/src/layouts/internals/layout-header.js
  website/src/layouts/internals/navbar.js
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore

#731 revert(storybook): contexts addon, since it's missing the core-js dependency
  packages/application-components/.storybook/addons.js
  packages/application-components/.storybook/config.js
  packages/application-components/.storybook/configs/contexts/index.js
  packages/application-components/.storybook/configs/contexts/intl-context.js
  packages/application-components/.storybook/decorators/index.js
  packages/application-components/.storybook/decorators/intl/index.js
  packages/application-components/.storybook/decorators/intl/intl.js
  packages/application-components/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#733 refactor(website): to use custom knobs to control component props
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.example.js
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.spec.js
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.example.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.story.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.example.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.spec.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js
  packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js
  packages/application-components/src/components/internals/for-docs/modal-controller/modal-controller.js
  packages/application-components/src/components/modal-page/modal-page.story.js
  website/src/layouts/content.js
  website/src/layouts/internals/globals.js
  website/src/layouts/internals/layout-main.js
  website/src/layouts/marketing.js
  website/src/templates/markdown.js
Labels: 🏕 Technical Exploration

#735 fix(website): tooltip z-index fix
  packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js
Labels: 🐛 Type: Bug

#736 fix(build): use `overrideBrowsersList` to comply with new autoprefixer API
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  rollup.config.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#737 refactor: migrate application-shell-connectors to TypeScript
  .eslintrc.yaml
  jest.d.ts
  netlify.toml
  package.json
  packages/application-shell-connectors/index.ts
  packages/application-shell-connectors/package.json
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/components/application-context/index.ts
  packages/application-shell-connectors/src/components/project-extension-image-regex/index.ts
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.js
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.spec.tsx
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.tsx
  packages/application-shell-connectors/src/graphql.d.ts
  packages/application-shell-connectors/src/index.ts
  packages/application-shell-connectors/src/utils/get-display-name.ts
  packages/application-shell-connectors/src/version.ts
  packages/application-shell-connectors/tsconfig.declarations.json
  packages/application-shell-connectors/tsconfig.json
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/project-container/project-container.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/constants/index.ts
  packages/constants/package.json
  packages/constants/src/constants.ts
  packages/constants/src/index.ts
  packages/constants/src/version.ts
  packages/constants/tsconfig.declarations.json
  packages/constants/tsconfig.json
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/setup-test-framework.js
  packages/l10n/package.json
  packages/l10n/src/create-l10n-injector/create-l10n-injector.tsx
  packages/l10n/src/utils.ts
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.js
  packages/react-notifications/src/components/notifications-list/notifications-list.spec.js
  packages/sentry/src/sentry-user-logout-tracker/sentry-user-logout-tracker.spec.tsx
  packages/sentry/src/sentry-user-logout-tracker/sentry-user-logout-tracker.tsx
  packages/sentry/src/sentry-user-tracker/sentry-user-tracker.spec.tsx
  packages/sentry/src/sentry-user-tracker/sentry-user-tracker.tsx
  packages/sentry/src/sentry.ts
  packages/sentry/src/type-utils.ts
  rollup.config.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#642 feat(components): new Modal Page design
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.js
  packages/application-components/src/components/dialogs/internals/dialog-footer.js
  packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js
  packages/application-components/src/components/modal-page/README.md
  packages/application-components/src/components/modal-page/index.js
  packages/application-components/src/components/modal-page/modal-page.js
  packages/application-components/src/components/modal-page/modal-page.mod.css
  packages/application-components/src/components/modal-page/modal-page.story.js
  packages/application-components/src/components/modal-page/modal-page.visualroute.js
  packages/application-components/src/components/modal-page/modal-page.visualspec.js
  packages/application-components/src/components/modal-pages/form-modal-page/README.md
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.example.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.mdx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.story.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.visualroute.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.visualspec.js
  packages/application-components/src/components/modal-pages/form-modal-page/index.js
  packages/application-components/src/components/modal-pages/info-modal-page/README.md
  packages/application-components/src/components/modal-pages/info-modal-page/index.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.example.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.mdx
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.story.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.visualroute.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.visualspec.js
  packages/application-components/src/components/modal-pages/internals/messages.js
  packages/application-components/src/components/modal-pages/internals/modal-page-header-default-controls.js
  packages/application-components/src/components/modal-pages/internals/modal-page-header-title.js
  packages/application-components/src/components/modal-pages/internals/modal-page-header.js
  packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.js
  packages/application-components/src/components/modal-pages/internals/modal-page.js
  packages/application-components/src/components/modal-pages/internals/modal-page.styles.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/README.md
  packages/application-components/src/components/modal-pages/tabular-modal-page/index.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.example.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.mdx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.story.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.visualroute.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-page.visualspec.js
  packages/application-components/src/index.js
  packages/application-components/src/utils/button-messages.js
  website/gatsby-config.js
Labels: 👨‍🎨 Status: UI/UX Review, 🙏 Status: Dev Review

#740 fix(app-shell-connectors): to cast context type to not be empty, use function overloading for useApplicationContext
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/tsconfig.declarations.json
  packages/constants/tsconfig.declarations.json
  packages/l10n/tsconfig.declarations.json
  packages/sentry/tsconfig.declarations.json
  packages/storage/tsconfig.declarations.json
  packages/url-utils/tsconfig.declarations.json
  tsconfig.json
Labels: 🔮 Type: Chore

#741 chore: unrevert contexts for app-components storybook.
  packages/application-components/.storybook/addons.js
  packages/application-components/.storybook/config.js
  packages/application-components/.storybook/configs/contexts/index.js
  packages/application-components/.storybook/configs/contexts/intl-context.js
  packages/application-components/.storybook/decorators/index.js
  packages/application-components/.storybook/decorators/intl/index.js
  packages/application-components/.storybook/decorators/intl/intl.js
  packages/application-components/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#743 docs(sdk): fix example code
  packages/sdk/README.md
Labels: ✍️ Type: Documentation

#744 feat(website): add intl controller for playground mode
  packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js
  packages/application-components/src/components/internals/for-docs/intl-controller/index.js
  packages/application-components/src/components/internals/for-docs/intl-controller/intl-controller.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.example.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.example.js
Labels: 🔮 Type: Chore

#746 chore: keep rollup command simple and consistent
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/permissions/package.json
Labels: 🔮 Type: Chore

#749 chore: remove storybook
  jest.stylelint.config.js
  package.json
  packages/application-components/.storybook/addons.js
  packages/application-components/.storybook/assets/favicon.ico
  packages/application-components/.storybook/config.js
  packages/application-components/.storybook/configs/contexts/index.js
  packages/application-components/.storybook/configs/contexts/intl-context.js
  packages/application-components/.storybook/decorators/index.js
  packages/application-components/.storybook/decorators/section/index.js
  packages/application-components/.storybook/decorators/section/section.js
  packages/application-components/.storybook/manager-head.html
  packages/application-components/.storybook/preview-head.html
  packages/application-components/.storybook/webpack.config.js
  packages/application-components/.storybook/welcome.story.js
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.story.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.story.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.story.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.story.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.story.js
  packages/application-components/src/components/page-not-found/page-not-found.story.js
  yarn.lock
Labels: 🔮 Type: Chore

#760 chore(app-shell): remove org list toggle
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/feature-toggles.js
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#762 fix(i18n): fix naming bug for french and chinese translations
  packages/i18n/data/fr-FR.json
  packages/i18n/data/zh-CN.json
  packages/i18n/src/load-i18n.js
Labels: 🐛 Type: Bug

#764 feat(app-shell): add user deleted logout reason
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/constants/src/constants.ts
Labels: Semver: FEATURE, 💅 Type: Enhancement

#769 fix: support link url
  packages/application-components/src/components/page-not-found/page-not-found.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/application-shell/src/constants.js
  packages/constants/src/constants.ts
Labels: 🐛 Type: Bug

#776 chore(application-shell): remove usage of deprecated custom property
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
Labels: 🔮 Type: Chore

#766 feat(modal-pages): add delay before calling onClose to let animations finish
  packages/application-components/src/components/modal-pages/form-modal-page/README.md
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.example.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.js
  packages/application-components/src/components/modal-pages/info-modal-page/README.md
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.js
  packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.js
  packages/application-components/src/components/modal-pages/internals/modal-page.js
  packages/application-components/src/components/modal-pages/internals/modal-page.styles.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/README.md
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.example.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.js
Labels: 💅 Type: Enhancement

#774 refactor(i18n): convert to TS
  jest.d.ts
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/i18n/index.ts
  packages/i18n/package.json
  packages/i18n/src/async-locale-data/async-locale-data.js
  packages/i18n/src/async-locale-data/async-locale-data.spec.js
  packages/i18n/src/async-locale-data/async-locale-data.spec.tsx
  packages/i18n/src/async-locale-data/async-locale-data.tsx
  packages/i18n/src/async-locale-data/index.ts
  packages/i18n/src/index.ts
  packages/i18n/src/load-i18n.ts
  packages/i18n/src/locales.d.ts
  packages/i18n/src/utils.ts
  packages/i18n/src/version.ts
  packages/i18n/tsconfig.declarations.json
  packages/i18n/tsconfig.json
  packages/l10n/package.json
  packages/permissions/package.json
  packages/sentry/package.json
Labels: ⛑ Type: Refactoring

#777 fix(website): to use better font sizes scale, fix menu grid row for small screen
  website/src/layouts/content.js
  website/src/layouts/internals/content-pagination.js
  website/src/layouts/internals/layout-container.js
  website/src/layouts/internals/layout-toc.js
  website/src/layouts/internals/navbar.js
  website/src/templates/markdown.js
Labels: 🖥 Type: Website

#775 chore: move with-mouse-over-state internal
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/with-mouse-over-state/README.md
  packages/application-shell/src/components/with-mouse-over-state/index.js
  packages/application-shell/src/components/with-mouse-over-state/with-mouse-over-state.js
  packages/application-shell/src/components/with-mouse-over-state/with-mouse-over-state.spec.js
  packages/application-shell/src/components/wrap-display-name/index.js
  packages/application-shell/src/components/wrap-display-name/wrap-display-name.js
  packages/application-shell/src/components/wrap-display-name/wrap-display-name.spec.js
Labels: 🔮 Type: Chore

#789 fix(jest-stylelint-runner): include run file
  packages/jest-stylelint-runner/package.json
Labels: 🐛 Type: Bug

#791 chore: add babel plugin transform react constant
  packages/babel-preset-mc-app/index.js
Labels: 🔮 Type: Chore

#792 fix(app-shell): to support admin service target
  packages/application-shell/src/apollo-links/token-retry-link.js
  packages/application-shell/src/apollo-links/token-retry-link.spec.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#793 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#797 fix(babel-preset): to remove plugin-transform-react-constant-elements
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  yarn.lock
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review
