Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-02, with the labels that each got.

#332 Add graceful shutdown and isolated Prometheus metrics server to mc-http-server
  packages/mc-http-server/package.json
  packages/mc-http-server/routes/metrics.js
  packages/mc-http-server/routes/metrics.spec.js
  packages/mc-http-server/server.js
  yarn.lock
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#340 chore: update deps
  package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  playground/package.json
  yarn.lock
Labels: Semver: UNRELATED

#342 Add placeholder to quick-access input
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
  packages/application-shell/src/components/quick-access/messages.js
  packages/i18n/data/core.json
Labels: Semver: FEATURE, 🚀 Type: New Feature

#341 fix(apollo-cache): to use __typename + key for whitelisted types only if the id is not present
  packages/application-shell/src/configure-apollo.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#343 docs(changelog): for release v7.3.1 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#345 chore: drop unnecessary deep-freeze dependency
  packages/notifications/middleware/middleware.spec.js
  packages/notifications/package.json
  packages/notifications/reducer/reducer.spec.js
  yarn.lock
Labels: 🔮 Type: Chore

#346 refactor: to not setupTestFramework for jest (so we can update)
  application-templates/starter/package.json
  package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/jest-preset.js
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/transform-babel-jest.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#348 Replace `query-string` with `qss`
  packages/application-shell/package.json
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js
  packages/browser-history/index.js
  packages/browser-history/package.json
  packages/sdk/package.json
  packages/sdk/src/utils/utils.js
  packages/sdk/src/utils/utils.spec.js
  yarn.lock
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#352 Fix fetching custom application menu only when feature is enabled
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#353 docs(changelog): for v7.3.3 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#355 fix(browser-history): to omit the question mark
  packages/browser-history/index.js
Labels: Semver: FIX, 🐛 Type: Bug

#362 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#354 fix(application-shell): redirect to welcome by default
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
Labels: Semver: BREAKING, 💥 Type: Breaking Change, 🙏 Status: Dev Review

#366 Add Storybook for developing application components
  .gitignore
  package.json
  packages/application-components/.storybook/addons.js
  packages/application-components/.storybook/assets/favicon.ico
  packages/application-components/.storybook/config.js
  packages/application-components/.storybook/decorators/index.js
  packages/application-components/.storybook/decorators/intl/index.js
  packages/application-components/.storybook/decorators/intl/intl.js
  packages/application-components/.storybook/decorators/section/index.js
  packages/application-components/.storybook/decorators/section/section.js
  packages/application-components/.storybook/manager-head.html
  packages/application-components/.storybook/preview-head.html
  packages/application-components/.storybook/webpack.config.js
  packages/application-components/.storybook/welcome.story.js
  packages/application-components/package.json
  packages/application-components/src/components/maintenance-page-layout/README.md
  packages/application-components/src/components/maintenance-page-layout/index.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.mod.css
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.spec.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.story.js
  packages/application-components/src/components/page-not-found/page-not-found.js
  packages/application-components/src/components/page-not-found/page-not-found.mod.css
  packages/application-components/src/components/page-not-found/page-not-found.story.js
  packages/application-components/src/components/service-page-response-layout/index.js
  packages/application-components/src/components/service-page-response-layout/service-page-response-layout.js
  packages/application-components/src/components/service-page-response-layout/service-page-response-layout.mod.css
  packages/application-components/src/index.js
  packages/application-components/src/utils/deprecate-component.js
  packages/application-shell/src/components/error-apologizer/error-apologizer.js
  packages/application-shell/src/components/failed-authentication/failed-authentication.js
  packages/application-shell/src/components/login-locked/login-locked.js
  packages/application-shell/src/components/project-expired/__snapshots__/project-expired.spec.js.snap
  packages/application-shell/src/components/project-expired/project-expired.js
  packages/application-shell/src/components/project-expired/project-expired.spec.js
  packages/application-shell/src/components/project-not-found/__snapshots__/project-not-found.spec.js.snap
  packages/application-shell/src/components/project-not-found/project-not-found.js
  packages/application-shell/src/components/project-not-found/project-not-found.spec.js
  packages/application-shell/src/components/project-suspended/__snapshots__/project-suspended.spec.js.snap
  packages/application-shell/src/components/project-suspended/project-suspended.js
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🔮 Type: Chore, 🙏 Status: Dev Review

#378 chore: update to ui-kit v9.0.0
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/login-sso/__snapshots__/login-sso.spec.js.snap
  packages/i18n/package.json
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#367 feat: add <InfoDialog>
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/info-dialog/README.md
  packages/application-components/src/components/dialogs/info-dialog/index.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.spec.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js
  packages/application-components/src/components/dialogs/internals/dialog-container.js
  packages/application-components/src/components/dialogs/internals/dialog-content.js
  packages/application-components/src/components/dialogs/internals/dialog-header.js
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
  packages/application-components/src/index.js
  packages/application-components/src/utils/deprecate-component.js
  packages/application-shell/src/components/login-box/login-box.js
  packages/application-shell/src/components/login/countdown.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/from-core/README.md
  packages/application-shell/src/from-core/button-close/__snapshots__/button-close.spec.js.snap
  packages/application-shell/src/from-core/button-close/button-close.js
  packages/application-shell/src/from-core/button-close/button-close.mod.css
  packages/application-shell/src/from-core/button-close/button-close.spec.js
  packages/application-shell/src/from-core/button-close/index.js
  packages/application-shell/src/from-core/card/__snapshots__/card.spec.js.snap
  packages/application-shell/src/from-core/card/card.js
  packages/application-shell/src/from-core/card/card.mod.css
  packages/application-shell/src/from-core/card/card.spec.js
  packages/application-shell/src/from-core/card/index.js
  packages/application-shell/src/from-core/info-dialog/info-dialog.js
  packages/application-shell/src/from-core/info-dialog/info-dialog.mod.css
  packages/application-shell/src/from-core/info-dialog/info-dialog.spec.js
  packages/application-shell/src/from-core/modal-container/__snapshots__/modal-container.spec.js.snap
  packages/application-shell/src/from-core/modal-container/index.js
  packages/application-shell/src/from-core/modal-container/modal-container.spec.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#380 fix: broken layouts due to Card component structure changes
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/README.md
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.js
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js
  packages/application-components/src/components/dialogs/info-dialog/README.md
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js
  packages/application-components/src/components/dialogs/internals/dialog-container.js
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.js
  packages/application-components/src/utils/deprecate-component.js
  packages/application-components/src/utils/get-display-name.js
  packages/application-shell/src/components/login-box/__snapshots__/login-box.spec.js.snap
  packages/application-shell/src/components/login-box/login-box.js
  packages/application-shell/src/components/login-box/login-box.mod.css
  packages/application-shell/src/components/login-box/login-box.spec.js
  packages/application-shell/src/components/public-page-container/public-page-container.js
  packages/application-shell/src/components/public-page-container/public-page-container.mod.css
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css
Labels: 🐛 Type: Bug, 💅 Type: Enhancement, 🙏 Status: Dev Review

#381 fix(app-shell): quick-access to support full reloads
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: Semver: FIX, 🐛 Type: Bug

#384 feat(components/dialogs): make overlay z-index configurable
  packages/application-components/src/components/dialogs/confirmation-dialog/README.md
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.js
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js
  packages/application-components/src/components/dialogs/info-dialog/README.md
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js
  packages/application-components/src/components/dialogs/internals/dialog-container.js
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#385 chore(app-shell): expose ApplicationShellProvider
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.js
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/application-shell/src/components/application-shell-provider/global-style-imports.js
  packages/application-shell/src/components/application-shell-provider/grid.mod.css
  packages/application-shell/src/components/application-shell-provider/index.js
  packages/application-shell/src/components/application-shell-provider/reset.mod.css
  packages/application-shell/src/components/application-shell-provider/utils.js
  packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/index.js
  packages/i18n/async-locale-data/async-locale-data.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Type: New Feature

#386 docs(changelog): for release v9.0.0 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#387 fix(app-shell): to not open in new tab
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#397 Update uglify plugin / stop shipping es6 code to ie
  application-templates/starter/webpack.config.prod.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/config/polyfills.js
  packages/mc-scripts/package.json
  playground/webpack.config.prod.js
  yarn.lock
Labels: Semver: BREAKING, 💥 Type: Breaking Change

#399 feat(components/dialogs): add FormDialog
  packages/application-components/src/components/dialogs/confirmation-dialog/README.md
  packages/application-components/src/components/dialogs/form-dialog/README.md
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.story.js
  packages/application-components/src/components/dialogs/form-dialog/index.js
  packages/application-components/src/components/dialogs/internals/messages.js
  packages/application-components/src/index.js
  packages/i18n/data/core.json
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#395 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#400 Remove recompose
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.js
  packages/application-shell-connectors/src/utils/get-display-name.js
  packages/application-shell/package.json
  packages/application-shell/src/components/fetch-project/README.md
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/fetch-project/index.js
  packages/application-shell/src/components/fetch-user/README.md
  packages/application-shell/src/components/fetch-user/fetch-user.js
  packages/application-shell/src/components/fetch-user/fetch-user.spec.js
  packages/application-shell/src/components/fetch-user/index.js
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.js
  packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js
  packages/application-shell/src/components/login-sso/login-sso.js
  packages/application-shell/src/components/login/login.js
  packages/application-shell/src/components/logout/logout.js
  packages/application-shell/src/components/logout/logout.spec.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/project-switcher/project-switcher.js
  packages/application-shell/src/components/project-switcher/project-switcher.spec.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.js
  packages/application-shell/src/utils/get-display-name.js
  packages/jest-preset-mc-app/package.json
  packages/l10n/create-l10n-injector/create-l10n-injector.js
  packages/l10n/package.json
  packages/l10n/utils/get-display-name.js
  packages/permissions/package.json
  packages/permissions/src/components/authorized/authorized.js
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.js
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.js
  packages/permissions/src/utils/get-display-name.js
  packages/react-notifications/package.json
  packages/react-notifications/src/components/notification/notification.js
  packages/react-notifications/src/components/notification/notification.spec.js
  playground/src/components/state-machines-list/state-machines-list.js
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#398 docs(changelog): for release v10.0.0 [skip ci]
  CHANGELOG.md
Labels: 🔮 Type: Chore

#402 feat: remove pegjs loader from webpack config
  packages/jest-preset-mc-app/jest-preset.js
  packages/jest-preset-mc-app/package.json
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: Semver: BREAKING, 💥 Type: Breaking Change

#405 chore: pull translations [skip ci]
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#406 refactor(configure-apollo): add special mapping for DeliveryItem type
  packages/application-shell/src/configure-apollo.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#408 fix(components/dialog): to pass title for modal aria-label
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.js
  packages/application-components/src/components/dialogs/internals/dialog-container.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#410 Revert "refactor(configure-apollo): add special mapping for deliveryItem type
  packages/application-shell/src/configure-apollo.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review
