Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-09, with the labels that each got.

#1013 chore: update flopflip
  packages/application-shell/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1015 fix(mc-http-server): to add referrer policy
  packages/mc-html-template/lib/load-headers.js
  packages/mc-http-server/package.json
  packages/mc-http-server/server.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🚨 Type: Security

#1014 feat: add eslint plugin for react testing library 🔥
  .eslintignore
  .eslintrc.yaml
  package.json
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.spec.tsx
  packages/application-components/src/components/page-not-found/page-not-found.spec.tsx
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.js
  packages/eslint-plugin-testing-library-react/.gitignore
  packages/eslint-plugin-testing-library-react/LICENSE
  packages/eslint-plugin-testing-library-react/README.md
  packages/eslint-plugin-testing-library-react/babel.config.js
  packages/eslint-plugin-testing-library-react/docs/rules/prefer-expect-query-by.md
  packages/eslint-plugin-testing-library-react/package.json
  packages/eslint-plugin-testing-library-react/src/configs/all.json
  packages/eslint-plugin-testing-library-react/src/configs/recommended.json
  packages/eslint-plugin-testing-library-react/src/index.ts
  packages/eslint-plugin-testing-library-react/src/rules/index.ts
  packages/eslint-plugin-testing-library-react/src/rules/prefer-expect-query-by.ts
  packages/eslint-plugin-testing-library-react/src/utils.ts
  packages/eslint-plugin-testing-library-react/test/rules.spec.ts
  packages/eslint-plugin-testing-library-react/test/rules/prefer-expect-query-by.spec.ts
  packages/eslint-plugin-testing-library-react/tsconfig.json
  yarn.lock
Labels: 🚀 Type: New Feature

#1023 refactor(renovate): update config to have one pr per week
  .renovaterc.json
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1025 chore: update deps
  package.json
  yarn.lock
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1026 fix(renovate): config to not nest
  .renovaterc.json
Labels: 🙏 Status: Dev Review

#1016 feat: add ability to specify feature policies
  packages/mc-html-template/README.md
  packages/mc-html-template/lib/compile-html.js
  packages/mc-html-template/lib/load-headers.js
  packages/mc-http-server/bin/start-mc.js
  packages/mc-scripts/compile-html.js
  packages/mc-scripts/config/webpack-dev-server.config.js
  playground/README.md
  playground/csp.json
  playground/headers.json
  playground/package.json
  playground/production-eu.csp.json
  playground/production-eu.headers.json
  playground/production-us.csp.json
  playground/production-us.headers.json
  website/content/deployment/example-aws-s3-cloudfront.mdx
  website/content/deployment/example-firebase.mdx
  website/content/deployment/example-now-v1.mdx
  website/content/deployment/http-server.mdx
  website/content/deployment/runtime-configuration.mdx
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#1028 fix(app-shell): null check for dataFences in navbar component
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: 🐛 Type: Bug

#1029 fix(mc-html-template): to load headers not from csp
  packages/mc-html-template/lib/load-headers.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1031 fix(app-shell): use default cache-first fetch policy for user account menu
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
Labels: 🐛 Type: Bug

#1033 Remove unsupported countries
  packages/l10n/data/countries/de.json
  packages/l10n/data/countries/en.json
  packages/l10n/data/countries/es.json
  packages/l10n/data/countries/fr-FR.json
  packages/l10n/data/countries/zh-CN.json
  packages/l10n/scripts/generate-l10n-data.js
Labels: 🐛 Type: Bug

#1035 Try to improve Netlify build time for website
  netlify.toml
  website/gatsby-config.js
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1036 fix(app-shell): fetch policy on AmILoggedIn
  packages/application-shell/src/components/authenticated/authenticated.js
Labels: 🐛 Type: Bug

#1034 chore: update ts-eslint to v2
  .eslintrc.yaml
  package.json
  packages/application-components/src/utils/filter-data-attributes.ts
  packages/application-shell/src/apollo-links/token-retry-link.spec.js
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/i18n/src/async-locale-data/async-locale-data.tsx
  packages/jest-preset-mc-app/polyfills/intl-pluralrules.js
  packages/mc-scripts/extract-intl.js
  packages/permissions/src/components/authorized/authorized.tsx
  packages/react-notifications/src/components/notification/notification.spec.tsx
  packages/react-notifications/src/utils/filter-data-attributes.ts
  tsconfig.eslint.json
  tsconfig.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1038 refactor(app-shell): do not fetch unused fields for project query
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
Labels: ⛑ Type: Refactoring

#1045 fix(csp): to whitelist sentry.io in connect-src
  packages/mc-html-template/lib/load-headers.js
Labels: 🐛 Type: Bug

#1047 chore: improve ts setup for discovering types
  @types-extensions/locales.d.ts
  packages/i18n/tsconfig.json
  packages/permissions/src/components/authorized/authorized.spec.tsx
  tsconfig.json
Labels: 🔮 Type: Chore

#1048 feat: validate graphql files using eslint and schema introspection
  .env.template
  .eslintrc.yaml
  .graphqlconfig.yaml
  CONTRIBUTING.md
  package.json
  packages/application-shell-connectors/src/components/project-extension-image-regex/fetch-project-extension-image-regex.settings.graphql
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.spec.tsx
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.tsx
  packages/application-shell/src/components/authenticated/authenticated.js
  packages/application-shell/src/components/authenticated/authenticated.mc.graphql
  packages/application-shell/src/components/authenticated/authenticated.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/fetch-user/fetch-user.js
  packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql
  packages/application-shell/src/components/fetch-user/fetch-user.spec.js
  packages/application-shell/src/components/navbar/fetch-project-extensions-navbar.settings.graphql
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/application-shell/src/components/project-switcher/project-switcher-fragments.mc.graphql
  packages/application-shell/src/components/project-switcher/project-switcher.js
  packages/application-shell/src/components/project-switcher/project-switcher.mc.graphql
  packages/application-shell/src/components/project-switcher/project-switcher.spec.js
  packages/application-shell/src/components/quick-access/quick-access-product.ctp.graphql
  packages/application-shell/src/components/quick-access/quick-access.ctp.graphql
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/quick-access/sub-commands.js
  packages/application-shell/src/hooks/use-applications-menu/fetch-applications-menu.proxy.graphql
  packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.js
  packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.js
  packages/application-shell/src/utils/select-user-id/select-user-id.js
  packages/application-shell/src/utils/select-user-id/select-user-id.mc.graphql
  schemas/ctp.json
  schemas/mc.json
  schemas/proxy.json
  schemas/settings.json
  yarn.lock
Labels: 💅 Type: Enhancement

#1049 fix: to avoid using Mapped Types as babel plugin does not properly generate prop-types
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: 🐛 Type: Bug

#1050 chore: add Type: tooling to labels [skip ci]
  .github-labelsrc.json
Labels: 🛠 Type: Tooling

#1051 chore(changelog): update to v15.1.4
  CHANGELOG.md
Labels: 🚀 Status: ship it

#1046 refactor(rollup): to build multiple bundles
  CONTRIBUTING.md
  README.md
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  playground/README.md
  rollup.config.js
Labels: 🔮 Type: Chore

#1057 fix(app-shell): sanitize correlation id parts
  packages/application-shell/src/utils/get-correlation-id/get-correlation-id.js
  packages/application-shell/src/utils/get-correlation-id/get-correlation-id.spec.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#1058 fix: exclude package names causing issues
  .renovaterc.json
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1062 feat: generate TS types for graphql schemas
  .prettierignore
  @types-extensions/graphql-ctp.d.ts
  @types-extensions/graphql-mc.d.ts
  @types-extensions/graphql-proxy.d.ts
  @types-extensions/graphql-settings.d.ts
  @types-extensions/graphql.d.ts
  codegen.yml
  husky.config.js
  jest.prettier.config.js
  lint-staged.config.js
  package.json
  packages/application-shell-connectors/src/components/project-extension-image-regex/fetch-project-extension-image-regex.settings.graphql
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.spec.tsx
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.tsx
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell-connectors/src/types/generated/settings.ts
  packages/application-shell/src/components/authenticated/authenticated.mc.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql
  packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql
  packages/application-shell/src/components/navbar/fetch-project-extensions-navbar.settings.graphql
  packages/application-shell/src/components/project-switcher/project-switcher.mc.graphql
  packages/application-shell/src/components/quick-access/quick-access-product.ctp.graphql
  packages/application-shell/src/components/quick-access/quick-access.ctp.graphql
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/proxy.ts
  packages/application-shell/src/types/generated/settings.ts
  packages/application-shell/src/utils/select-user-id/select-user-id.js
  packages/application-shell/src/utils/select-user-id/select-user-id.mc.graphql
  yarn.lock
Labels: 🔮 Type: Chore

#1063 fix(app-shell): apollo header link to omit empty headers
  packages/application-shell/src/apollo-links/header-link.js
  packages/application-shell/src/apollo-links/header-link.spec.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#1066 fix(mc-scripts): to read headers path
  packages/mc-scripts/compile-html.js
Labels: 🐛 Type: Bug

#1067 docs(website): fix malformed hyphens
  website/content/deployment/example-aws-s3-cloudfront.mdx
  website/content/deployment/example-firebase.mdx
Labels: 🖥 Type: Website

#1064 refactor(app-context): to derive provider types from generated query types
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/components/application-context/normalizers.spec.ts
  packages/application-shell-connectors/src/components/application-context/normalizers.ts
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/test-utils/README.md
  packages/application-shell/src/test-utils/test-utils.js
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: ⛑ Type: Refactoring
