Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-04, with the labels that each got.

#503 fix(assets): publish all files and folders
  packages/assets/package.json
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#508 fix: store cypress artifacts
  .circleci/config.yml
Labels: Semver: UNRELATED, 🐛 Type: Bug

#507 Update dependencies
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sentry/package.json
  playground/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#506 fix(app-shell): css height for app container
  packages/application-shell/src/components/application-shell/application-shell.mod.css
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#509 fix(app-shell): prevent main content to be scrollable when modals are open
  packages/application-shell/src/components/application-shell/application-shell.mod.css
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#513 chore: fix canary releases
  .circleci/config.yml
Labels: Semver: UNRELATED, 🐛 Type: Bug

#512 docs(changelog): for v13.0.0 [skip ci]
  CHANGELOG.md
Labels: Semver: UNRELATED

#515 fix(app-shell): to unset previously set cached value
  packages/application-shell/src/components/authenticated/authenticated.js
  packages/application-shell/src/components/authenticated/authenticated.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#517 fix(app-shell): redirect to logout when catching unauthorized error
  packages/application-shell/src/components/application-shell/application-shell.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#526 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/create-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/sentry/sentry.js
  playground/package.json
  visual-testing-app/package.json
  yarn.lock
Labels: Semver: FIX, ⛑ Type: Refactoring

#528 feat(app-shell): add allowing to pass ldTrackingTenant alone
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
Labels: Semver: FEATURE, 🙏 Status: Dev Review, 🚀 Type: New Feature

#530 fix: allow react-redux@7.x as peer dep
  application-templates/starter/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/react-notifications/package.json
  packages/sdk/package.json
  playground/package.json
  yarn.lock
Labels: Semver: FIX, 🙏 Status: Dev Review

#531 feat(configure-apollo): add special mapping for Store entity
  packages/application-shell/src/configure-apollo.js
Labels: Semver: FIX, 💅 Type: Enhancement, 🙏 Status: Dev Review

#535 fix: replace deprecated and broken package jest-plugin-filename with jest-watch-typeahead
  jest.eslint.config.js
  jest.stylelint.config.js
  package.json
  packages/jest-preset-mc-app/jest-preset.js
  packages/jest-preset-mc-app/package.json
  yarn.lock
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#542 fix(dialogs): content overflow. Refs #534
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
Labels: 🐛 Type: Bug

#519 refactor(i18n): to load the i18n messages async
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.js
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/application-shell/src/components/application-shell-provider/utils.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/i18n/async-locale-data/async-locale-data.js
  packages/i18n/load-i18n.js
  packages/i18n/utils.js
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: ⚠️ Blocked ‼, 💅 Type: Enhancement, 🖐 Status: On Hold

#543 chore: use non deprecated custom properties
  application-templates/starter/src/components/main-view/main-view.mod.css
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
  packages/application-shell/src/components/app-bar/app-bar.mod.css
  packages/application-shell/src/components/application-loader/application-loader.mod.css
  packages/application-shell/src/components/application-shell-provider/reset.mod.css
  packages/application-shell/src/components/loading-placeholder/loading-placeholder.mod.css
  packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css
  packages/application-shell/src/components/navbar/navbar.mod.css
  packages/application-shell/src/components/project-switcher/project-switcher.mod.css
  packages/application-shell/src/components/quick-access/butler-command/butler-command.mod.css
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css
  packages/react-notifications/src/components/notification/notification.mod.css
  packages/react-notifications/src/components/notifications-list/notifications-list.mod.css
  playground/src/components/state-machines-list/state-machines-list.mod.css
Labels: Semver: UNRELATED, 🔮 Type: Chore

#544 chore: update deps
  application-templates/starter/src/messages.js
  package.json
  packages/application-shell/src/components/failed-authentication/index.js
  packages/i18n/load-i18n.js
  packages/l10n/country-information.js
  packages/l10n/currency-information.js
  packages/l10n/data/currencies/de.json
  packages/l10n/data/currencies/en.json
  packages/l10n/data/currencies/es.json
  packages/l10n/data/currencies/fr-FR.json
  packages/l10n/data/currencies/zh-CN.json
  packages/l10n/data/time-zones/de.json
  packages/l10n/data/time-zones/en.json
  packages/l10n/data/time-zones/es.json
  packages/l10n/data/time-zones/fr-FR.json
  packages/l10n/data/time-zones/zh-CN.json
  packages/l10n/language-information.js
  packages/l10n/package.json
  packages/l10n/scripts/generate-l10n-data.js
  packages/l10n/time-zone-information.js
  playground/src/messages.js
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore

#547 chore: fix formatting
  packages/i18n/load-i18n.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#549 docs(changelog): for v13.3.0 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#551 fix: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/mc-html-template/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  visual-testing-app/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#550 refactor: to pass intl message to Text components
  application-templates/starter/src/components/main-view/main-view.js
  application-templates/starter/src/components/view-one/view-one.js
  application-templates/starter/src/components/view-two/view-two.js
  packages/application-shell/src/components/app-bar/app-bar.js
  playground/src/components/state-machines-list/messages.js
  playground/src/components/state-machines-list/state-machines-list.js
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#555 fix(app-shell): add env variable for enabling sign up
  packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/project-container/project-container.spec.js
Labels: Semver: FIX, 🙏 Status: Dev Review

#563 refactor(sentry): to also pass location to sentry environment, enable sentry based on tracking value
  packages/sentry/sentry.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#567 fix(app-shell): back to project link colour
  packages/application-shell/src/components/app-bar/app-bar.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#571 fix(mc-scripts): do not use ip address as socket host. Fixes #569
  packages/mc-scripts/start.js
Labels: 🐛 Type: Bug

#581 chore: update dependencies
  application-templates/starter/package.json
  lerna.json
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#582 fix(app-shell): routing to project without key
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#574 refactor(components): to use emotion styles
  .stylelintignore
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualroute.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualspec.js
  packages/application-components/src/components/dialogs/internals/dialog-container.js
  packages/application-components/src/components/dialogs/internals/dialog-content.js
  packages/application-components/src/components/dialogs/internals/dialog-header.js
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
  packages/application-components/src/components/dialogs/internals/dialog.styles.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.mod.css
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  yarn.lock
Labels: Semver: FIX, ⛑ Type: Refactoring, 🔮 Type: Chore, 🙏 Status: Dev Review

#583 docs(changelog): for v13.3.6 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#584 fix(app-shell): project key being set to null
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/project-container/project-container.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#586 chore(app-shell): extract logic into util
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/utils/get-previous-project-key/get-previous-project-key.js
  packages/application-shell/src/utils/get-previous-project-key/index.js
  packages/application-shell/src/utils/index.js
Labels: Semver: FIX, 🙏 Status: Dev Review

#573 refactor(website): to style markdown pages (convert info dialog page)
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.mdx
  website/gatsby-config.js
  website/package.json
  website/src/colors.js
  website/src/components/burger-icon.js
  website/src/components/code-block.js
  website/src/components/footer.js
  website/src/components/header.js
  website/src/components/layout.js
  website/src/components/markdown-layout.js
  website/src/components/navbar.js
  website/src/components/pagination.js
  website/src/components/seo.js
  website/src/images/logo.svg
  yarn.lock
Labels: 🙏 Status: Dev Review

#587 chore(app-shell): add development mode message
  packages/application-shell/src/components/application-shell/application-shell.js
Labels: Semver: FIX, 🙏 Status: Dev Review

#585 docs(changelog): for v13.3.7 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#590 refactor(app-shell): to have redirect-to-project-create component
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/redirect-to-project-create/index.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🙏 Status: Dev Review

#592 chore(app-shell): to not fetch project without key
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.js
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#588 chore(website): migrate content pages for getting started, improve layout and other things
  lint-staged.config.js
  package.json
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.mdx
  website/content/getting-started/deployment.mdx
  website/content/getting-started/development.mdx
  website/content/getting-started/installation.mdx
  website/content/getting-started/introduction.mdx
  website/content/getting-started/registration.mdx
  website/content/http-api.mdx
  website/content/mc-fe-architecture.png
  website/gatsby-config.js
  website/package.json
  website/src/components/markdown-layout.js
  website/static/assets/custom-applications/mc-apps-activated.png
  website/static/assets/custom-applications/mc-apps-activation.png
  website/static/assets/custom-applications/mc-apps-inactive.png
  website/static/assets/custom-applications/mc-dev-now-alias.png
  website/static/assets/custom-applications/mc-dev-now-deployed.png
  website/static/assets/custom-applications/mc-dev-now-login-failed.png
  website/static/assets/custom-applications/mc-dev-now_1.png
  website/static/assets/custom-applications/mc-dev-now_2.png
  website/static/assets/custom-applications/mc-dev-starter-login.png
  website/static/assets/custom-applications/mc-dev-starter-main.png
  website/static/assets/custom-applications/mc-dev-yarn-build.png
  website/static/assets/custom-applications/mc-dev-yarn-i18n-build.png
  website/static/assets/custom-applications/mc-dev-yarn-start.png
  website/static/assets/custom-applications/mc-dev-yarn-test.png
  website/static/assets/custom-applications/mc-fe-architecture.png
  website/static/assets/custom-applications/mc-http-api.png
  yarn.lock
Labels: 🙏 Status: Dev Review
