Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-08, with the labels that each got.

#917 refactor: to use emotion styles
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.mod.css
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-loader/application-loader.js
  packages/application-shell/src/components/application-loader/application-loader.mod.css
  packages/application-shell/src/components/application-loader/application-loader.spec.js
  packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.mod.css
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/loading-placeholder/loading-placeholder.js
  packages/application-shell/src/components/loading-placeholder/loading-placeholder.mod.css
  packages/application-shell/src/components/locale-switcher/locale-switcher.js
  packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css
  packages/application-shell/src/components/navbar/__snapshots__/navbar.spec.js.snap
  packages/application-shell/src/components/navbar/navbar.spec.js
  packages/application-shell/src/components/portals-container/portals-container.js
  packages/application-shell/src/components/portals-container/portals-container.mod.css
  packages/application-shell/src/components/project-switcher/project-switcher.js
  packages/application-shell/src/components/project-switcher/project-switcher.mod.css
  packages/application-shell/src/components/quick-access/butler-command/butler-command.js
  packages/application-shell/src/components/quick-access/butler-command/butler-command.mod.css
  packages/application-shell/src/components/quick-access/butler-container/butler-container.js
  packages/application-shell/src/components/quick-access/butler-container/butler-container.mod.css
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
  packages/application-shell/src/components/quick-access/index.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.mod.css
  packages/application-shell/src/components/setup-flop-flip-provider/__snapshots__/setup-flop-flip-provider.spec.js.snap
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/react-notifications/package.json
  packages/react-notifications/src/components/notifications-list/notifications-list.styles.ts
  playground/src/components/page-bottom-spacer/__snapshots__/page-bottom-spacer.spec.js.snap
  playground/src/components/page-bottom-spacer/page-bottom-spacer.spec.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#919 feat: add some uikit declaration types
  @types/commercetools-frontend__ui-kit/index.d.ts
  packages/application-shell-connectors/package.json
  packages/react-notifications/src/components/notification/notification.tsx
  yarn.lock
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#923 chore: update react-intl to 3.0.0-beta.23
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#924 chore(types/ui-kit): add more type declarations
  .circleci/config.yml
  @types/commercetools-frontend__ui-kit/index.d.ts
  packages/jest-preset-mc-app/jest-preset-for-typescript.js
  packages/react-notifications/src/components/notification/notification.tsx
Labels: 🚀 Type: New Feature

#931 chore: update deps
  package.json
  yarn.lock
Labels: 🚀 Status: ship it

#933 chore(website): update to gatsby-plugin-mdx, workaround for remark images bug
  website/gatsby-config.js
  website/package.json
  website/src/templates/markdown.js
  yarn.lock
Labels: 🖥 Type: Website

#918 feat(application-shell/project-query): add `allAppliedDataFences`
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  playground/env.json
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#934 feat(circleci): snapshot testing for documentation website
  .circleci/config.yml
  .percy.yml
  website/gatsby-config.js
  website/src/pages/index.js
Labels: 🏕 Type: Technical Exploration, 🖥 Type: Website

#936 feat(e2e): take percy snapshots
  .circleci/config.yml
  cypress/integration/playground/state-machines.js
  cypress/integration/template-starter/main.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/urls.js
  package.json
  yarn.lock
Labels: 🏕 Type: Technical Exploration, 👨‍⚕️ Type: Tests

#937 chore: update to stable react-intl v3
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-components/src/components/page-not-found/page-not-found.tsx
  packages/application-shell/package.json
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  visual-testing-app/webpack.config.js
  website/gatsby-node.js
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#939 fix: Modal Pages custom controls
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx
  packages/application-components/src/components/modal-pages/internals/modal-page.tsx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
Labels: 🐛 Type: Bug

#940 fix(website): use default font-family of ui-kit for playground container
  website/src/layouts/internals/globals.js
Labels: 🖥 Type: Website

#942 feat(app-shell/navbar): add ability to hide menu by action rights
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#932 docs: firebase and aws deployment example documentation
  website/content/deployment/example-aws.mdx
  website/content/deployment/example-firebase.mdx
  website/gatsby-config.js
  website/static/assets/custom-applications/mc-dev-aws-changeset-create.png
  website/static/assets/custom-applications/mc-dev-aws-changeset-execute.png
  website/static/assets/custom-applications/mc-dev-aws-fallback.png
  website/static/assets/custom-applications/mc-dev-aws-s3-upload.png
  website/static/assets/custom-applications/mc-dev-aws-stack-create.png
  website/static/assets/custom-applications/mc-dev-aws-stack-fields.png
  website/static/assets/custom-applications/mc-dev-aws-stack-outputs.png
  website/static/assets/custom-applications/mc-dev-aws-stack-resources.png
  website/static/assets/custom-applications/mc-dev-aws-stack-upload.png
  website/static/assets/custom-applications/mc-dev-firebase-fallback.png
  website/static/assets/custom-applications/mc-dev-firebase-hosting-console.png
  website/static/assets/custom-applications/mc-dev-firebase-hosting-site.png
  website/static/assets/custom-applications/mc-dev-firebase-hosting.png
  website/static/assets/custom-applications/mc-dev-firebase-init.png
Labels: 🖥 Type: Website

#944 refactor(website): use only one font, several other improvements
  website/content/deployment/example-now-v1.mdx
  website/gatsby-config.js
  website/src/components/notification-feature.js
  website/src/images/external-link.svg
  website/src/layouts/content.js
  website/src/layouts/internals/globals.js
  website/src/layouts/internals/layout-container.js
  website/src/layouts/internals/layout-footer.js
  website/src/layouts/internals/layout-toc.js
  website/src/pages/code-snippets/getting-started-npm-install.mdx
  website/src/pages/code-snippets/getting-started-npx-install.mdx
  website/src/pages/index.js
  website/src/templates/markdown.js
Labels: 🖥 Type: Website

#945 fix(test-utils): to set default required dataFences option
  packages/application-shell/src/test-utils/test-utils.js
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
Labels: 🐛 Type: Bug

#946 fix(website): syntax highlighting and font-family for UI components
  packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js
  website/content/deployment/example-aws-s3-cloudfront.mdx
  website/content/deployment/example-firebase.mdx
  website/content/deployment/example-now-v1.mdx
  website/content/deployment/http-server.mdx
  website/content/deployment/production-build.mdx
  website/content/development/folder-structure.mdx
  website/content/getting-started/installing-a-starter-application.mdx
  website/content/main-concepts/data-fetching.mdx
  website/src/templates/markdown.js
Labels: 🖥 Type: Website

#948 fix(jest): use cjs syntax
  packages/jest-preset-mc-app/setup-test-framework.js
Labels: 🐛 Type: Bug

#949 fix(application-components): rewrite conditional props logic, to account prop-types transformer
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
Labels: ⛑ Type: Refactoring

#938 chore: update ui-kit
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
  packages/application-shell/package.json
  packages/i18n/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#951 fix(react-notifications): onCloseClick is optional
  packages/react-notifications/src/components/notification/notification.tsx
Labels: 🐛 Type: Bug

#953 fix(application-components): prop is optional
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.tsx
Labels: 🐛 Type: Bug

#963 chore: update deps
  jest.test.config.js
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/jest-preset.js
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/vendors-to-transpile.js
  packages/mc-scripts/config/vendors-to-transpile.js
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  packages/sentry/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🚀 Status: ship it

#970 fix: percy snapshots for website
  .percy.yml
  package.json
  website/.percy.yml
  website/package.json
  website/src/layouts/internals/layout-container.js
Labels: 🖥 Type: Website

#971 refactor(constants): use const assertion
  packages/constants/src/constants.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#941 feat(permissions/authorized): add support for demandedDataFences for injectAuthorized
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/permissions/README.md
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: 🙏 Status: Dev Review

#973 fix: prop-types for dataFences optional field
  .circleci/config.yml
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/project-container/project-container.spec.js
  packages/application-shell/src/test-utils/test-utils.js
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
Labels: 🐛 Type: Bug

#972 feat(app-shell): load actionRights from gql for menu
  packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#975 refactor: remove reselect
  package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/project-switcher/project-switcher.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/permissions/package.json
  packages/react-notifications/package.json
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Status: ship it

#976 fix(actions-global): distinguish unknown/api errors based on presence of body field
  packages/actions-global/src/actions/handle-action-error.spec.ts
  packages/actions-global/src/actions/handle-action-error.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#978 chore: update react-intl
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#986 feat(sdk): allow to pass a mcApiProxyTarget, to the SDK action
  packages/application-shell/src/components/performance-timing/actions.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/version-tracker/actions.js
  packages/constants/src/constants.ts
  packages/sdk/README.md
  packages/sdk/src/middleware/middleware.js
  packages/sdk/src/middleware/middleware.spec.js
  packages/sdk/src/test-utils/README.md
  playground/src/components/state-machines-details/actions.js
  playground/src/components/state-machines-list-connector/actions.js
  playground/src/components/state-machines-list-connector/state-machines-list-connector.js
  playground/src/components/state-machines-list/state-machines-list.js
  playground/src/components/state-machines-list/state-machines-list.spec.js
  playground/src/routes.js
  website/content/main-concepts/data-fetching.mdx
  website/content/main-concepts/graphql.mdx
  website/content/main-concepts/proxy-endpoints.mdx
  yarn.lock
Labels: 🚀 Type: New Feature

#988 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/l10n/data/countries/de.json
  packages/l10n/data/countries/en.json
  packages/l10n/data/countries/es.json
  packages/l10n/data/countries/fr-FR.json
  packages/l10n/data/countries/zh-CN.json
  packages/l10n/data/currencies/de.json
  packages/l10n/data/currencies/en.json
  packages/l10n/data/currencies/es.json
  packages/l10n/data/currencies/fr-FR.json
  packages/l10n/data/currencies/zh-CN.json
  packages/l10n/data/time-zones/de.json
  packages/l10n/data/time-zones/en.json
  packages/l10n/data/time-zones/es.json
  packages/l10n/data/time-zones/fr-FR.json
  packages/l10n/data/time-zones/zh-CN.json
  packages/l10n/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#985 refactor(sdk): to convert to TS
  @types/commercetools__api-request-builder/index.d.ts
  @types/commercetools__http-user-agent/index.d.ts
  @types/commercetools__sdk-client/index.d.ts
  @types/commercetools__sdk-middleware-correlation-id/index.d.ts
  @types/commercetools__sdk-middleware-http/index.d.ts
  @types/globals.d.ts
  package.json
  packages/application-shell/src/test-utils/test-utils.js
  packages/constants/src/constants.ts
  packages/sdk/index.ts
  packages/sdk/package.json
  packages/sdk/src/actions/actions.js
  packages/sdk/src/actions/actions.spec.js
  packages/sdk/src/actions/actions.spec.ts
  packages/sdk/src/actions/actions.ts
  packages/sdk/src/actions/index.ts
  packages/sdk/src/components/sdk-get/index.ts
  packages/sdk/src/components/sdk-get/sdk-get.spec.tsx
  packages/sdk/src/components/sdk-get/sdk-get.tsx
  packages/sdk/src/index.ts
  packages/sdk/src/middleware/client.ts
  packages/sdk/src/middleware/index.ts
  packages/sdk/src/middleware/middleware.js
  packages/sdk/src/middleware/middleware.spec.ts
  packages/sdk/src/middleware/middleware.ts
  packages/sdk/src/test-utils/README.md
  packages/sdk/src/test-utils/index.ts
  packages/sdk/src/test-utils/test-utils.js
  packages/sdk/src/test-utils/test-utils.spec.ts
  packages/sdk/src/test-utils/test-utils.ts
  packages/sdk/src/types.ts
  packages/sdk/src/utils/index.ts
  packages/sdk/src/utils/logger.ts
  packages/sdk/src/utils/utils.spec.ts
  packages/sdk/src/utils/utils.ts
  packages/sdk/src/version.ts
  packages/sdk/test-utils.ts
  packages/sdk/tsconfig.declarations.json
  packages/sdk/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: ⛑ Type: Refactoring

#990 refactor(permissions/has-permissions): pass `actualDataFenceValues` into `selectDataFenceData`
  packages/permissions/README.md
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#991 feat(application-shell/navbar): add demandedDataFences and return dataFenceValues given to the user
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
  packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
Labels: 💥 Type: Breaking Change, 🙏 Status: Dev Review, 🚀 Status: ship it, 🚀 Type: New Feature

#992 fix: tsconfig to correctly include custom type definitions and check test files
  @types-extensions/graphql.d.ts
  @types-extensions/svg.d.ts
  @types/commercetools__sdk-client/index.d.ts
  @types/commercetools__sdk-middleware-http/index.d.ts
  @types/globals.d.ts
  jest.d.ts
  packages/actions-global/src/actions/handle-action-error.ts
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/constants/src/constants.ts
  packages/i18n/src/locales.d.ts
  packages/i18n/tsconfig.json
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/sdk/src/components/sdk-get/sdk-get.spec.tsx
  packages/sdk/src/middleware/client.ts
  packages/sdk/src/middleware/middleware.spec.ts
  packages/sdk/src/test-utils/test-utils.spec.ts
  packages/sdk/src/utils/utils.spec.ts
  packages/sentry/package.json
  packages/sentry/src/sentry-user-logout-tracker/sentry-user-logout-tracker.tsx
  packages/sentry/src/sentry-user-tracker/sentry-user-tracker.spec.tsx
  packages/sentry/src/sentry-user-tracker/sentry-user-tracker.tsx
  packages/sentry/src/sentry.ts
  tsconfig.json
Labels: 🐛 Type: Bug

#994 fix(dialogs): onClose prop is optional
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.tsx
Labels: 🐛 Type: Bug

#1006 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-html-template/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1009 CON-187: properly pass dataFences from menu to `Authorized.js`
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
Labels: 🐛 Type: Bug, 🚀 Status: ship it
