Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-03, with the labels that each got.

#375 Add Percy VRT tests
  .eslintrc.yaml
  .percy.yml
  .prettierignore
  .travis.yml
  jest-puppeteer.config.js
  jest.visual-dummy.config.js
  jest.visual.config.js
  package.json
  packages/application-components/dummy.visualroute.js
  packages/application-components/dummy.visualspec.js
  packages/application-components/src/components/page-not-found/page-not-found.visualroute.js
  packages/application-components/src/components/page-not-found/page-not-found.visualspec.js
  packages/application-components/test-utils/visual/index.js
  packages/application-components/test-utils/visual/spec.js
  packages/application-components/test-utils/visual/suite.js
  scripts/run-percy.js
  visual-testing-app/index.html
  visual-testing-app/package.json
  visual-testing-app/src/App.js
  visual-testing-app/src/index.js
  visual-testing-app/webpack.config.js
  yarn.lock
Labels: 🔮 Type: Chore

#411 fix(components/dialog): to have L spacing between buttons
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
Labels: ⛑ Type: Refactoring, 👨‍🎨 Status: UI/UX Review

#414 chore: consistently use lodash-es import
  packages/permissions/src/utils/has-permissions.js
Labels: 🔮 Type: Chore

#415 chore: upgrade to react-router v4.4.0-beta.7
  application-templates/starter/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#413 fix(test-utils): create default memory history with the enhanced location
  packages/application-shell/src/test-utils/README.md
  packages/application-shell/src/test-utils/test-utils.js
  packages/browser-history/index.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#416 docs(readme): update badges [skip ci]
  README.md
  packages/actions-global/README.md
  packages/application-components/README.md
  packages/application-shell-connectors/README.md
  packages/application-shell/README.md
  packages/assets/README.md
  packages/babel-preset-mc-app/README.md
  packages/browser-history/README.md
  packages/constants/README.md
  packages/create-mc-app/README.md
  packages/eslint-config-mc-app/README.md
  packages/i18n/README.md
  packages/jest-preset-mc-app/README.md
  packages/l10n/README.md
  packages/mc-html-template/README.md
  packages/mc-http-server/README.md
  packages/mc-scripts/README.md
  packages/notifications/README.md
  packages/permissions/README.md
  packages/react-notifications/README.md
  packages/sdk/README.md
  packages/sentry/README.md
  packages/storage/README.md
  packages/url-utils/README.md
Labels: ✍️ Type: Documentation

#412 Dialog layout fixes, add VRT tests 💅
  packages/application-components/src/components/dialogs/confirmation-dialog/README.md
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.js
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.visualroute.js
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.visualspec.js
  packages/application-components/src/components/dialogs/form-dialog/README.md
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualroute.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualspec.js
  packages/application-components/src/components/dialogs/info-dialog/README.md
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.visualroute.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.visualspec.js
  packages/application-components/src/components/dialogs/internals/dialog-container.js
  packages/application-components/src/components/dialogs/internals/dialog-header.js
  packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
  packages/application-components/test-utils/visual/spec.js
  packages/application-components/test-utils/visual/suite.js
  visual-testing-app/package.json
  yarn.lock
Labels: 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review, 💅 Type: Enhancement, 🙏 Status: Dev Review

#423 chore: upgrade deps
  application-templates/starter/package.json
  lerna.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#409 docs(changelog): for release v11.0.0 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#425 fix: pin react-router to 4.4.0-beta.6
  application-templates/starter/package.json
  application-templates/starter/src/components/entry-point/entry-point.js
  package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/react-notifications/package.json
  playground/package.json
  playground/src/components/entry-point/entry-point.js
  visual-testing-app/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#426 fix(apps-menu): to trigger remote query based on servedByProxy value
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/route-catch-all/route-catch-all.js
  packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
Labels: 🐛 Type: Bug

#428 chore: remove dummy percy test
  jest.visual-dummy.config.js
  package.json
  packages/application-components/dummy.visualroute.js
  packages/application-components/dummy.visualspec.js
  scripts/run-percy.js
Labels: 🔮 Type: Chore

#427 feat: add cypress tests for playground and template apps
  .gitignore
  .travis.yml
  application-templates/starter/package.json
  cypress.json
  cypress/.env.template
  cypress/.eslintrc.yaml
  cypress/fixtures/example.json
  cypress/integration/playground/state-machines.js
  cypress/integration/template-starter/main.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/support/urls.js
  cypress/videos/playground/state-machines.js.mp4
  package.json
  yarn.lock
Labels: 👨‍⚕️ Type: Tests

#430 docs(changelog): for release v11.0.1 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#434 chore: remove local transifex config, we use github integration now
  .travis.yml
  .tx/config
  package.json
  packages/i18n/README.md
  scripts/push_translations.sh
Labels: 🔮 Type: Chore

#435 docs(app-shell): fix test-utils link to readme
  packages/application-shell/README.md
Labels: Semver: UNRELATED, 🙏 Status: Dev Review

#443 docs(changelog): for release v11.0.2 [skip ci]
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#446 Support HEAD-requests
  packages/sdk/package.json
  packages/sdk/src/actions/actions.js
  packages/sdk/src/actions/actions.spec.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#449 React Router v4.4.0
  application-templates/starter/package.json
  package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/browser-history/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#457 feat(app-shell): add re-export of gtm logout and flopflip
  packages/application-shell/src/index.js
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#458 fix(mc-scripts): use terser as minifier
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#460 fix: update react-router to v5
  application-templates/starter/package.json
  package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  yarn.lock
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#462 feat(app-shell): quick-access to have noresults message
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
  packages/application-shell/src/components/quick-access/messages.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#463 feat(app-shell): quick access to have loading indicator
  packages/application-shell/src/components/quick-access/butler/butler.js
  packages/application-shell/src/components/quick-access/butler/butler.mod.css
Labels: Semver: FEATURE, 🙏 Status: Dev Review, 🚀 Type: New Feature

#465 fix: insight into dirty working directory post build
  CONTRIBUTING.md
  package.json
  scripts/release_canary.sh
Labels: Semver: UNRELATED, 🔮 Type: Chore

#466 fix: update storybook to v5
  .prettierignore
  packages/application-components/.storybook/addons.js
  packages/application-components/.storybook/config.js
  packages/application-components/.storybook/decorators/intl/intl.js
  packages/application-components/.storybook/webpack.config.js
  packages/application-components/package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.story.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.story.js
  yarn.lock
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#467 chore: remove cypress video
  cypress/videos/playground/state-machines.js.mp4
Labels: Semver: UNRELATED, 🔮 Type: Chore

#475 chore: update yarn to 1.15.2
  .travis.yml
Labels: 🙏 Status: Dev Review

#476 refactor(sentry): to use newest sdk over deprecated raven client
  packages/application-shell/package.json
  packages/application-shell/src/middleware/sentry-tracking.js
  packages/sentry/package.json
  packages/sentry/sentry.js
  packages/sentry/sentry.spec.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#478 chore: remove csp report-uri
  packages/mc-html-template/load-headers.js
Labels: 🔮 Type: Chore

#481 chore: update omit-empty-es to v1.0.3
  packages/application-shell/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#482 refactor(test-utils): to avoid conflicting named exports with rtl render function
  application-templates/starter/src/components/main-view/main-view.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/fetch-user/fetch-user.spec.js
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.spec.js
  packages/application-shell/src/components/inject-reducers/inject-reducers.spec.js
  packages/application-shell/src/components/login-locked/login-locked.spec.js
  packages/application-shell/src/components/login/login.spec.js
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
  packages/application-shell/src/test-utils/README.md
  packages/application-shell/src/test-utils/test-utils.js
  packages/application-shell/src/test-utils/test-utils.spec.js
  playground/src/components/state-machines-list/state-machines-list.spec.js
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#486 refactor(ci): migrate to CircleCI
  .circleci/config.yml
  .travis.yml
  README.md
  package.json
  scripts/install_app_template.sh
  scripts/release_canary.sh
  scripts/run-percy.js
  yarn.lock
Labels: Semver: UNRELATED, ⛑ Type: Refactoring

#489 fix: save other dist folders too
  .circleci/config.yml
Labels: Semver: UNRELATED, 🙏 Status: Dev Review

#490 Fix orb for compare urls
  .circleci/config.yml
Labels: Semver: UNRELATED, 🙏 Status: Dev Review

#487 feat(app-shell): Add prop do defer adapter config on flop flip provider setup
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#491 fix: update flopflip
  packages/application-shell/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🙏 Status: Dev Review

#493 chore: update launchdarkly-adapter
  packages/application-shell/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#494 docs(changelog): for v12.1.0
  CHANGELOG.md
Labels: Semver: UNRELATED, 🔮 Type: Chore

#492 Decoupled html template from Webpack
  packages/application-components/package.json
  packages/application-shell/src/index.js
  packages/assets/html-page/favicon.png
  packages/assets/html-page/favicon_144x144px.png
  packages/assets/html-page/favicon_57x57px.png
  packages/assets/html-page/favicon_72x72px.png
  packages/assets/html-page/google977a5fb1d7733002.html
  packages/assets/html-page/robots.txt
  packages/assets/images/ct-logo.svg
  packages/assets/index.js
  packages/assets/package.json
  packages/mc-html-template/README.md
  packages/mc-html-template/lib/generate.js
  packages/mc-html-template/lib/html-scripts/.eslintrc.yaml
  packages/mc-html-template/lib/html-scripts/data-layer.js
  packages/mc-html-template/lib/html-scripts/index.js
  packages/mc-html-template/lib/html-scripts/loading-screen.js
  packages/mc-html-template/lib/html-styles/index.js
  packages/mc-html-template/lib/html-styles/loading-screen.css
  packages/mc-html-template/lib/index.js
  packages/mc-html-template/lib/load-env.js
  packages/mc-html-template/lib/load-headers.js
  packages/mc-html-template/lib/utils/create-asset-hash.js
  packages/mc-html-template/lib/utils/replace-html-placeholders.js
  packages/mc-html-template/lib/utils/sanitize-app-environment.js
  packages/mc-html-template/package.json
  packages/mc-html-template/webpack.js
  packages/mc-http-server/bin/start-mc.js
  packages/mc-http-server/load-options.js
  packages/mc-scripts/config/application-runtime.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/config/webpack-dev-server.config.js
  packages/mc-scripts/webpack-plugins/local-html-webpack-plugin.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review
