Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-07, with the labels that each got.

#810 refactor(website): to use syntax highlighting plugin for vscode themes
  website/content/deployment/example-now-v1.mdx
  website/content/main-concepts/data-fetching.mdx
  website/gatsby-config.js
  website/package.json
  website/src/components/code-block.js
  website/src/components/index.js
  website/src/pages/code-snippets/getting-started-npm-install.mdx
  website/src/pages/code-snippets/getting-started-npx-install.mdx
  website/src/pages/index.js
  website/src/templates/markdown.js
  yarn.lock
Labels: 🖥 Type: Website

#813 refactor(app-shell): to remove team count
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#814 feat(app-shell): allow to disable menu items per env
  .prettierignore
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/navbar/__snapshots__/navbar.spec.js.snap
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#818 fix(jest/setup): to show actual error logs on CI when something is logged to console
  packages/jest-preset-mc-app/setup-tests.js
Labels: 🔮 Type: Chore

#827 feat(app-shell): track main menu click
  packages/application-shell/README.md
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#829 v14 -> refactor: remove vendorsToTranspile
  packages/mc-scripts/config/create-webpack-config-for-production.js
Labels: 💥 Type: Breaking Change

#832 fix(html-template/compile-html): to use correct option for useLocalAssets
  packages/mc-html-template/lib/compile-html.js
  packages/mc-scripts/compile-html.js
Labels: 🐛 Type: Bug

#834 refactor(assets): rename images
  packages/application-components/src/components/maintenance-page-layout/README.md
  packages/application-components/src/components/page-not-found/page-not-found.js
  packages/application-shell/src/components/error-apologizer/error-apologizer.js
  packages/application-shell/src/components/failed-authentication/failed-authentication.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/project-expired/project-expired.js
  packages/application-shell/src/components/project-not-found/project-not-found.js
  packages/application-shell/src/components/project-not-initialized/project-not-initialized.js
  packages/application-shell/src/components/project-suspended/project-suspended.js
  packages/assets/README.md
  packages/assets/images/camera-chain-broken.svg
  packages/assets/images/camera-chain.svg
  packages/assets/images/camera-crossed.svg
  packages/assets/images/camera.svg
  packages/assets/images/desert-fox.svg
  packages/assets/images/diagonal-line.svg
  packages/assets/images/doors-closed.svg
  packages/assets/images/folder-full-locked.svg
  packages/assets/images/hourglass.svg
  packages/assets/images/icecream.svg
  packages/assets/images/locked-diamond.svg
Labels: ⛑ Type: Refactoring

#838 refactor(permissions): to use sentry for error reporting
  packages/permissions/src/components/authorized/authorized.tsx
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#840 chore: update dependencies
  package.json
  packages/actions-global/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  playground/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#842 refactor(app-shell/quick-acess): to use new permissions
  packages/application-shell/src/components/quick-access/constants.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#849 chore: update deps
  package.json
  visual-testing-app/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#851 refactor(quick-access): leftover for permissions cleanup
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/sub-commands.js
Labels: ⛑ Type: Refactoring

#859 feat(app-shell): add passing `teamId` in link and middleware
  packages/application-shell/src/apollo-links/__snapshots__/header-link.spec.js.snap
  packages/application-shell/src/apollo-links/header-link.js
  packages/application-shell/src/apollo-links/header-link.spec.js
  packages/application-shell/src/configure-store.js
  packages/application-shell/src/constants.js
  packages/application-shell/src/utils/index.js
  packages/application-shell/src/utils/select-team-id-from-local-storage/index.js
  packages/application-shell/src/utils/select-team-id-from-local-storage/select-team-id-from-local-storage.js
  packages/sdk/src/middleware/middleware.js
  packages/sdk/src/middleware/middleware.spec.js
Labels: 📬 Resolution: Accepted, 🚀 Type: New Feature

#865 docs: improve docs about usage of shouldDelayOnClose prop of ModalPage
  packages/application-components/src/components/modal-pages/form-modal-page/README.md
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.mdx
  packages/application-components/src/components/modal-pages/info-modal-page/README.md
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.mdx
  packages/application-components/src/components/modal-pages/tabular-modal-page/README.md
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.mdx
Labels: ✍️ Type: Documentation, 🖥 Type: Website

#885 refactor(browser-history): to convert to TS
  packages/browser-history/index.ts
  packages/browser-history/package.json
  packages/browser-history/src/enhanced-history.ts
  packages/browser-history/src/index.ts
  packages/browser-history/src/version.ts
  packages/browser-history/tsconfig.declarations.json
  packages/browser-history/tsconfig.json
Labels: ⛑ Type: Refactoring

#884 refactor(notifications): to convert to TS
  package.json
  packages/notifications/index.ts
  packages/notifications/package.json
  packages/notifications/src/action-creators.ts
  packages/notifications/src/action-creators/action-creators.js
  packages/notifications/src/action-creators/action-creators.spec.js
  packages/notifications/src/action-creators/index.js
  packages/notifications/src/action-types.ts
  packages/notifications/src/constants.js
  packages/notifications/src/index.ts
  packages/notifications/src/middleware.ts
  packages/notifications/src/middleware/index.js
  packages/notifications/src/middleware/middleware.js
  packages/notifications/src/middleware/middleware.spec.js
  packages/notifications/src/notifications.spec.ts
  packages/notifications/src/reducer.ts
  packages/notifications/src/reducer/index.js
  packages/notifications/src/reducer/reducer.js
  packages/notifications/src/reducer/reducer.spec.js
  packages/notifications/src/types.ts
  packages/notifications/src/version.ts
  packages/notifications/tsconfig.declarations.json
  packages/notifications/tsconfig.json
  yarn.lock
Labels: ⛑ Type: Refactoring

#883 feat: add support for action rights though `allAppliedActionRights`
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/project-container/project-container.spec.js
  packages/application-shell/src/test-utils/test-utils.js
  packages/permissions/README.md
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#890 chore: add vrts for notification components
  .eslintrc.yaml
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.visualroute.js
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualroute.js
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.visualroute.js
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.visualroute.js
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.visualroute.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.visualroute.js
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.visualspec.js
  packages/application-components/src/components/page-not-found/page-not-found.visualroute.js
  packages/react-notifications/src/components/notification/notification.mod.css
  packages/react-notifications/src/components/notifications.visualroute.js
  packages/react-notifications/src/components/notifications.visualspec.js
  visual-testing-app/package.json
  visual-testing-app/src/App.js
  visual-testing-app/test-utils/index.js
  visual-testing-app/test-utils/spec.js
  visual-testing-app/test-utils/suite.js
  visual-testing-app/webpack.config.js
Labels: 👨‍⚕️ Type: Tests

#891 fix(permissions): to drill props
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#893 refactor(permissions): restricted-by-permissions to rtl
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
Labels: 👨‍⚕️ Type: Tests

#894 feat(app-shell): add api clients to quick access
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/messages.js
  packages/i18n/data/core.json
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#898 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/application-shell/src/test-utils/test-utils.js
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/create-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/jest-stylelint-runner/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#899 chore: remove regenerator-runtime
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#897 chore: update react-intl to 3.0.0-beta.19
  application-templates/starter/package.json
  jest.test.config.js
  packages/application-components/package.json
  packages/application-components/src/components/page-not-found/messages.js
  packages/application-components/src/components/page-not-found/page-not-found.js
  packages/application-components/src/components/page-not-found/page-not-found.spec.js
  packages/application-shell/package.json
  packages/i18n/data/core.json
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
  packages/i18n/data/fr_FR.json
  packages/i18n/data/zh_CN.json
  packages/jest-preset-mc-app/jest-preset.js
  packages/jest-preset-mc-app/vendors-to-transpile.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/config/vendors-to-transpile.js
  packages/mc-scripts/extract-intl.js
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#901 chore: update react-intl to 3.0.0-beta.20
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#902 refactor(jest-preset): to split typescript config from default preset
  jest.test.config.js
  packages/jest-preset-mc-app/jest-preset-for-typescript.js
  packages/jest-preset-mc-app/jest-preset.js
Labels: ⛑ Type: Refactoring

#903 chore: use recent version 5.4.3 of intl-messageformat
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#904 chore: remove (deprecated) storage package
  packages/storage/LICENSE
  packages/storage/README.md
  packages/storage/index.ts
  packages/storage/package.json
  packages/storage/src/index.ts
  packages/storage/src/version.ts
  packages/storage/tsconfig.declarations.json
  packages/storage/tsconfig.json
Labels: 🔮 Type: Chore

#905 fix(mc-scripts): to use paths to package directory instead of entry points
  packages/mc-scripts/config/vendors-to-transpile.js
Labels: 🐛 Type: Bug

#912 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-http-server/package.json
  packages/react-notifications/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#915 chore(mc-http-server): update to node v12
  packages/mc-http-server/Dockerfile
Labels: 🔮 Type: Chore

#914 chore: enable eslint rules for react hooks
  .eslintrc.yaml
  packages/application-shell/src/components/configure-intl-provider/configure-intl-provider.js
  packages/react-notifications/src/components/notifications-list/notifications-list.tsx
  packages/react-notifications/src/components/notifier/notifier.tsx
  website/src/layouts/internals/layout-sidebar.js
  website/src/templates/markdown.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#916 refactor: default props type declarations
  packages/permissions/src/components/authorized/authorized.tsx
  packages/react-notifications/src/components/notification/notification.spec.tsx
  packages/react-notifications/src/components/notification/notification.tsx
  packages/react-notifications/src/components/notifier/notifier.tsx
  tsconfig.json
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it
