Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-11, with the labels that each got.

#1139 chore(app-shell): add logging to tracking
  packages/application-shell/src/utils/gtm.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1140 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1147 fix(app-shell): to merge internal feature flags with provided ones
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
  packages/application-shell/src/feature-toggles.js
Labels: 🐛 Type: Bug

#1150 chore: bump to node 12
  .circleci/config.yml
  .nvmrc
  playground/Dockerfile
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1149 test(setup-tests): ignore CellMeasurerCach warning
  packages/jest-preset-mc-app/setup-tests.js
Labels: 🔮 Type: Chore

#1153 feat(app-shell): to use all feature toggles query
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/fetch-all-menu-feature-toggles.proxy.graphql
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/index.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js
  schemas/proxy.json
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1157 fix(app-shell): falling back to default
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.js
Labels: 🐛 Type: Bug

#1159 fix(app-shell): return object with default values
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js
Labels: 🐛 Type: Bug

#1160 Update description in cloudfront example
  website/src/content/deployment/example-aws-s3-cloudfront.mdx
Labels: 🖥 Type: Website

#1163 fix the logic of isAuthorized and Authorized
  packages/permissions/src/components/authorized/authorized.spec.tsx
  packages/permissions/src/components/authorized/authorized.tsx
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: 🚀 Status: ship it

#1165 fix: cannot use rerender with app-kit custom render functions
  packages/application-shell/src/test-utils/test-utils.js
  packages/application-shell/src/test-utils/test-utils.spec.js
Labels: 🚀 Status: ship it

#1168 chore: replace deprecated rollup deps
  package.json
  rollup.config.js
  yarn.lock
Labels: 🤖 Type: Dependencies

#1169 refactor(website): upgrade to theme 1.0.0-canary.28
  website-components-playground/package.json
  website/gatsby-config.js
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/use-additional-site-data.js
  website/src/components/links-card.js
  website/src/components/playground-controller.js
  website/src/layouts/marketing.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1171 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1173 refactor: only some subset of demanded DF values should belong to actual DF values
  packages/permissions/src/utils/has-permissions.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1175 docs(changelog): v15.3.9
  CHANGELOG.md
Labels: 🚀 Status: ship it

#1181 chore(website): update docs theme to canary.42
  website/gatsby-config.js
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1183 fix(app-shell): portal container height to fix tabbing in modals
  packages/application-shell/src/components/portals-container/portals-container.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it
