Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-05, with the labels that each got.

#593 refactor(website): to re-organize components
  website/src/components/index.js
  website/src/components/layout.js
  website/src/components/markdown-layout.js
  website/src/components/text-highlight.js
  website/src/layouts/content.js
  website/src/layouts/index.js
  website/src/layouts/internals/content-pagination.js
  website/src/layouts/internals/globals.js
  website/src/layouts/internals/layout-container.js
  website/src/layouts/internals/layout-footer.js
  website/src/layouts/internals/layout-header.js
  website/src/layouts/internals/layout-main.js
  website/src/layouts/internals/layout-sidebar.js
  website/src/layouts/internals/navbar.js
  website/src/layouts/marketing.js
  website/src/pages/404.js
  website/src/pages/index.js
  website/src/templates/markdown.js
Labels: ⛑ Type: Refactoring

#594 fix(app-shell): back to project peforming full page reload
  packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/back-to-project/back-to-project.js
  packages/application-shell/src/components/back-to-project/back-to-project.spec.js
  packages/application-shell/src/components/back-to-project/index.js
  packages/application-shell/src/components/back-to-project/messages.js
Labels: Semver: FIX, 🙏 Status: Dev Review

#598 chore: update deps
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  website/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#599 feat(app-shell): add "Manage Projects" to Quick Access
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/messages.js
  packages/i18n/data/core.json
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#602 refactor(app-shell): remove old feature flags
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: Semver: FIX, 🐛 Type: Bug

#606 👯‍♀️ chore: update flopflip 👯‍♀️
  packages/application-shell/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#615 refactor: use non deprecated custom props
  packages/application-components/test-utils/visual/spec.js
Labels: ⛑ Type: Refactoring

#616 chore: move deprecated custom prop internal
  packages/application-shell/src/components/app-bar/app-bar.mod.css
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css
  packages/react-notifications/src/components/notification/notification.mod.css
Labels: 🔮 Type: Chore

#618 refactor(project-switcher): refactor to use ui kit select input
  packages/application-shell/src/components/project-switcher/__snapshots__/project-switcher.spec.js.snap
  packages/application-shell/src/components/project-switcher/project-switcher.js
  packages/application-shell/src/components/project-switcher/project-switcher.mod.css
  packages/application-shell/src/components/project-switcher/project-switcher.spec.js
Labels: ⛑ Type: Refactoring

#617 refactor(application-shell): use ui kit select input for locale switcher
  packages/application-shell/src/components/locale-switcher/locale-switcher.js
  packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css
  packages/application-shell/src/components/locale-switcher/locale-switcher.spec.js
Labels: ⛑ Type: Refactoring

#621 chore: remove react-select v1
  application-templates/starter/src/index.js
  packages/application-shell/package.json
  playground/package.json
  playground/src/index.js
  yarn.lock
Labels: 🔮 Type: Chore

#622 chore: update changelog for version 13.4.2
  CHANGELOG.md
Labels: 🔮 Type: Chore

#619 fix(application-components): ui-kit peer dep
  packages/application-components/package.json
Labels: Semver: FIX, 🐛 Type: Bug

#623 refactor: remove projects list toggle
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/feature-toggles.js
Labels: Semver: FIX, ⛑ Type: Refactoring, 🙏 Status: Dev Review

#625 fix(application-shell, react-notifications): fix invalid shadow
  packages/application-shell/src/components/app-bar/app-bar.mod.css
  packages/react-notifications/src/components/notification/notification.mod.css
Labels: 🐛 Type: Bug

#624 feat(permissions): add use-is-authorized hook
  packages/application-shell-connectors/src/components/application-context/application-context.js
  packages/application-shell-connectors/src/components/application-context/index.js
  packages/application-shell-connectors/src/index.js
  packages/permissions/src/hooks/index.js
  packages/permissions/src/hooks/use-is-authorized/index.js
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.js
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.js
Labels: Semver: FEATURE, 🙏 Status: Dev Review, 🚀 Type: New Feature

#626 chore: update changelog for `13.5.0`
  CHANGELOG.md
Labels: 🔮 Type: Chore

#627 fix(app-shell): to default to menu if no submenus are defined
  packages/application-shell/src/components/navbar/navbar.js
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#634 chore: update deps
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-scripts/package.json
  packages/sentry/package.json
  rollup.config.js
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore

#636 feat(components): add ModalPage component
  packages/application-components/src/components/modal-page/README.md
  packages/application-components/src/components/modal-page/index.js
  packages/application-components/src/components/modal-page/modal-page.js
  packages/application-components/src/components/modal-page/modal-page.mod.css
  packages/application-components/src/components/modal-page/modal-page.story.js
  packages/application-components/src/components/modal-page/modal-page.visualroute.js
  packages/application-components/src/components/modal-page/modal-page.visualspec.js
  packages/application-components/src/index.js
Labels: 🚀 Type: New Feature

#638 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/mc-scripts/start.js
  packages/react-notifications/package.json
  packages/sentry/package.json
  playground/package.json
  website/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#637 feat(app-shell): add menuVisibility to menu query
  application-templates/starter/package.json
  lerna.json
  packages/application-shell/package.json
  packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql
  packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
  playground/package.json
Labels: Semver: FEATURE, 🙏 Status: Dev Review, 🚀 Type: New Feature

#639 docs(changelog): for v13.6.0 [skip ci]
  CHANGELOG.md
Labels: Semver: UNRELATED

#640 feat(app-shell): add manage organizations
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/components/quick-access/messages.js
  packages/application-shell/src/components/quick-access/quick-access.js
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/i18n/data/core.json
Labels: Semver: FEATURE, 💅 Type: Enhancement, 🙏 Status: Dev Review

#643 chore: update flopflip
  packages/application-shell/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore

#650 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#651 fix(circleci): to use new compare-url orb
  .circleci/config.yml
Labels: Semver: UNRELATED, 🙏 Status: Dev Review

#652 fix(app-shell): Switcher counter not properly centered
  packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css
  packages/application-shell/src/components/project-switcher/project-switcher.mod.css
Labels: Semver: FIX, 🐛 Type: Bug

#654 chore: update deps
  application-templates/starter/package.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/create-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-scripts/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  visual-testing-app/package.json
  website/package.json
  yarn.lock
Labels: Semver: FIX, 🔮 Type: Chore, 🙏 Status: Dev Review

#656 fix(app-shell): quick access env not always set
  packages/application-shell/src/components/quick-access/quick-access.js
Labels: Semver: FIX, 🐛 Type: Bug

#664 chore: update deps
  .circleci/config.yml
  package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  website/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#669 chore(mc-scripts): update with upstream react-scripts for (relevant) latest changes
  packages/mc-scripts/build.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/package.json
  packages/mc-scripts/start.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review
