Repository commercetools/merchant-center-application-kit, pull requests merged in 2019-12, with the labels that each got.

#1186 chore: update docs theme canary.60
  now.json
  package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.mdx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.mdx
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.mdx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.mdx
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.mdx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.mdx
  website-components-playground/gatsby-node.js
  website-components-playground/package.json
  website-components-playground/src/components/example-wrapper.js
  website-components-playground/src/components/intl-controller.js
  website-components-playground/src/components/modal-controller.js
  website-components-playground/src/components/playground-controller.js
  website-components-playground/src/hooks/use-window-height.js
  website-components-playground/src/layouts/layout-app.js
  website-components-playground/src/pages/confirmation-dialog.js
  website-components-playground/src/pages/form-dialog.js
  website-components-playground/src/pages/form-modal-page.js
  website-components-playground/src/pages/index.js
  website-components-playground/src/pages/info-dialog.js
  website-components-playground/src/pages/info-modal-page.js
  website-components-playground/src/pages/tabular-modal-page.js
  website/gatsby-config.js
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  website/src/components/playground-controller.js
  website/src/components/playground.js
  website/src/content/beta.mdx
  website/src/content/components/index.mdx
  website/src/content/deployment/example-aws-s3-cloudfront.mdx
  website/src/content/deployment/example-firebase.mdx
  website/src/content/deployment/example-now-v1.mdx
  website/src/content/deployment/http-server.mdx
  website/src/content/deployment/index.mdx
  website/src/content/deployment/production-build.mdx
  website/src/content/development/folder-structure.mdx
  website/src/content/development/index.mdx
  website/src/content/getting-started/index.mdx
  website/src/content/getting-started/installing-a-starter-application.mdx
  website/src/content/main-concepts/index.mdx
  website/src/content/register-applications/index.mdx
  website/src/layouts/marketing.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1191 chore: update lockfile
  yarn.lock
Labels: 🤖 Type: Dependencies

#1192 test: refactor some tests to RTL
  packages/application-shell/src/components/gtm-booter/gtm-booter.js
  packages/application-shell/src/components/gtm-booter/gtm-booter.spec.js
  packages/application-shell/src/components/gtm-user-logout-tracker/gtm-user-logout-tracker.js
  packages/application-shell/src/components/gtm-user-logout-tracker/gtm-user-logout-tracker.spec.js
  packages/application-shell/src/components/gtm-user-tracker/gtm-user-tracker.js
  packages/application-shell/src/components/gtm-user-tracker/gtm-user-tracker.spec.js
  packages/application-shell/src/components/project-switcher/project-switcher-test-utils.js
  packages/application-shell/src/components/project-switcher/project-switcher.spec.js
  packages/application-shell/src/components/route-catch-all/route-catch-all.js
  packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js
Labels: 👨‍⚕️ Type: Tests

#1196 chore(website): update to theme 1.0.0
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  website/src/components/links-card.js
  website/src/layouts/marketing.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1182 chore: lint markdown content using vale and CT writing style
  .circleci/config.yml
  .gitignore
  .vscode/settings.json
  jest-runner-executor.config.js
  jest.text.config.js
  package.json
  website/src/content/deployment/example-aws-s3-cloudfront.mdx
  website/src/content/deployment/example-firebase.mdx
  website/src/content/deployment/example-now-v1.mdx
  website/src/content/deployment/http-server.mdx
  website/src/content/deployment/production-build.mdx
  website/src/content/deployment/runtime-configuration.mdx
  website/src/content/deployment/serving-static-assets.mdx
  website/src/content/deployment/static-server.mdx
  website/src/content/development/available-scripts.mdx
  website/src/content/development/folder-structure.mdx
  website/src/content/development/menu-links.mdx
  website/src/content/development/styling.mdx
  website/src/content/development/testing.mdx
  website/src/content/development/translations.mdx
  website/src/content/getting-started/installing-a-starter-application.mdx
  website/src/content/getting-started/tooling.mdx
  website/src/content/main-concepts/application-shell.mdx
  website/src/content/main-concepts/architecture.mdx
  website/src/content/main-concepts/data-fetching.mdx
  website/src/content/main-concepts/proxy-to-external-api.mdx
  website/src/content/register-applications/activating-a-custom-application.mdx
  website/src/content/register-applications/caveats.mdx
  website/src/content/register-applications/configuring-a-custom-application.mdx
  website/src/content/register-applications/deleting-a-custom-application.mdx
  yarn.lock
Labels: 🙏 Status: Dev Review

#1198 chore: check npm authentication on prerelease
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1202 fix: babel macros with react-intl
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/index.js
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#1197 docs(website): document what a custom app is, add draft for service contract
  CHANGELOG.md
  package.json
  website-components-playground/package.json
  website/gatsby-config.js
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  website/src/components/links-card.js
  website/src/content/beta.mdx
  website/src/content/deployment/example-aws-s3-cloudfront.mdx
  website/src/content/deployment/example-firebase.mdx
  website/src/content/deployment/example-now-v1.mdx
  website/src/content/deployment/production-build.mdx
  website/src/content/development/translations.mdx
  website/src/content/getting-started/installing-a-starter-application.mdx
  website/src/content/getting-started/what-is-a-custom-application.mdx
  website/src/content/main-concepts/api-gateway.mdx
  website/src/content/main-concepts/architecture.mdx
  website/src/content/register-applications/activating-a-custom-application.mdx
  website/src/content/register-applications/configuring-a-custom-application.mdx
  website/src/data/navigation.yaml
  website/src/layouts/marketing.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#987 refactor(vrt): move visual specs into VRT app
  .eslintrc.yaml
  .gitignore
  @types/commercetools-uikit__text-field/index.d.ts
  @types/commercetools-uikit__text-input/index.d.ts
  jest-puppeteer.config.js
  jest.visual.config.js
  package.json
  packages/babel-preset-mc-app/index.js
  packages/jest-stylelint-runner/run.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  postcss.config.js
  tsconfig.json
  visual-testing-app/env.json
  visual-testing-app/index.html
  visual-testing-app/package.json
  visual-testing-app/src/App.js
  visual-testing-app/src/application.tsx
  visual-testing-app/src/components/confirmation-dialog/confirmation-dialog.visualroute.tsx
  visual-testing-app/src/components/confirmation-dialog/confirmation-dialog.visualspec.ts
  visual-testing-app/src/components/form-dialog/form-dialog.visualroute.tsx
  visual-testing-app/src/components/form-dialog/form-dialog.visualspec.ts
  visual-testing-app/src/components/form-modal-page/form-modal-page.visualroute.tsx
  visual-testing-app/src/components/form-modal-page/form-modal-page.visualspec.ts
  visual-testing-app/src/components/info-dialog/info-dialog.visualroute.tsx
  visual-testing-app/src/components/info-dialog/info-dialog.visualspec.ts
  visual-testing-app/src/components/info-modal-page/info-modal-page.visualroute.tsx
  visual-testing-app/src/components/info-modal-page/info-modal-page.visualspec.ts
  visual-testing-app/src/components/notifications/notifications.visualroute.tsx
  visual-testing-app/src/components/notifications/notifications.visualspec.ts
  visual-testing-app/src/components/page-not-found/page-not-found.visualroute.tsx
  visual-testing-app/src/components/page-not-found/page-not-found.visualspec.ts
  visual-testing-app/src/components/tabular-modal-page/tabular-modal-page.visualroute.tsx
  visual-testing-app/src/components/tabular-modal-page/tabular-modal-page.visualspec.ts
  visual-testing-app/src/constants.ts
  visual-testing-app/src/index.js
  visual-testing-app/src/index.tsx
  visual-testing-app/src/test-utils/index.ts
  visual-testing-app/src/test-utils/spec.tsx
  visual-testing-app/src/test-utils/suite.tsx
  visual-testing-app/tsconfig.json
  visual-testing-app/webpack.config.dev.js
  visual-testing-app/webpack.config.js
  visual-testing-app/webpack.config.prod.js
  website-components-playground/src/pages/tabular-modal-page.js
  yarn.lock
Labels: 🏕 Type: Technical Exploration, 🛠 Type: Tooling

#1210 chore: update flopflip to latest
  .renovaterc.json
  packages/application-shell/package.json
  packages/application-shell/src/test-utils/test-utils.spec.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🤖 Type: Dependencies

#1213 fix(dev-auth): parsing of error responses
  packages/mc-dev-authentication/views/login.js
Labels: 🐛 Type: Bug

#1214 fix(app-shell): retry unauthenticated requests for graphql errors
  packages/application-shell/src/apollo-links/error-link.js
  packages/application-shell/src/apollo-links/error-link.spec.js
Labels: 🐛 Type: Bug

#1215 fix: building type declarations
  packages/actions-global/tsconfig.declarations.json
  packages/application-components/tsconfig.declarations.json
  packages/application-shell-connectors/tsconfig.declarations.json
  packages/browser-history/tsconfig.declarations.json
  packages/constants/tsconfig.declarations.json
  packages/i18n/package.json
  packages/i18n/tsconfig.declarations.json
  packages/l10n/package.json
  packages/l10n/tsconfig.declarations.json
  packages/notifications/tsconfig.declarations.json
  packages/permissions/tsconfig.declarations.json
  packages/react-notifications/tsconfig.declarations.json
  packages/sdk/tsconfig.declarations.json
  packages/sentry/tsconfig.declarations.json
  packages/url-utils/tsconfig.declarations.json
Labels: 🐛 Type: Bug

#1217 chore: pull latest schemas and regenerate types
  @types-extensions/graphql-proxy.d.ts
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell-connectors/src/types/generated/settings.ts
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/proxy.ts
  packages/application-shell/src/types/generated/settings.ts
  schemas/ctp.json
  schemas/mc.json
  schemas/settings.json
Labels: 🛠 Type: Tooling
