Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-01, with the labels that each got.

#1220 fix(app-shell): null check
  packages/application-shell/src/apollo-links/error-link.js
Labels: 🐛 Type: Bug

#1223 chore: update docs
  packages/l10n/README.md
Labels: ✍️ Type: Documentation, 🙏 Status: Dev Review

#1222 refactor(app-shell): rewrite tests for ProjectDataLocale, use functional components
  packages/application-shell/src/components/project-data-locale/project-data-locale.js
  packages/application-shell/src/components/project-data-locale/project-data-locale.spec.js
Labels: ⛑ Type: Refactoring

#1228 fix(app-shell): denormalization of action rights
  packages/application-shell/src/test-utils/test-utils.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1229 chore: regenerate graphql types
  @types-extensions/graphql-mc.d.ts
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/normalizers.spec.ts
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell-connectors/src/types/generated/settings.ts
  packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql
  packages/application-shell/src/components/project-switcher/project-switcher-fragments.mc.graphql
  packages/application-shell/src/components/project-switcher/project-switcher.mc.graphql
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/settings.ts
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  schemas/ctp.json
Labels: 🛠 Type: Tooling

#1232 refactor(mc-scripts): sync with latest react-scripts
  packages/mc-scripts/build.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/config/webpack-dev-server.config.js
Labels: 💅 Type: Enhancement

#1231 test(app-shell): rewrite top level tests to integration and e2e tests
  cypress/integration/playground/application-shell.js
  cypress/plugins/index.js
  cypress/support/commands.js
  graphql-test-utils/apply-mocks-for-external-network-requests.js
  graphql-test-utils/create-graphql-mock-server.js
  graphql-test-utils/cypress/add-commands.js
  graphql-test-utils/cypress/task.js
  graphql-test-utils/graphql-mocks/mc.js
  graphql-test-utils/graphql-mocks/proxy.js
  graphql-test-utils/graphql-models/project.js
  graphql-test-utils/graphql-models/user.js
  graphql-test-utils/index.js
  graphql-test-utils/resolve-and-cache-schema.js
  package.json
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.js
  packages/application-shell/src/components/application-shell-provider/utils.spec.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/project-suspended/index.js
  packages/application-shell/src/components/redirector/redirector.js
  packages/constants/src/constants.ts
  playground/src/components/entry-point/entry-point.js
  yarn.lock
Labels: 👨‍⚕️ Type: Tests

#1238 feat(actions-global): add use-hide-all-page-notifications
  packages/actions-global/src/hooks/index.ts
  packages/actions-global/src/hooks/use-hide-all-page-notifications.ts
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#1240 feat(actions-global): to add use-on-action-error
  packages/actions-global/src/actions/handle-action-error.ts
  packages/actions-global/src/hooks/index.ts
  packages/actions-global/src/hooks/use-on-action-error.ts
Labels: 💅 Type: Enhancement

#1242 fix(mc-scripts): allowing to opt-out of parallel builds
  packages/mc-scripts/config/create-webpack-config-for-production.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#1243 docs(changelog): for v15.7.0 [skip ci]
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#1244 refactor(website): layout for landing page to latest designs
  website/gatsby-config.js
  website/package.json
  website/src/components/links-card.js
  website/src/icons/landing-page-rocket.svg
  website/src/icons/screen-bulb-icon.svg
  website/src/icons/screen-cog-icon.svg
  website/src/icons/screen-design-tool-icon.svg
  website/src/images/landing-page-background.png
  website/src/layouts/marketing.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1250 feat(sdk): add useAsyncDispatch for resolving async sdk actions (static types)
  packages/sdk/src/hooks/use-async-dispatch.ts
  packages/sdk/src/index.ts
Labels: 🚀 Type: New Feature

#1254 fix(babel-preset-mc-app): remove uncalled-for plugins
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1245 refactor(website): improve landing page
  website/src/layouts/marketing.js
  website/src/pages/index.js
  website/static/Liquid-Cheese.svg
Labels: 🖥 Type: Website

#1256 refactor(lint-staged): remove unnecessary git add
  lint-staged.config.js
Labels: 🛠 Type: Tooling

#1255 test(app-shell): add more higher level tests to app-shell, cleanup some old enzyme test
  packages/application-shell/src/components/app-bar/app-bar.js
  packages/application-shell/src/components/app-bar/app-bar.spec.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/locale-switcher/locale-switcher.js
  packages/application-shell/src/components/locale-switcher/locale-switcher.spec.js
  packages/application-shell/src/components/project-container/project-container.js
  packages/application-shell/src/components/project-container/project-container.spec.js
  packages/application-shell/src/constants.js
Labels: 👨‍⚕️ Type: Tests

#1241 feat(app-shell): add launchdarkly tracking subgroup
  graphql-test-utils/graphql-models/user.js
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql
  packages/application-shell/src/components/fetch-user/fetch-user.spec.js
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
  packages/application-shell/src/test-utils/test-utils.js
  packages/application-shell/src/types/generated/mc.ts
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  schemas/ctp.json
  schemas/mc.json
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#1205 docs(website): support policy
  .vscode/settings.json
  website/gatsby-config.js
  website/src/content/support-policy.mdx
Labels: ✍️ Type: Documentation, 🖥 Type: Website, 🙏 Status: Dev Review

#1258 test(app-shell): migrate navbar specs to RTL
  cypress/integration/playground/application-shell.js
  graphql-test-utils/graphql-mocks/proxy.js
  graphql-test-utils/graphql-mocks/settings.js
  graphql-test-utils/graphql-models/application-appbar-menu.js
  graphql-test-utils/graphql-models/application-navbar-menu.js
  graphql-test-utils/graphql-models/application-navbar-submenu.js
  graphql-test-utils/graphql-models/custom-application.js
  graphql-test-utils/graphql-models/project-extension.js
  graphql-test-utils/index.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/navbar/navbar.js
  packages/application-shell/src/components/navbar/navbar.spec.js
Labels: 👨‍⚕️ Type: Tests, 🙏 Status: Dev Review

#1249 feat: send performance timing values to GTM
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.js
  packages/application-shell/src/components/application-shell/application-shell.js
  packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.js
  packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js
  packages/application-shell/src/components/gtm-application-tracker/index.js
  packages/application-shell/src/track-performance.js
  packages/application-shell/src/utils/gtm.js
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#1260 refactor(app-shell): deprecate MeasureFirstPaint
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/performance-timing/actions.js
  packages/application-shell/src/components/performance-timing/conversions.js
  packages/application-shell/src/components/performance-timing/conversions.spec.js
  packages/application-shell/src/components/performance-timing/measure-first-paint.js
  packages/application-shell/src/components/performance-timing/measure-first-paint.spec.js
  packages/permissions/package.json
Labels: ⛑ Type: Refactoring

#1259 fix(permissions): data fences to be overwritten by manage resource permission
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1262 chore: ignore .vscode/settings.json, add recommended.code-workspace
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  recommended.code-workspace
Labels: 🔮 Type: Chore

#1263 chore: update jest
  .eslintrc.yaml
  application-templates/starter/package.json
  jest.d.ts
  package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-scripts/package.json
  packages/sdk/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1267 refactor: fix and improve docs and usage of permissions
  application-templates/starter/menu.json
  application-templates/starter/src/routes.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/quick-access/create-commands.js
  packages/application-shell/src/test-utils/README.md
  packages/permissions/README.md
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/sdk/README.md
  playground/menu.json
  playground/src/routes.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1261 chore(permissions): add warnings to propose improvements
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  packages/jest-preset-mc-app/.gitignore
  packages/jest-preset-mc-app/setup-tests.js
  packages/permissions/package.json
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
  yarn.lock
Labels: 💥 Type: Breaking Change, 🖐 Status: On Hold

#1272 chore: regenerate schema types, use ctp project used for e2e tests
  .env.template
  cypress/.env.template
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  schemas/ctp.json
  schemas/mc.json
  yarn.lock
Labels: 🛠 Type: Tooling

#1270 feat(website): to use new top menu and footer
  website/package.json
  website/src/layouts/marketing.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1278 docs(website): content wording improvements
  .gitignore
  .vscode/spellright.dict
  application-templates/starter/src/components/entry-point/entry-point.js
  application-templates/starter/src/load-messages.js
  lint-staged.config.js
  package.json
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.mdx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.mdx
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.mdx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.mdx
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.mdx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.mdx
  recommended.code-workspace
  website/package.json
  website/src/content/deployment/example-aws-s3-cloudfront.mdx
  website/src/content/deployment/example-firebase.mdx
  website/src/content/deployment/example-now-v1.mdx
  website/src/content/deployment/production-build.mdx
  website/src/content/deployment/runtime-configuration.mdx
  website/src/content/deployment/serving-static-assets.mdx
  website/src/content/development/available-scripts.mdx
  website/src/content/development/folder-structure.mdx
  website/src/content/development/menu-links.mdx
  website/src/content/development/styling.mdx
  website/src/content/development/testing.mdx
  website/src/content/development/translations.mdx
  website/src/content/getting-started/installing-a-starter-application.mdx
  website/src/content/getting-started/tooling.mdx
  website/src/content/getting-started/what-is-a-custom-application.mdx
  website/src/content/main-concepts/api-gateway.mdx
  website/src/content/main-concepts/architecture.mdx
  website/src/content/main-concepts/authentication.mdx
  website/src/content/main-concepts/data-fetching.mdx
  website/src/content/main-concepts/graphql.mdx
  website/src/content/main-concepts/proxy-to-external-api.mdx
  website/src/content/register-applications/activating-a-custom-application.mdx
  website/src/content/register-applications/configuring-a-custom-application.mdx
  website/src/content/register-applications/deleting-a-custom-application.mdx
  website/src/content/support-policy.mdx
  website/src/data/navigation.yaml
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1285 fix(website): use noUnderline prop to configure link styles
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  website/src/components/links-card.js
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1283 docs(components): improve documentation of static Intl exports
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.mdx
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.mdx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx
  packages/application-components/src/components/modal-pages/custom-form-modal-page/custom-form-modal-page.mdx
  packages/application-components/src/components/modal-pages/custom-form-modal-page/custom-form-modal-page.tsx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.mdx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.mdx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
Labels: ✍️ Type: Documentation

#1288 refactor(website): pull latest and next releases from repo
  website/.gitignore
  website/gatsby-config.js
  website/package.json
  website/scripts/get_latest_release.sh
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/use-additional-site-data.js
  website/src/pages/index.js
Labels: 🖥 Type: Website, 🚀 Status: ship it

#1290 chore: define needed type declaration deps in each package.json
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/browser-history/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  yarn.lock
Labels: 🔮 Type: Chore

#1291 chore: add homepage link and directory to each package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/assets/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/create-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/jest-stylelint-runner/package.json
  packages/l10n/package.json
  packages/mc-dev-authentication/package.json
  packages/mc-html-template/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
Labels: ✍️ Type: Documentation

#1287 docs(website): document missing things, link READMEs to docs
  packages/application-shell/README.md
  packages/application-shell/src/test-utils/README.md
  website/package.json
  website/src/content/components/application-shell.mdx
  website/src/content/deployment/example-deployment-aws-s3-cloudfront.mdx
  website/src/content/deployment/example-deployment-firebase.mdx
  website/src/content/deployment/example-deployment-now-v1.mdx
  website/src/content/deployment/example-deployment-now-v2.mdx
  website/src/content/deployment/http-server.mdx
  website/src/content/deployment/runtime-configuration.mdx
  website/src/content/deployment/serving-static-assets.mdx
  website/src/content/development/available-scripts.mdx
  website/src/content/development/menu-links.mdx
  website/src/content/development/testing.mdx
  website/src/content/development/translations.mdx
  website/src/content/development/typescript.mdx
  website/src/content/getting-started/installing-a-starter-application.mdx
  website/src/content/getting-started/tooling.mdx
  website/src/content/main-concepts/application-shell.mdx
  website/src/content/main-concepts/architecture.mdx
  website/src/content/main-concepts/authentication.mdx
  website/src/content/main-concepts/data-fetching.mdx
  website/src/content/main-concepts/graphql.mdx
  website/src/content/main-concepts/proxy-endpoints.mdx
  website/src/content/main-concepts/proxy-to-external-api.mdx
  website/src/content/main-concepts/user-permissions.mdx
  website/src/content/register-applications/activating-a-custom-application.mdx
  website/src/content/register-applications/caveats.mdx
  website/src/content/register-applications/configuring-a-custom-application.mdx
  website/src/content/register-applications/deleting-a-custom-application.mdx
  website/src/content/register-applications/removing-a-custom-application.mdx
  website/src/data/navigation.yaml
  website/src/images/mc-apps-removal.png
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1293 fix(components): explicitly define intl message type, to generate correct prop-types
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx
  packages/application-components/src/components/dialogs/internals/dialog-footer.tsx
  packages/application-components/src/components/modal-pages/custom-form-modal-page/custom-form-modal-page.tsx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx
  packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.tsx
  packages/application-components/src/components/modal-pages/internals/default-form-buttons.tsx
  packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.tsx
  packages/application-components/src/components/modal-pages/internals/modal-page.tsx
  packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
Labels: 🐛 Type: Bug

#1294 fix(permissions): to match inferred data fence (view when manage)
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/permissions/src/utils/has-permissions.spec.tsx
  packages/permissions/src/utils/has-permissions.ts
Labels: 🐛 Type: Bug
