Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-10, with the labels that each got.

#1772 test(app-kit): remove use of `enzyme` in playground and application-templates/starter
  .changeset/dry-onions-tap.md
  application-templates/starter/src/components/entry-point/entry-point.spec.js
  playground/src/components/entry-point/entry-point.spec.js
Labels: 👨‍⚕️ Type: Tests, 🚀 Status: ship it, 🧟 Type: Technical Debt

#1775 fix(csp): use wildcard for sentry.io for matching subdomains
  .changeset/beige-beers-join.md
  packages/mc-html-template/src/process-headers.js
Labels: 🐛 Type: Bug

#1780 [Breaking] refactor(application-shell): remove support for `trackingEventWhitelist`
  .changeset/ninety-masks-repair.md
  packages/application-shell/src/components/application-shell/application-shell.tsx
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1781 [Breaking] chore(application-shell): remove deprecated components.
  .changeset/weak-mails-train.md
  packages/application-shell/src/components/async-chunk-loader/async-chunk-loader.spec.js
  packages/application-shell/src/components/async-chunk-loader/async-chunk-loader.tsx
  packages/application-shell/src/components/async-chunk-loader/index.ts
  packages/application-shell/src/components/handle-apollo-errors/README.md
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.spec.js
  packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.tsx
  packages/application-shell/src/components/handle-apollo-errors/index.ts
  packages/application-shell/src/index.ts
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1784 feat(user): add business role to application context
  .changeset/brown-crabs-bake.md
  .env.template
  .graphqlrc.yml
  graphql-test-utils/graphql-models/user.js
  package.json
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell-connectors/src/types/generated/settings.ts
  packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql
  packages/application-shell/src/test-utils/test-utils.tsx
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/proxy.ts
  packages/application-shell/src/types/generated/settings.ts
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  schemas/ctp.json
  schemas/mc.json
  schemas/settings.json
  test-data/user/generator.ts
  test-data/user/types.ts
  yarn.lock
Labels: 🚀 Status: ship it

#1782 test(express): use msw instead of nock
  packages-backend/express/package.json
  packages-backend/express/src/middlewares/session-middleware.spec.ts
Labels: ⛑ Type: Refactoring

#1788 fix(app-shell/components): keyboard navigation of user settings menu
  .changeset/clean-snakes-sort.md
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1802 refactor(app-shell): to remove disabledMenuItems support
  .changeset/odd-bobcats-happen.md
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/constants/src/constants.ts
Labels: 🖐 Status: On Hold, 🙏 Status: Dev Review

#1809 fix(app-shell): default cache policy for apps menu
  .changeset/little-snakes-sniff.md
  packages/application-shell/src/configure-apollo.ts
Labels: 🚀 Status: ship it

#1811 fix(sentry): to use beforeSend to omit some data
  .changeset/angry-lions-rush.md
  packages/sentry/src/sentry.spec.ts
  packages/sentry/src/sentry.ts
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1815 fix(test-utils): pass the apollo cache to the mocked provider
  .changeset/big-pugs-pay.md
  packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js
  packages/application-shell/src/test-utils/test-utils.tsx
  website/src/content/development/testing.mdx
Labels: 🚀 Status: ship it

#1816 fix(quick access): wrong navigation when using product commands
  .changeset/violet-fireants-hope.md
  packages/application-shell/src/components/quick-access/create-commands.ts
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/quick-access/sub-commands.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#1827 refactor(playground): to use explicit imports of React
  .changeset/moody-melons-arrive.md
  playground/src/components/echo-server/echo-server.js
  playground/src/components/entry-point/entry-point.js
  playground/src/components/state-machines-details/state-machines-details.js
  playground/src/components/state-machines-list-connector/state-machines-list-connector.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1828 refactor(playground): to use new automatic jsx runtime
  .changeset/friendly-news-agree.md
  playground/.env
  playground/.eslintrc.js
  playground/src/components/echo-server/echo-server.js
  playground/src/components/entry-point/entry-point.js
  playground/src/components/entry-point/entry-point.spec.js
  playground/src/components/state-machines-details/state-machines-details.js
  playground/src/components/state-machines-list-connector/state-machines-list-connector.js
  playground/src/components/state-machines-list/state-machines-list.js
  playground/src/components/state-machines-list/state-machines-list.spec.js
  playground/src/index.js
  playground/src/routes.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1835 feat(graphql targets): added change history graphql target
  .changeset/young-rings-kiss.md
  packages/application-shell/src/apollo-links/utils.spec.js
  packages/constants/src/constants.ts
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1838 fix(webpack): babel preset syntax
  .changeset/plenty-lies-serve.md
  packages/mc-scripts/src/config/create-webpack-config-for-development.js
  packages/mc-scripts/src/config/create-webpack-config-for-production.js
Labels: 🚀 Status: ship it

#1842 fix(mc-scripts): to add jsx runtime for js files not only svg
  .changeset/old-carpets-accept.md
  packages/mc-scripts/src/config/create-webpack-config-for-development.js
  packages/mc-scripts/src/config/create-webpack-config-for-production.js
Labels: 🐛 Type: Bug

#1844 fix(babel): pragma frag to be Fragment not React.Fragment
  .changeset/fifty-jeans-shave.md
  packages/babel-preset-mc-app/index.js
Labels: 🚀 Status: ship it
