Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-09, with the labels that each got.

#1717 fix(sentry): update versions, use allowUrls option instead of denyUrls
  .changeset/pink-paws-tap.md
  package.json
  packages-backend/loggers/package.json
  packages/application-shell/package.json
  packages/sentry/package.json
  packages/sentry/src/sentry.ts
  yarn.lock
Labels: 🚀 Status: ship it

#1718 feat(i18n): use compiled data
  .changeset/lovely-dogs-allow.md
  package.json
  packages/i18n/src/load-i18n.ts
Labels: 🚀 Status: ship it

#1722 refactor: consistent naming for `examples-starter`
  .changeset/serious-maps-sniff.md
  website/src/content/deployment/example-deployment-vercel.mdx
  website/src/content/getting-started/installing-a-starter-application.mdx
  website/src/content/register-applications/configuring-a-custom-application.mdx
Labels: ✍️ Type: Documentation, 👶 good first contribution, 🚀 Status: ship it

#1723 Fix notifications styles issue (alignment and links color)
  .changeset/tender-llamas-retire.md
  packages/react-notifications/src/components/notification/notification.styles.ts
Labels: 🐛 Type: Bug, 💅 Type: Enhancement, 🚀 Status: ship it

#1725 docs(installing-starter): add `account` endpoint
  .changeset/nervous-beers-exercise.md
  website/src/content/getting-started/installing-a-starter-application.mdx
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1728 Update Application Shell link in the docs
  website/src/content/getting-started/tooling.mdx
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1730 docs(support-policy): improve wording
  .changeset/odd-tips-sleep.md
  website/src/content/support-policy.mdx
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1742 docs(proxy-external): add description of decoded JWT claims
  .changeset/three-readers-invent.md
  website/src/content/main-concepts/proxy-to-external-api.mdx
Labels: 👶 good first contribution, 🚀 Status: ship it

#1752 docs(website): fix heading level
  website/src/content/main-concepts/proxy-to-external-api.mdx
Labels: 🚀 Status: ship it

#1754 fix(application-shell): to support token retry on mc backend graphql …
  .changeset/fifty-spiders-kneel.md
  packages/application-shell/src/apollo-links/token-retry-link.spec.js
  packages/application-shell/src/apollo-links/token-retry-link.ts
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/fetch-user/fetch-user.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1755 feat(app-shell): add ability to `skipTokenRetry` with variable
  .changeset/chilled-snakes-thank.md
  packages/application-shell/src/apollo-links/token-retry-link.spec.js
  packages/application-shell/src/apollo-links/token-retry-link.ts
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/authenticated/am-i-logged-in.tsx
  packages/application-shell/src/constants.ts
  packages/application-shell/src/utils/apollo-context.ts
Labels: 🙏 Status: Dev Review

#1756 fix(app-shell): error link to support opting out of token retry
  .changeset/breezy-eels-jam.md
  packages/application-shell/src/apollo-links/error-link.spec.js
  packages/application-shell/src/apollo-links/error-link.ts
  packages/application-shell/src/apollo-links/token-retry-link.spec.js
  packages/application-shell/src/apollo-links/token-retry-link.ts
  packages/application-shell/src/apollo-links/utils.spec.js
  packages/application-shell/src/apollo-links/utils.ts
Labels: 🙏 Status: Dev Review

#1764 fix(app-shell): to handle errors without extentions property
  .changeset/cold-points-doubt.md
  packages/application-shell/src/apollo-links/error-link.spec.js
  packages/application-shell/src/apollo-links/error-link.ts
  packages/application-shell/src/apollo-links/utils.ts
Labels: 🙏 Status: Dev Review

#1767 chore(package.json): upgrade ui-kit
  .changeset/nasty-trains-try.md
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  yarn.lock
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1751 docs: add `compile-html`
  .changeset/light-moose-learn.md
  website/src/content/deployment/compiling-a-custom-application.mdx
  website/src/content/deployment/http-server.mdx
  website/src/content/deployment/production-build.mdx
  website/src/content/deployment/serving-static-assets.mdx
  website/src/content/deployment/static-server.mdx
  website/src/content/development/available-scripts.mdx
  website/src/data/navigation.yaml
Labels: ✍️ Type: Documentation, 🖥 Type: Website

#1743 Define test data for user and project, using new core package
  package.json
  packages/application-shell/src/components/fetch-project/fetch-project.spec.tsx
  packages/application-shell/src/components/fetch-user/fetch-user.spec.tsx
  test-data/organization/builder.ts
  test-data/organization/generator.ts
  test-data/organization/index.ts
  test-data/organization/presets/index.ts
  test-data/organization/transformers.ts
  test-data/organization/types.ts
  test-data/project/builder.ts
  test-data/project/fields/applied-action-right/builder.ts
  test-data/project/fields/applied-action-right/generator.ts
  test-data/project/fields/applied-action-right/index.ts
  test-data/project/fields/applied-action-right/transformers.ts
  test-data/project/fields/applied-action-right/types.ts
  test-data/project/fields/applied-menu-visibilities/builder.ts
  test-data/project/fields/applied-menu-visibilities/generator.ts
  test-data/project/fields/applied-menu-visibilities/index.ts
  test-data/project/fields/applied-menu-visibilities/transformers.ts
  test-data/project/fields/applied-menu-visibilities/types.ts
  test-data/project/fields/applied-permission/builder.ts
  test-data/project/fields/applied-permission/generator.ts
  test-data/project/fields/applied-permission/index.ts
  test-data/project/fields/applied-permission/transformers.ts
  test-data/project/fields/applied-permission/types.ts
  test-data/project/fields/applied-store-data-fence/builder.ts
  test-data/project/fields/applied-store-data-fence/generator.ts
  test-data/project/fields/applied-store-data-fence/index.ts
  test-data/project/fields/applied-store-data-fence/transformers.ts
  test-data/project/fields/applied-store-data-fence/types.ts
  test-data/project/fields/expiry/builder.ts
  test-data/project/fields/expiry/generator.ts
  test-data/project/fields/expiry/index.ts
  test-data/project/fields/expiry/transformers.ts
  test-data/project/fields/expiry/types.ts
  test-data/project/fields/suspension/builder.ts
  test-data/project/fields/suspension/generator.ts
  test-data/project/fields/suspension/index.ts
  test-data/project/fields/suspension/transformers.ts
  test-data/project/fields/suspension/types.ts
  test-data/project/generator.ts
  test-data/project/index.ts
  test-data/project/presets/index.ts
  test-data/project/transformers.ts
  test-data/project/types.ts
  test-data/user/builder.ts
  test-data/user/generator.ts
  test-data/user/index.ts
  test-data/user/presets/index.ts
  test-data/user/transformers.ts
  test-data/user/types.ts
  yarn.lock
Labels: 👨‍⚕️ Type: Tests, 🙏 Status: Dev Review, 🚀 Status: ship it

#1771 fix(navbar): timing of updating menu open local storage to eliminate navbar state change during window resize
  .changeset/tall-eyes-deliver.md
  packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
Labels: 🐛 Type: Bug, 🚀 Status: ship it
