Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-03, with the labels that each got.

#1373 docs: changelog for v16.3.3
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#1374 fix(jest-preset): to not throw on createFactory
  packages/jest-preset-mc-app/setup-tests.js
Labels: 👨‍⚕️ Type: Tests, 🙏 Status: Dev Review

#1375 fix(permissions): to warn only once for condition and message
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1378 fix(dev authentication): replace trailing slash in mcApiUrl
  packages/mc-dev-authentication/views/login.pug
Labels: 🐛 Type: Bug

#1379 fix(app-shell): regression to render menu divider
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
Labels: 🐛 Type: Bug

#1380 feat(mc-html-template): add support env variable placeholders
  packages/mc-html-template/lib/load-env.js
  packages/mc-html-template/lib/load-env.spec.js
Labels: 🚀 Type: New Feature

#1386 docs(mc-html-template): add docs for placeholders
  .vscode/spellright.dict
  packages/mc-html-template/README.md
  website/src/content/deployment/runtime-configuration.mdx
Labels: ✍️ Type: Documentation

#1387 chore: update flopflip
  packages/application-shell/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1395 PCM-1600: routes to product varitns from quick access
  packages/application-shell/src/components/quick-access/quick-access.tsx
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1396 refactor: to not use wait-for-element
  application-templates/starter/src/components/main-view/main-view.spec.js
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/application-shell/src/components/fetch-project/fetch-project.spec.js
  packages/application-shell/src/components/fetch-user/fetch-user.spec.js
  packages/application-shell/src/components/inject-reducers/inject-reducers.spec.js
  packages/application-shell/src/components/project-data-locale/project-data-locale.spec.js
  packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx
  packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/react-notifications/src/components/notifications-list/notifications-list.spec.tsx
  packages/react-notifications/src/components/notifier/notifier.spec.tsx
  playground/src/components/state-machines-list/state-machines-list.spec.js
Labels: ⛑ Type: Refactoring

#1397 refactor: to use waitFor and waitForElementToBeRemoved
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.spec.tsx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.tsx
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.spec.tsx
  packages/application-shell/src/components/application-loader/application-loader.spec.js
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/authenticated/authenticated.spec.tsx
  packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx
  packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js
  packages/application-shell/src/components/gtm-booter/gtm-booter.spec.tsx
  packages/application-shell/src/components/gtm-user-logout-tracker/gtm-user-logout-tracker.spec.js
  packages/application-shell/src/components/gtm-user-tracker/gtm-user-tracker.spec.js
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx
  packages/application-shell/src/components/requests-in-flight-loader/requests-in-flight-loader.spec.tsx
  packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js
  packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.tsx
  packages/application-shell/src/test-utils/test-utils.spec.tsx
  packages/i18n/src/async-locale-data/async-locale-data.spec.tsx
  packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx
  packages/react-notifications/src/components/notifier/notifier.spec.tsx
  playground/src/components/state-machines-list/state-machines-list.spec.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1398 refactor: to use location module
  application-templates/starter/package.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/application-shell/application-shell.tsx
  packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx
  packages/application-shell/src/components/back-to-project/back-to-project.tsx
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx
  packages/application-shell/src/components/project-switcher/project-switcher.tsx
  packages/application-shell/src/components/quick-access/create-commands.ts
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/quick-access/quick-access.tsx
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.tsx
  packages/application-shell/src/components/redirector/redirector.tsx
  packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js
  packages/application-shell/src/components/route-catch-all/route-catch-all.tsx
  packages/application-shell/src/utils/location/index.ts
  packages/application-shell/src/utils/location/location.ts
  packages/jest-preset-mc-app/package.json
  packages/react-notifications/package.json
  yarn.lock
Labels: ⛑ Type: Refactoring

#1400 fix(quick-access): to not use global.replace under test
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#1389 refactor(test-utils): drop unused gtmTracking option
  packages/application-shell/src/test-utils/test-utils.tsx
  playground/src/components/state-machines-details/state-machines-details.js
  playground/src/components/state-machines-list/state-machines-list.spec.js
  website/src/content/development/testing.mdx
Labels: 👨‍⚕️ Type: Tests

#1401 feat(jest-preset): add preset for jsdom sixteen
  packages/jest-preset-mc-app/jest-preset-for-jsdom-sixteen.js
  packages/jest-preset-mc-app/package.json
  yarn.lock
Labels: 🚀 Type: New Feature

#1402 chore: to use jsdom sixteen under test
  jest.test.config.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
Labels: 👨‍⚕️ Type: Tests, 🚀 Status: ship it

#1403 fix(quick-access): link to pim search list
  packages/application-shell/src/components/quick-access/create-commands.ts
  packages/application-shell/src/components/quick-access/messages.ts
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/i18n/data/core.json
Labels: 🐛 Type: Bug

#1405 docs: add 'Help Needed' page
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/documentation_deployment_examples.md
  .github/ISSUE_TEMPLATE/documentation_improvements.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request_deployment_examples.md
  packages/babel-preset-mc-app/index.js
  website/src/content/help-needed.mdx
  website/src/content/register-applications/caveats.mdx
  website/src/data/navigation.yaml
  website/src/images/chrome-cookie-setting.png
Labels: 🖥 Type: Website

#1406 fix(jest-preset-mc-app): add mutation-observer-shim
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/setup-tests.js
  yarn.lock
Labels: 🤖 Type: Dependencies

#1407 fix: revert "fix: remove old product list from quick access"
  packages/application-shell/src/components/quick-access/create-commands.ts
  packages/application-shell/src/components/quick-access/messages.ts
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/i18n/data/core.json
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1411 fix: proper invocation of window.location.replace
  packages/application-shell/src/utils/location/location.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#1412 docs: update changelog for v16.5.2
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#1394 fix(apollo-caching): simplify id from object logic
  packages/application-shell/src/configure-apollo.ts
Labels: 🐛 Type: Bug

#1415 refactor: hasDemandeDataFences -> hasDemandedDataFences
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1416 Properly report unhandled rejections and ErrorEvents to Sentry
  packages/sentry/src/sentry.spec.ts
  packages/sentry/src/sentry.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#1418 docs(website): mention limitations of forward-to proxy endpoint
  website/src/content/main-concepts/proxy-to-external-api.mdx
Labels: 🖥 Type: Website
