Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-06, with the labels that each got.

#1547 feat(app-shell): fetch organization name with owner
  .changeset/cool-geckos-know.md
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/components/application-context/normalizers.spec.ts
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/test-utils/test-utils.spec.tsx
  packages/application-shell/src/test-utils/test-utils.tsx
  packages/application-shell/src/types/generated/mc.ts
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1557 refactor(website): to use new design for landing page
  website/src/content/index.mdx
  website/src/icons/web-developer.svg
  website/src/pages/fragments/based-on-design-system.mdx
  website/src/pages/fragments/built-on-modern-technologies.mdx
  website/src/pages/fragments/zero-config-development-tools.mdx
  website/src/pages/index.js
  website/static/Liquid-Cheese.svg
Labels: 🖥 Type: Website

#1558 docs(website): missing australia hostname
  website/src/content/main-concepts/api-gateway.mdx
Labels: 🖥 Type: Website

#1570 build(eslint): enable react/no-unused-prop-types rule
  .changeset/dry-cars-kiss.md
  packages/eslint-config-mc-app/index.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🛠 Type: Tooling

#1572 fix(app-shell): user settings menu labels for opening and closing menu
  .changeset/slimy-grapes-joke.md
  cypress/integration/playground/application-shell.js
  packages/application-shell/src/components/user-settings-menu/messages.ts
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
  packages/i18n/data/core.json
Labels: 🐛 Type: Bug

#1571 fix(app-shell): user settings menu link width for testing
  .changeset/happy-donuts-jam.md
  cypress/integration/playground/application-shell.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
Labels: 🐛 Type: Bug

#1579 feat(eslint-config-mc-app): to add jest-dom plugin
  .changeset/empty-beers-reflect.md
  package.json
  packages/eslint-config-mc-app/index.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1581 fix(eslint-config-mc-app): add missing peer dep
  .changeset/spicy-panthers-clean.md
  packages/eslint-config-mc-app/package.json
Labels: 🙏 Status: Dev Review

#1583 feat(app-shell): to add label to maintenance page layouts
  .changeset/quick-tools-wash.md
  packages/application-components/src/components/maintenance-page-layout/README.md
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.spec.tsx
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.tsx
  packages/application-components/src/components/page-not-found/page-not-found.tsx
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/application-shell/src/components/error-apologizer/error-apologizer.tsx
  packages/application-shell/src/components/failed-authentication/failed-authentication.tsx
  packages/application-shell/src/components/project-expired/project-expired.tsx
  packages/application-shell/src/components/project-not-found/project-not-found.tsx
  packages/application-shell/src/components/project-not-initialized/project-not-initialized.tsx
  packages/application-shell/src/components/project-suspended/project-suspended.tsx
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🚀 Type: New Feature

#1586 feat(jest-preset-mc-app): add config for rtl
  .changeset/six-pillows-share.md
  packages/jest-preset-mc-app/setup-test-framework.js
Labels: 🙏 Status: Dev Review

#1596 fix(kodiak): to use blocking wording not blacklist
  .kodiak.toml
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1599 feat(template/starter): to add version update script
  .changeset/three-pans-tickle.md
  application-templates/starter/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#1603 fix: add new keys to core.json
  packages/i18n/data/core.json
Labels: 🙏 Status: Dev Review
