Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-11, with the labels that each got.

#1851 refactor(playground): allow to access playground app in our staging env
  .github/workflows/main.yml
  playground/custom-application-config.json
  playground/vercel-deployments/state-machines-gcp-eu/package.json
  playground/vercel-deployments/state-machines-gcp-us/package.json
Labels: 🚀 Status: ship it

#1854 chore: update deps
  .changeset/quiet-jars-draw.md
  application-templates/starter/package.json
  package.json
  packages-backend/express/package.json
  packages-backend/loggers/package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-config/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/assets/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/create-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/jest-stylelint-runner/package.json
  packages/l10n/package.json
  packages/mc-dev-authentication/package.json
  packages/mc-html-template/package.json
  packages/mc-scripts/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  playground/package.json
  rollup.config.js
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🚀 Status: ship it

#1853 chore: add import export api target
  .changeset/thick-wasps-hang.md
  packages/constants/src/constants.ts
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1850 feat(navbar): add `installedApplications` in FetchProjectExtension query, merge with current custom app
  .changeset/kind-donkeys-hunt.md
  graphql-test-utils/graphql-models/application-navbar-menu.js
  graphql-test-utils/graphql-models/application-navbar-submenu.js
  graphql-test-utils/graphql-models/project-extension.js
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell-connectors/src/types/generated/settings.ts
  packages/application-shell/src/components/navbar/fetch-project-extensions-navbar.settings.graphql
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/settings.ts
  schemas/ctp.json
  schemas/mc.json
  schemas/settings.json
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review, 🚀 Status: ship it

#1869 feat(application-shell): add user business role custom dimension tracking
  .changeset/new-baboons-hide.md
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell/src/components/application-shell/application-shell.tsx
  packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js
  packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.tsx
  packages/application-shell/src/components/gtm-booter/gtm-booter.tsx
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/utils/gtm.ts
  schemas/ctp.json
  schemas/mc.json
Labels: 🚀 Status: ship it

#1879 refactor(actions-global/types): add `text` as optional to `TShowNotification`
  .changeset/long-cats-cheat.md
  packages/actions-global/src/types.ts
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1881 feat(navbar): add clock with arrow icon to available application icons
  .changeset/rotten-crabs-promise.md
  @types/commercetools-uikit__icons/index.d.ts
  packages/application-shell/src/components/navbar/navbar.tsx
Labels: 🚀 Status: ship it

#1883 refactor(website): use fontsource package instead of gatsby fonts plugin
  package.json
  website-components-playground/gatsby-config.js
  website-components-playground/package.json
  website-components-playground/src/layouts/layout-app.js
  yarn.lock
Labels: 🚀 Status: ship it

#1887 chore: upgrade ui-kit to latest
  .changeset/forty-months-explode.md
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/i18n/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1885 feat(l10n): add graphql transformers and `localize`
  .changeset/young-months-sing.md
  packages/l10n/README.md
  packages/l10n/package.json
  packages/l10n/src/index.ts
  packages/l10n/src/localize.spec.ts
  packages/l10n/src/localize.ts
  packages/l10n/src/types.ts
  packages/l10n/src/utils.ts
  yarn.lock
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1897 feat: add new constraint values to dialog size props
  .changeset/calm-suns-burn.md
  @types/commercetools-uikit__design-system/index.d.ts
  packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx
  packages/application-components/src/components/dialogs/info-dialog/info-dialog.tsx
  packages/application-components/src/components/dialogs/internals/dialog-container.tsx
  packages/application-components/src/components/dialogs/internals/dialog.styles.ts
  visual-testing-app/src/components/confirmation-dialog/confirmation-dialog.visualroute.tsx
  visual-testing-app/src/components/form-dialog/form-dialog.visualroute.tsx
  visual-testing-app/src/components/info-dialog/info-dialog.visualroute.tsx
  visual-testing-app/src/test-utils/spec.tsx
Labels: 🚀 Status: ship it

#1902 fix(application-shell/test-utils): `storeState` render option of `renderAppWithRedux` is unusable
  .changeset/eighty-dogs-brake.md
  packages/application-shell/src/configure-store.ts
  packages/application-shell/src/test-utils/test-utils.spec.tsx
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1904 refactor(l10n/localize): export transformLocalizedFieldToLocalizedString
  .changeset/tricky-kiwis-drive.md
  packages/l10n/src/index.ts
  packages/l10n/src/localize.ts
  packages/l10n/src/types.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it
