Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-02, with the labels that each got.

#1296 feat(website): enable search
  website/gatsby-config.js
  website/package.json
  website/src/layouts/marketing.js
  website/src/pages/fragments/based-on-design-system.mdx
  website/src/pages/fragments/built-on-modern-technologies.mdx
  website/src/pages/fragments/zero-config-development-tools.mdx
  website/src/pages/index.js
  yarn.lock
Labels: 🖥 Type: Website

#1299 chore(website): update to theme 1.7.5
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1301 docs(website): fix title case, add basic info about ui-kit
  website/gatsby-config.js
  website/src/content/components/ui-kit.mdx
  website/src/content/support-policy.mdx
Labels: 🖥 Type: Website

#1300 fix(app-shell): to read project key from url again when location changes
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/application-shell/application-shell.tsx
  packages/application-shell/src/components/quick-access/index.tsx
  playground/src/components/state-machines-details/state-machines-details.js
Labels: 🐛 Type: Bug

#1302 docs(website): improve documentation around data fetching
  website/src/content/main-concepts/data-fetching.mdx
Labels: 🖥 Type: Website

#1305 fix(create-mc-app): escape white spaces in project path
  packages/create-mc-app/src/steps/download-template.js
  packages/create-mc-app/src/steps/update-package-info.js
Labels: 🐛 Type: Bug

#1306 fix: use main ui-kit package as peer dependency
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.tsx
  packages/application-shell/src/test-utils/test-utils.spec.tsx
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website/src/content/development/testing.mdx
  yarn.lock
Labels: 🐛 Type: Bug

#1308 fix: keep ui-kit peer dep
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/react-notifications/package.json
Labels: 🐛 Type: Bug

#1311 fix: force canary releases to always publish all packages
  package.json
Labels: 🛠 Type: Tooling

#1309 chore: run CI jobs with github actions
  .circleci/config.yml
  .github/workflows/main.yml
  .nowignore
  README.md
  jest-puppeteer.config.js
  package.json
  playground/package.json
Labels: 🛠 Type: Tooling

#1312 refactor(create-mc-app): to run tasks using listr output
  packages/create-mc-app/bin/create-mc-app.js
  packages/create-mc-app/package.json
  packages/create-mc-app/src/hint-outdated-version.js
  packages/create-mc-app/src/logger.js
  packages/create-mc-app/src/parse-arguments.js
  packages/create-mc-app/src/steps/download-template.js
  packages/create-mc-app/src/steps/install-dependencies.js
  packages/create-mc-app/src/steps/parse-arguments.js
  packages/create-mc-app/src/steps/success.js
  packages/create-mc-app/src/steps/update-package-info.js
  packages/create-mc-app/src/tasks/download-template.js
  packages/create-mc-app/src/tasks/index.js
  packages/create-mc-app/src/tasks/install-dependencies.js
  packages/create-mc-app/src/tasks/update-package-info.js
  packages/create-mc-app/src/utils.js
  yarn.lock
Labels: 💅 Type: Enhancement

#1292 docs(website): add first draft of user permissions
  website/src/content/main-concepts/user-permissions.mdx
Labels: ✍️ Type: Documentation

#1314 fix(application-menu): pass `useFullRedirectsForLinks` to ApplicationMenu
  packages/application-shell/src/components/navbar/navbar.tsx
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1313 feat(actions): add job to test installation of template apps
  .github/workflows/main.yml
  .gitignore
  packages/create-mc-app/bin/create-mc-app.js
  packages/i18n/package.json
  scripts/build-tarballs.js
  scripts/install-template.js
Labels: 👨‍⚕️ Type: Tests

#1317 chore: update docs-kit to 1.7.6
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1318 chore(actions): skip workflow if CHANGELOG file changed
  .github/workflows/main.yml
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1319 fix: publish canary only if lerna detects that packages changed
  scripts/release_canary.sh
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1321 fix(actions): check out with depth 50 to allow proper canary versions on master branch
  .github/workflows/main.yml
  scripts/release_canary.sh
Labels: 🔮 Type: Chore

#1322 refactor(app-shell): sdk and apollo to fallback to build `mcApiUrl` from origin
  packages/application-shell/src/configure-apollo.ts
  packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.spec.js
  packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.ts
  packages/application-shell/src/utils/get-mc-api-url/index.ts
  packages/application-shell/src/utils/index.ts
  packages/sdk/src/middleware/client.ts
  packages/sdk/src/utils/index.ts
  packages/sdk/src/utils/utils.spec.ts
  packages/sdk/src/utils/utils.ts
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1323 fix(tracking): infinite loop in getHierarchy
  packages/application-shell/src/utils/gtm.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1325 chore: update cypress to v4
  package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1327 chore: add skipping of mc api url inferring process
  packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.spec.js
  packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.ts
  packages/sdk/src/utils/utils.spec.ts
  packages/sdk/src/utils/utils.ts
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#1324 chore: update deps 💣
  .eslintrc.yaml
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.spec.tsx
  packages/application-shell/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/create-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/l10n/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🤖 Type: Dependencies

#1328 chore: update flopflip
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/application-shell.tsx
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
  packages/application-shell/src/test-utils/test-utils.tsx
  yarn.lock
Labels: 🤖 Type: Dependencies

#1329 docs: changelog for v16.2.0
  CHANGELOG.md
Labels: 🙏 Status: Dev Review

#1334 fix(actions): kill server process running the app on port 3001 between cypress runs
  .github/workflows/main.yml
Labels: 🛠 Type: Tooling

#1332 chore: update flopflip and promster
  .github/workflows/main.yml
  package.json
  packages/application-shell/package.json
  packages/mc-http-server/package.json
  packages/mc-http-server/server.js
  yarn.lock
Labels: 🤖 Type: Dependencies

#1336 chore: also kill second server
  .github/workflows/main.yml
Labels: 🛠 Type: Tooling

#1333 docs: testing.mdx
  website/src/content/development/testing.mdx
Labels: ✍️ Type: Documentation

#1337 chore: update lockfile (update minor things)
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/create-mc-app/package.json
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1335 fix(actions-global): method signature of useOnActionError
  packages/actions-global/package.json
  packages/actions-global/src/actions/handle-action-error.ts
  packages/actions-global/src/hooks/use-hide-all-page-notifications.ts
  packages/actions-global/src/hooks/use-on-action-error.spec.tsx
  packages/actions-global/src/hooks/use-on-action-error.ts
  packages/actions-global/src/hooks/use-show-api-error-notification.ts
  packages/actions-global/src/hooks/use-show-notification.ts
  packages/actions-global/src/hooks/use-show-unexpected-error-notification.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1344 chore(website): update to theme 1.7.7
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1345 chore: ignore ts-jest updates (for now)
  .renovaterc.json
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1340 test: fix missing async tests and remove unnecessary usage of beforeEach
  .github/workflows/main.yml
  packages/application-shell/src/components/authenticated/authenticated.spec.tsx
  packages/application-shell/src/components/authenticated/authenticated.tsx
  packages/application-shell/src/components/back-to-project/back-to-project.spec.js
  packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx
  packages/application-shell/src/components/project-switcher/project-switcher-test-utils.ts
  packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx
  packages/application-shell/src/components/requests-in-flight-loader/requests-in-flight-loader.spec.tsx
  packages/application-shell/src/test-utils/test-utils.spec.tsx
Labels: 👨‍⚕️ Type: Tests

#1348 feat(headers/csp): whitelist bucket for asia cloud region
  packages/mc-html-template/lib/load-headers.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1350 chore(website): update to theme 1.8.0
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1346 docs(website): improve docs around csp and cloud regions
  website/src/content/deployment/runtime-configuration.mdx
  website/src/content/main-concepts/api-gateway.mdx
Labels: 🖥 Type: Website

#1351 docs(website): list legacy hostnames
  website/src/content/main-concepts/api-gateway.mdx
Labels: 🖥 Type: Website

#1353 fix(create-mc-app): yarn binary check to not throw
  packages/create-mc-app/src/utils.js
Labels: 🐛 Type: Bug

#1349 docs: add deployment example for ZEIT Now v2, restructure other examples.
  .env.template
  CONTRIBUTING.md
  packages/application-shell-connectors/src/components/application-context/README.md
  packages/jest-preset-mc-app/jest-preset.js
  packages/mc-scripts/config/webpack-dev-server.config.js
  playground/README.md
  playground/production-eu.env.json
  website/src/content/deployment/example-deployment-aws-s3-cloudfront.mdx
  website/src/content/deployment/example-deployment-firebase.mdx
  website/src/content/deployment/example-deployment-now-v1.mdx
  website/src/content/deployment/example-deployment-now-v2.mdx
  website/src/content/deployment/serving-static-assets.mdx
  website/src/content/main-concepts/architecture.mdx
Labels: 🖥 Type: Website

#1355 fix(app-shell): token refetch triggerd by requests from settings service
  packages/application-shell/src/apollo-links/token-retry-link.spec.js
  packages/application-shell/src/apollo-links/token-retry-link.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1357 chore(website): update to theme 1.8.1
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1362 fix(mc-scripts): remove noop service worker middleware from webpack dev server
  packages/mc-scripts/config/webpack-dev-server.config.js
Labels: 🐛 Type: Bug

#1364 chore(website): update MC architecture diagrams
  website/src/images/mc-fe-architecture.png
  website/src/images/mc-http-api.png
Labels: 🖥 Type: Website

#1365 fix(sdk/test-utils): serialize `undefined` as `undefined`
  packages/sdk/package.json
  packages/sdk/src/test-utils/test-utils.spec.ts
  packages/sdk/src/test-utils/test-utils.ts
  yarn.lock
Labels: 🐛 Type: Bug

#1366 chore: update flopflip and promster
  packages/application-shell/package.json
  packages/mc-http-server/package.json
  packages/mc-http-server/server.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🤖 Type: Dependencies

#1368 bug(app-shell-connectors): path mcApiUrl on context env
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/utils/get-mc-api-url/get-mc-api-url.spec.js
  packages/application-shell-connectors/src/utils/get-mc-api-url/get-mc-api-url.ts
  packages/application-shell-connectors/src/utils/get-mc-api-url/index.ts
  packages/constants/src/constants.ts
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review
