Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-04, with the labels that each got.

#1422 docs(website): mention that dev login with SSO is currently not supported
  packages/mc-dev-authentication/views/login.css
  packages/mc-dev-authentication/views/login.pug
  website/src/content/getting-started/installing-a-starter-application.mdx
Labels: 🖥 Type: Website

#1424 fix(l18n): react to only be peer dependency
  application-templates/starter/package.json
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🐛 Type: Bug

#1399 chore: update testing-library/react to v10
  application-templates/starter/package.json
  package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/application-shell/src/components/authenticated/authenticated.spec.tsx
  packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx
  packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js
  packages/application-shell/src/components/gtm-booter/gtm-booter.spec.tsx
  packages/application-shell/src/components/gtm-user-logout-tracker/gtm-user-logout-tracker.spec.js
  packages/application-shell/src/components/gtm-user-tracker/gtm-user-tracker.spec.js
  packages/application-shell/src/components/project-suspended/project-suspended.spec.js
  packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx
  packages/application-shell/src/components/quick-access/quick-access.spec.js
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx
  packages/application-shell/src/components/requests-in-flight-loader/requests-in-flight-loader.spec.tsx
  packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js
  packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js
  packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js
  packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.tsx
  packages/application-shell/src/test-utils/test-utils.spec.tsx
  packages/i18n/src/async-locale-data/async-locale-data.spec.tsx
  packages/jest-preset-mc-app/package.json
  packages/react-notifications/package.json
  packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx
  packages/react-notifications/src/components/notifier/notifier.spec.tsx
  playground/src/components/state-machines-list/state-machines-list.spec.js
  yarn.lock
Labels: 🤖 Type: Dependencies

#1423 feat(jest-preset): allow to configure jest preset
  packages/jest-preset-mc-app/README.md
  packages/jest-preset-mc-app/load-config.js
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/setup-tests.js
Labels: 🚀 Type: New Feature

#1429 chore(ci): continuously deploy playground app to ZEIT
  .github/workflows/main.yml
  playground/.gitignore
  playground/Dockerfile
  playground/config/transformer-now.js
  playground/env.json
  playground/headers.json
  playground/now-deployments/state-machines-gcp-eu/.gitignore
  playground/now-deployments/state-machines-gcp-eu/package.json
  playground/now-deployments/state-machines-gcp-eu/production-gcp-eu.env.json
  playground/now-deployments/state-machines-gcp-eu/production-gcp-eu.headers.json
  playground/now-deployments/state-machines-gcp-eu/routes/fallback.js
  playground/now-deployments/state-machines-gcp-us/.gitignore
  playground/now-deployments/state-machines-gcp-us/package.json
  playground/now-deployments/state-machines-gcp-us/production-gcp-us.env.json
  playground/now-deployments/state-machines-gcp-us/production-gcp-us.headers.json
  playground/now-deployments/state-machines-gcp-us/routes/fallback.js
  playground/package.json
  playground/production-eu.env.json
  playground/production-eu.headers.json
  playground/production-us.env.json
  playground/production-us.headers.json
  scripts/deploy_playground.sh
Labels: 🛠 Type: Tooling

#1430 chore: update deps (among flopflip)
  application-templates/starter/package.json
  package.json
  packages/application-components/src/components/dialogs/internals/dialog-container.tsx
  packages/application-components/src/components/modal-pages/internals/modal-page.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell/package.json
  packages/application-shell/src/apollo-links/token-retry-link.ts
  packages/application-shell/src/components/application-shell/application-shell.tsx
  packages/application-shell/src/components/quick-access/constants.ts
  packages/application-shell/src/components/quick-access/types.ts
  packages/application-shell/src/components/redirector/redirector.tsx
  packages/application-shell/src/constants.ts
  packages/application-shell/src/test-utils/test-utils.tsx
  packages/application-shell/src/tracking-whitelist.ts
  packages/constants/src/constants.ts
  packages/create-mc-app/package.json
  packages/mc-scripts/package.json
  packages/react-notifications/src/components/notifications-list/notifications-list.tsx
  packages/sdk/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1432 chore(website): update to theme 2.4.1-canary.7
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1436 fix(app-shell/test-utils): to defer adapter initialization without flags
  packages/application-shell/src/test-utils/test-utils.tsx
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1433 fix(app-shell): apply cached menu state synchronously as a layout effect, to avoid flickering
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/application-shell/src/components/navbar/use-loading-menu-layout-effect.ts
  packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
Labels: 🙏 Status: Dev Review

#1446 fix(website): rendering of UI component pages
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1447 feat: introduce new package @commercetools-backend/express with utilities for working with Custom Applications
  .eslintignore
  .vscode/spellright.dict
  jest.test.config.js
  package.json
  packages-backend/express/.gitignore
  packages-backend/express/LICENSE
  packages-backend/express/README.md
  packages-backend/express/package.json
  packages-backend/express/src/constants.ts
  packages-backend/express/src/index.ts
  packages-backend/express/src/middlewares/fixtures/jwt-token.ts
  packages-backend/express/src/middlewares/session-middleware.spec.ts
  packages-backend/express/src/middlewares/session-middleware.ts
  packages-backend/express/src/types.ts
  packages-backend/express/tsconfig.build.json
  packages-backend/express/tsconfig.json
  packages-backend/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: 🚀 Type: New Feature

#1450 fix(website): update to docs-kit 2.5.1-canary.2 to fix MDX issues
  package.json
  website-components-playground/package.json
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/markdown-components.js
  website/src/content/support-policy.mdx
  yarn.lock
Labels: 🖥 Type: Website

#1451 refactor(ci): to not use cypress github action
  .github/workflows/main.yml
Labels: 🔮 Type: Chore

#1452 refactor(express): support request handler for serverless functions
  packages-backend/express/README.md
  packages-backend/express/src/auth.ts
  packages-backend/express/src/index.ts
  packages-backend/express/src/middlewares/session-middleware.spec.ts
  packages-backend/express/src/middlewares/session-middleware.ts
  packages-backend/express/src/types.ts
Labels: ⛑ Type: Refactoring

#1453 refactor(express): support backwards compatibility for v1
  packages-backend/express/README.md
  packages-backend/express/src/auth.ts
  packages-backend/express/src/constants.ts
  packages-backend/express/src/middlewares/session-middleware.spec.ts
  packages-backend/express/src/types.ts
  packages-backend/express/src/utils.ts
Labels: ⛑ Type: Refactoring

#1455 fix: typings ref for test utils, treat crypto as an external module
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/sdk/package.json
  rollup.config.js
  yarn.lock
Labels: 🐛 Type: Bug

#1456 feat(headers.json): add support for env variable placeholders
  packages/mc-html-template/lib/load-env.js
  packages/mc-html-template/lib/load-headers.js
  packages/mc-html-template/lib/utils/substitute-env-variable-placeholders.js
  packages/mc-html-template/lib/utils/substitute-env-variable-placeholders.spec.js
  website/src/content/deployment/runtime-configuration.mdx
Labels: 🚀 Type: New Feature

#1457 feat: support forwardTo request config for apollo and sdk
  packages/application-shell/src/apollo-links/header-link.ts
  packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.ts
  packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.ts
  packages/application-shell/src/index.ts
  packages/application-shell/src/utils/apollo-context.ts
  packages/application-shell/src/utils/index.ts
  packages/sdk/README.md
  packages/sdk/src/actions/actions.ts
  website/src/content/main-concepts/data-fetching.mdx
Labels: 🚀 Type: New Feature

#1459 fix(express): do not append trailing slash to audience if request path is "/"
  packages-backend/express/src/auth.ts
Labels: 🐛 Type: Bug

#1458 feat(playground): implement echo server view/api to demo /proxy/forward-to feature
  packages-backend/express/index.ts
  playground/config/transformer-now.js
  playground/env.json
  playground/menu.json
  playground/now-deployments/state-machines-gcp-eu/api/echo.ts
  playground/now-deployments/state-machines-gcp-eu/package.json
  playground/now-deployments/state-machines-gcp-us/api/echo.ts
  playground/now-deployments/state-machines-gcp-us/package.json
  playground/package.json
  playground/src/components/echo-server/echo-server.js
  playground/src/components/echo-server/index.js
  playground/src/routes.js
  yarn.lock
Labels: 🛠 Type: Tooling

#1462 refactor: to update to node v13
  .github/workflows/main.yml
  .nvmrc
  package.json
  packages/mc-http-server/Dockerfile
  yarn.lock
Labels: ⛑ Type: Refactoring

#1461 docs(website): rewrite docs for proxing to external API
  website/src/content/main-concepts/proxy-to-external-api.mdx
Labels: 🖥 Type: Website

#1467 chore: add script to update uikit versions in bulk
  package.json
  packages-backend/express/package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/assets/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/create-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/jest-stylelint-runner/package.json
  packages/l10n/package.json
  packages/mc-dev-authentication/package.json
  packages/mc-html-template/package.json
  packages/mc-http-server/package.json
  packages/mc-scripts/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  yarn.lock
Labels: 🛠 Type: Tooling

#1468 refactor(mc-script): compile it through babel, to support node 10
  application-templates/starter/webpack.config.dev.js
  application-templates/starter/webpack.config.prod.js
  package.json
  packages/mc-scripts/.gitignore
  packages/mc-scripts/README.md
  packages/mc-scripts/bin/mc-scripts.js
  packages/mc-scripts/config/create-webpack-config-for-development.js
  packages/mc-scripts/config/create-webpack-config-for-production.js
  packages/mc-scripts/config/vendors-to-transpile.js
  packages/mc-scripts/package.json
  packages/mc-scripts/src/build.js
  packages/mc-scripts/src/compile-html.js
  packages/mc-scripts/src/config/application-runtime.js
  packages/mc-scripts/src/config/create-webpack-config-for-development.js
  packages/mc-scripts/src/config/create-webpack-config-for-production.js
  packages/mc-scripts/src/config/vendors-to-transpile.js
  packages/mc-scripts/src/config/webpack-dev-server.config.js
  packages/mc-scripts/src/extract-intl.js
  packages/mc-scripts/src/index.js
  packages/mc-scripts/src/start.js
  packages/mc-scripts/src/webpack-plugins/final-stats-writer-plugin.js
  packages/mc-scripts/src/webpack-plugins/local-html-webpack-plugin.js
  playground/webpack.config.dev.js
  playground/webpack.config.prod.js
  visual-testing-app/webpack.config.dev.js
  visual-testing-app/webpack.config.prod.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#1470 refactor(mc-html-template): compile it through babel, to support node 10
  package.json
  packages/create-mc-app/package.json
  packages/jest-preset-mc-app/package.json
  packages/mc-html-template/.gitignore
  packages/mc-html-template/html-scripts/.eslintrc.yaml
  packages/mc-html-template/html-scripts/data-layer.js
  packages/mc-html-template/html-scripts/loading-screen.js
  packages/mc-html-template/html-styles/loading-screen.css
  packages/mc-html-template/package.json
  packages/mc-html-template/src/compile-html.js
  packages/mc-html-template/src/generate-template.js
  packages/mc-html-template/src/index.js
  packages/mc-html-template/src/load-env.js
  packages/mc-html-template/src/load-env.spec.js
  packages/mc-html-template/src/load-headers.js
  packages/mc-html-template/src/load-html-scripts.js
  packages/mc-html-template/src/load-html-styles.js
  packages/mc-html-template/src/utils/create-asset-hash.js
  packages/mc-html-template/src/utils/replace-html-placeholders.js
  packages/mc-html-template/src/utils/sanitize-app-environment.js
  packages/mc-html-template/src/utils/substitute-env-variable-placeholders.js
  packages/mc-html-template/src/utils/substitute-env-variable-placeholders.spec.js
  packages/mc-html-template/webpack.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: ⛑ Type: Refactoring

#1463 refactor(permissions): use Record for dataFences
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/components/application-context/normalizers.ts
  packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
  packages/permissions/src/utils/has-permissions.ts
Labels: 💅 Type: Enhancement

#1471 refactor: to use official rollup plugins
  package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/babel-preset-mc-app/index.js
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  rollup.config.js
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🤖 Type: Dependencies

#1474 fix(babel): keep runtime helpers
  packages/mc-html-template/package.json
  packages/mc-scripts/package.json
Labels: 🚀 Status: ship it
