Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-05, with the labels that each got.

#1472 feat: add loggers package
  packages-backend/express/README.md
  packages-backend/loggers/.gitignore
  packages-backend/loggers/LICENSE
  packages-backend/loggers/README.md
  packages-backend/loggers/index.ts
  packages-backend/loggers/package.json
  packages-backend/loggers/src/create-application-logger.ts
  packages-backend/loggers/src/formatters/rewrite-fields.ts
  packages-backend/loggers/src/index.ts
  packages-backend/loggers/src/middlewares/create-access-logger.ts
  packages-backend/loggers/src/types.ts
  packages-backend/loggers/tsconfig.build.json
  packages-backend/loggers/tsconfig.json
  yarn.lock
Labels: 🚀 Type: New Feature

#1478 refactor(loggers): refine types
  packages-backend/loggers/src/formatters/rewrite-fields.ts
  packages-backend/loggers/src/loggers.spec.ts
Labels: ⛑ Type: Refactoring

#1480 refactor(loggers): remove generic type, as it doesn't really work as expected
  packages-backend/loggers/src/formatters/rewrite-fields.ts
  packages-backend/loggers/src/loggers.spec.ts
Labels: ⛑ Type: Refactoring

#1481 refactor: upgrade to jest v26
  jest.test.config.js
  package.json
  packages/jest-preset-mc-app/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1484 chore: set up changesets
  .changeset/README.md
  .changeset/config.json
  .github/workflows/main.yml
  .github/workflows/release.yml
  .gitignore
  CONTRIBUTING.md
  lerna.json
  package.json
  scripts/changelog.js
  scripts/release_canary.sh
  yarn.lock
Labels: 🛠 Type: Tooling

#1485 fix(mc-html-template): missing babel runtime dep
  .changeset/shiny-colts-eat.md
  packages/mc-html-template/package.json
  packages/mc-scripts/package.json
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1487 Fix mc-dev-authentication's /login link keeping query params
  .changeset/calm-cats-drum.md
  packages/mc-dev-authentication/views/logout.pug
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1492 docs: archive changelog, point to the release notes of each package
  ARCHIVED_CHANGELOG.md
  CHANGELOG.md
Labels: 🚀 Status: ship it

#1495 Fix starter to have `apollo-client` as dependency
  .changeset/soft-beans-deliver.md
  application-templates/starter/package.json
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1493 refactor(mc-http-server): to publish to cloud registry when a git tag is created
  .github/workflows/publish-cloud-registry.yml
  .github/workflows/release.yml
  packages/mc-http-server/cloudbuild.yaml
Labels: 🚀 Status: ship it

#1528 docs(website): rename to Vercel, drop example for Now v1
  .github/workflows/main.yml
  .vscode/spellright.dict
  packages/mc-scripts/src/compile-html.js
  website/README.md
  website/src/content/deployment/example-deployment-now-v1.mdx
  website/src/content/deployment/example-deployment-vercel.mdx
  website/src/data/navigation.yaml
Labels: 🖥 Type: Website

#1529 docs(website): update to theme 4.1.0, pin mdx dep versions
  package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🖥 Type: Website

#1535 refactor(mc-http-server): to use Node.js v14
  .changeset/lovely-wombats-remember.md
  .nvmrc
  packages/mc-http-server/Dockerfile
Labels: 🙏 Status: Dev Review
