Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-08, with the labels that each got.

#1665 fix(app-shell-connectors): default image regex loading to false, allow to skip query
  .changeset/shaggy-donkeys-march.md
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.spec.tsx
  packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.tsx
Labels: 🚀 Status: ship it

#1672 feat(react-notifications) add max resource limit exceeded error translation
  .changeset/chilled-buckets-draw.md
  packages/i18n/data/core.json
  packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx
  packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.tsx
  packages/react-notifications/src/components/notification-kinds/api-error-message/messages.ts
Labels: 🚀 Status: ship it

#1699 chore: update flopflip adapters
  .changeset/nine-penguins-tie.md
  packages/application-shell/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1703 fix(mc-scripts/extract-intl): fix console warning
  .changeset/gold-olives-tie.md
  packages/mc-scripts/src/extract-intl.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it
