Repository commercetools/merchant-center-application-kit, pull requests merged in 2020-12, with the labels that each got.

#1932 refactor: remove second border and spacing for the Github icon
  .changeset/gentle-mayflies-heal.md
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
Labels: 🐛 Type: Bug

#1929 Add Northern Ireland country to the list of available countries list
  .changeset/popular-apes-complain.md
  packages/l10n/data/countries/de.json
  packages/l10n/data/countries/en.json
  packages/l10n/data/countries/es.json
  packages/l10n/data/countries/fr-FR.json
  packages/l10n/data/countries/ja.json
  packages/l10n/data/countries/zh-CN.json
Labels: 🙏 Status: Dev Review

#1933 chore(header-link): add operation name to missing target error
  .changeset/seven-clocks-smell.md
  packages/application-shell/src/apollo-links/header-link.ts
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review
