Repository commercetools/merchant-center-application-kit, pull requests merged in 2021-01, with the labels that each got.

#1953 refactor: to update @flopflip to v12
  .changeset/twenty-moose-explain.md
  @types/omit-empty-es/index.d.ts
  packages/application-shell/package.json
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1952 chore: add and fix manypkg
  .changeset/stale-bears-smell.md
  application-templates/starter/package.json
  package.json
  packages-backend/express/package.json
  packages-backend/loggers/package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-config/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/assets/package.json
  packages/babel-preset-mc-app/package.json
  packages/browser-history/package.json
  packages/constants/package.json
  packages/create-mc-app/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/jest-preset-mc-app/package.json
  packages/jest-stylelint-runner/package.json
  packages/l10n/package.json
  packages/mc-dev-authentication/package.json
  packages/mc-html-template/package.json
  packages/mc-scripts/package.json
  packages/notifications/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  packages/url-utils/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1962 refactor(jest-preset): to remove unhandled promise lockfile
  .changeset/eleven-feet-repeat.md
  packages/jest-preset-mc-app/setup-tests.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1984 [Breaking] Remove deprecated legacy hostnames from default CSP config
  .changeset/lucky-seahorses-drop.md
  packages/mc-html-template/src/process-headers.js
Labels: 💥 Type: Breaking Change

#1961 [Breaking] refactor(eslint-mc-app): simplify and improve usage of eslint config
  .changeset/slow-kiwis-give.md
  .eslintrc.js
  jest.eslint.config.js
  package.json
  packages/actions-global/src/index.ts
  packages/application-shell-connectors/src/index.ts
  packages/application-shell/src/components/quick-access/quick-access.tsx
  packages/eslint-config-mc-app/README.md
  packages/eslint-config-mc-app/helpers/eslint.js
  packages/eslint-config-mc-app/helpers/has-jsx-runtime.js
  packages/eslint-config-mc-app/index.js
  packages/eslint-config-mc-app/package.json
  packages/react-notifications/src/components/notifier/notifier.tsx
  website-components-playground/src/pages/form-dialog.js
  yarn.lock
Labels: 💥 Type: Breaking Change

#1994 fix(mc-html-template): add no-referer policy
  .changeset/gentle-pets-glow.md
  packages/mc-html-template/src/generate-template.js
Labels: 🚀 Status: ship it

#1996 fix(mc-html-template): add no-referer policy to script-tags
  .changeset/red-pigs-breathe.md
  packages/mc-html-template/src/generate-template.js
  packages/mc-html-template/src/utils/replace-html-placeholders.js
Labels: 🙏 Status: Dev Review

#2002 fix(public-page-layout): allow container to flex beyond 100vh
  packages/application-components/src/components/public-page-layout/public-page-layout.tsx
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#2003 chore(public-page-layout): add changeset for #2002
  .changeset/grumpy-lies-turn.md
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#2014 refactor(test-utils): to use flopflip test provider
  .changeset/tidy-llamas-deliver.md
  packages/application-shell/package.json
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
  packages/application-shell/src/test-utils/test-utils.tsx
  yarn.lock
Labels: 🙏 Status: Dev Review

#2016 docs(app-shell): add comment to process.env check
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
Labels: 🙏 Status: Dev Review
