Repository commercetools/merchant-center-application-kit, pull requests merged in 2021-02, with the labels that each got.

#2019 chore: update flopflip
  .changeset/twenty-lions-mate.md
  packages/application-shell/package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#2031 chore: remove redundant key defined in env local template
  .changeset/great-suns-invent.md
  playground/.env
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#2030 fix(authenticated): cache lookup
  .changeset/late-ducks-confess.md
  packages/application-shell/src/components/authenticated/has-cached-authentication-state.ts
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#2033 refactor: to rename to enableLongLivedFeatureFlags
  .changeset/cuddly-kangaroos-hope.md
  packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
  packages/constants/src/constants.ts
Labels: 🙏 Status: Dev Review

#2017 drop product picker
  .changeset/hip-wombats-repair.md
  packages/application-components/experimental/package.json
  packages/application-components/package.json
  packages/application-components/src/experimental/components/index.ts
  packages/application-components/src/experimental/components/internals/centered-loading-spinner/centered-loading-spinner.tsx
  packages/application-components/src/experimental/components/internals/centered-loading-spinner/index.ts
  packages/application-components/src/experimental/components/internals/dropdown-indicator/dropdown-indicator.tsx
  packages/application-components/src/experimental/components/internals/dropdown-indicator/index.ts
  packages/application-components/src/experimental/components/internals/index.ts
  packages/application-components/src/experimental/components/internals/option/index.ts
  packages/application-components/src/experimental/components/internals/option/option.tsx
  packages/application-components/src/experimental/components/product-picker-input/fetch-product-by-prefix.ctp.graphql
  packages/application-components/src/experimental/components/product-picker-input/index.ts
  packages/application-components/src/experimental/components/product-picker-input/messages.ts
  packages/application-components/src/experimental/components/product-picker-input/prefetch-selected-product.ctp.graphql
  packages/application-components/src/experimental/components/product-picker-input/product-picker-input.spec.tsx
  packages/application-components/src/experimental/components/product-picker-input/product-picker-input.tsx
  packages/application-components/src/experimental/hooks/index.ts
  packages/application-components/src/experimental/hooks/use-load-with-prefix-search-fields/index.ts
  packages/application-components/src/experimental/hooks/use-load-with-prefix-search-fields/use-load-with-prefix-search-fields.spec.ts
  packages/application-components/src/experimental/hooks/use-load-with-prefix-search-fields/use-load-with-prefix-search-fields.ts
  packages/application-components/src/experimental/index.ts
  yarn.lock
Labels: ⛑ Type: Refactoring

#2040 docs(contrib): update graphql files section to correct config files
  CONTRIBUTING.md
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#2052 chore(menu): add new icon for use in audit log app, upgrade ui-kit
  .changeset/odd-badgers-listen.md
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  yarn.lock
Labels: 🚀 Status: ship it

#2060 fix(sdk/middleware): support `apply` endpoint for `orderEdits`
  .changeset/breezy-taxis-tie.md
  @types/commercetools__api-request-builder/index.d.ts
  packages/sdk/src/middleware/middleware.spec.ts
  packages/sdk/src/middleware/middleware.ts
Labels: 🐛 Type: Bug
