Repository commercetools/merchant-center-application-kit, pull requests merged in 2021-06, with the labels that each got.

#2233 refactor: to update to jest v27
  .changeset/sixty-eggs-agree.md
  application-templates/starter/package.json
  package.json
  packages/application-shell/src/components/application-shell/application-shell.spec.js
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/polyfills/intl.js
  packages/jest-preset-mc-app/setup-test-framework.js
  packages/jest-preset-mc-app/transform-babel-jest.js
  yarn.lock
Labels: 🙏 Status: Dev Review

#2254 feat: add ability to additionally silence warnings
  .changeset/tidy-boxes-drive.md
  packages/jest-preset-mc-app/setup-tests.js
Labels: 🙏 Status: Dev Review

#2258 feat: to add api targets for order search
  .changeset/perfect-mice-bow.md
  .changeset/wise-walls-know.md
  packages/constants/src/constants.ts
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#2257 test: disable core-js in test environment
  .changeset/tender-eggs-joke.md
  packages/babel-preset-mc-app/index.js
Labels: 🐛 Type: Bug, 💅 Type: Enhancement, 🙏 Status: Dev Review

#2260 fix(babel-preset-mc-app): to set node.js version to current
  .changeset/proud-cows-own.md
  packages/babel-preset-mc-app/index.js
Labels: 🙏 Status: Dev Review

#2263 fix: disable core-js in test environment
  jest-preset-mc-app.config.js
Labels: 🙏 Status: Dev Review

#2271 fix(api-error): log api errors to console only in development env
  .changeset/modern-cheetahs-cry.md
  packages/react-notifications/src/components/notification-kinds/api-error/api-error.tsx
Labels: 👨‍⚕️ Type: Tests, 🙏 Status: Dev Review
