Repository commercetools/merchant-center-application-kit, pull requests merged in 2021-03, with the labels that each got.

#2072 fix(webpack): to pass parallelism to thread-loader
  .changeset/swift-pandas-punch.md
  packages/mc-scripts/src/config/create-webpack-config-for-production.js
Labels: 🙏 Status: Dev Review

#2080 fix(packages.json): fix the yarn:clean command
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#2079 Add navigating to a project's stores to quick access commandlist
  .changeset/pretty-rice-hide.md
  packages/application-shell/src/components/quick-access/create-commands.ts
  packages/application-shell/src/components/quick-access/messages.ts
  packages/i18n/data/core.json
Labels: 🚀 Status: ship it

#2078 chore(application-components): remove generate types
  .changeset/ninety-beds-cover.md
  .graphqlrc.yml
  packages/application-components/src/types/generated/ctp.ts
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#2095 chore: upgrade to docs-kit v15
  .gitattributes
  @types-extensions/graphql-ctp/index.d.ts
  package.json
  packages/application-shell-connectors/src/types/.gitattributes
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell-connectors/src/types/generated/settings.ts
  packages/application-shell/src/components/navbar/navbar.tsx
  packages/application-shell/src/types/.gitattributes
  packages/application-shell/src/types/generated/ctp.ts
  packages/application-shell/src/types/generated/mc.ts
  packages/application-shell/src/types/generated/proxy.ts
  packages/application-shell/src/types/generated/settings.ts
  playground/package.json
  schemas/ctp.json
  schemas/mc.json
  schemas/proxy.json
  schemas/settings.json
  website-components-playground/gatsby-config.js
  website-components-playground/package.json
  website-components-playground/yarn.lock
  website/gatsby-config.js
  website/package.json
  website/src/@commercetools-docs/gatsby-theme-docs/overrides/site-icon.js
  website/src/layouts/marketing.js
  website/yarn.lock
  yarn.lock
Labels: 🤖 Type: Dependencies

#2105 feat(l10n): update generate-data script
  .changeset/ninety-donuts-tickle.md
  packages/l10n/scripts/generate-l10n-data.js
Labels: 🚀 Status: ship it, 🛠 Type: Tooling, 🧟 Type: Technical Debt

#2113 fix(l10n/scripts): fix typo and locale name
  packages/l10n/scripts/generate-l10n-data.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#2116 refactor(playground): add checkbox echo
  .changeset/mighty-rice-agree.md
  playground/package.json
  playground/src/components/echo-server/echo-server.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#2118 fix(express/auth): omit search params when reconstrucing audience URL
  .changeset/few-snails-hunt.md
  packages-backend/express/src/auth.spec.js
  packages-backend/express/src/auth.ts
Labels: 🐛 Type: Bug
