Repository commercetools/merchant-center-application-kit, pull requests merged in 2021-04, with the labels that each got.

#2131 chore: upgrade ui-kit to v12
  .changeset/small-grapes-cross.md
  @types/commercetools-uikit__async-select-input/index.d.ts
  @types/commercetools-uikit__link/index.d.ts
  @types/commercetools-uikit__select-input/index.d.ts
  @types/commercetools-uikit__text-field/index.d.ts
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.tsx
  packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.tsx
  packages/application-shell/package.json
  packages/application-shell/src/components/locale-switcher/locale-switcher.tsx
  packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.tsx
  packages/i18n/package.json
  packages/react-notifications/package.json
  playground/package.json
  playground/src/components/echo-server/echo-server.js
  playground/src/components/state-machines-details/state-machines-details.js
  visual-testing-app/package.json
  visual-testing-app/src/components/custom-form-modal-page/custom-form-modal-page.visualroute.tsx
  visual-testing-app/src/components/form-modal-page/form-modal-page.visualroute.tsx
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change, 🙏 Status: Dev Review

#2143 feat(application-config): add permissions policy header
  .changeset/bright-glasses-grin.md
  packages/application-config/schema.json
  packages/application-config/src/schema.ts
  packages/application-config/test/fixtures/config-full.json
  packages/application-config/test/process-config.spec.js
  packages/mc-html-template/src/process-headers.js
  packages/mc-scripts/src/compile-html.js
  website/src/content/development/application-config.mdx
Labels: 🚀 Type: New Feature

#2148 feat(l10n): adds `transformLocalizedStringToLocalizedField`
  .changeset/twenty-rabbits-admire.md
  packages/l10n/src/index.ts
  packages/l10n/src/localize.spec.ts
  packages/l10n/src/localize.ts
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🚀 Type: New Feature

#2144 feat(test-utils): add renderHook wrapper
  .changeset/heavy-ligers-admire.md
  packages/application-shell/package.json
  packages/application-shell/src/test-utils/test-utils.tsx
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#2175 [Breaking] Drop Enzyme support from Jest preset and make it opt-in
  .changeset/good-wolves-watch.md
  .changeset/serious-actors-attend.md
  @types-extensions/jest.d.ts
  application-templates/starter/package.json
  package.json
  packages/jest-preset-mc-app/README.md
  packages/jest-preset-mc-app/enzyme/base-setup-test-framework-for-enzyme.js
  packages/jest-preset-mc-app/enzyme/create-jest-preset-for-enzyme.js
  packages/jest-preset-mc-app/enzyme/jest-preset-for-enzyme-16.js
  packages/jest-preset-mc-app/enzyme/jest-preset-for-enzyme-17.js
  packages/jest-preset-mc-app/enzyme/setup-test-framework-for-enzyme-16.js
  packages/jest-preset-mc-app/enzyme/setup-test-framework-for-enzyme-17.js
  packages/jest-preset-mc-app/jest-preset.js
  packages/jest-preset-mc-app/package.json
  packages/jest-preset-mc-app/setup-test-framework.js
  packages/jest-preset-mc-app/setup-tests.js
  packages/sdk/package.json
  packages/sdk/src/components/sdk-get/sdk-get.spec.tsx
  yarn.lock
Labels: 💥 Type: Breaking Change, 🤖 Type: Dependencies
