Repository commercetools/merchant-center-application-kit, pull requests merged in 2022-08, with the labels that each got.

#2730 docs: add example of Azure deployment with Blob Storage
  website/src/content/deployment-examples/azure-blob-storage.mdx
  website/src/content/deployment-examples/azure-static-web-apps.mdx
  website/src/content/deployment-examples/index.mdx
  website/src/data/navigation.yaml
Labels: ✍️ Type: Documentation

#2740 Documentation example for deploying to Google Cloud with Static Web Apps
  website/src/content/deployment-examples/google-cloud-static-web-apps.mdx
  website/src/content/deployment-examples/index.mdx
  website/src/data/navigation.yaml
Labels: ✍️ Type: Documentation

#2778 chore: update flopflip dependencies
  .changeset/tricky-ears-confess.md
  packages/application-shell/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2745 feat: add MainPages component
  .changeset/moody-chicken-do.md
  packages/application-components/src/components/detail-pages/form-detail-page/form-detail-page.tsx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.tsx
  packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx
  packages/application-components/src/components/dialogs/internals/dialog-footer.tsx
  packages/application-components/src/components/internals/default-form-buttons.tsx
  packages/application-components/src/components/main-pages/custom-form-main-page/README.md
  packages/application-components/src/components/main-pages/custom-form-main-page/custom-form-main-page.spec.tsx
  packages/application-components/src/components/main-pages/custom-form-main-page/custom-form-main-page.tsx
  packages/application-components/src/components/main-pages/custom-form-main-page/index.ts
  packages/application-components/src/components/main-pages/form-main-page/README.md
  packages/application-components/src/components/main-pages/form-main-page/form-main-page.spec.tsx
  packages/application-components/src/components/main-pages/form-main-page/form-main-page.tsx
  packages/application-components/src/components/main-pages/form-main-page/index.ts
  packages/application-components/src/components/main-pages/info-main-page/README.md
  packages/application-components/src/components/main-pages/info-main-page/index.ts
  packages/application-components/src/components/main-pages/info-main-page/info-main-page.tsx
  packages/application-components/src/components/main-pages/internals/main-page.styles.ts
  packages/application-components/src/components/main-pages/tabular-main-page/README.md
  packages/application-components/src/components/main-pages/tabular-main-page/index.ts
  packages/application-components/src/components/main-pages/tabular-main-page/tabular-main-page.spec.tsx
  packages/application-components/src/components/main-pages/tabular-main-page/tabular-main-page.tsx
  packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx
  packages/application-components/src/index.ts
  visual-testing-app/src/components/custom-form-main-page/custom-form-main-page.visualroute.tsx
  visual-testing-app/src/components/custom-form-main-page/custom-form-main-page.visualspec.ts
  visual-testing-app/src/components/form-main-page/form-main-page.visualroute.tsx
  visual-testing-app/src/components/form-main-page/form-main-page.visualspec.ts
  visual-testing-app/src/components/info-main-page/info-main-page.visualroute.tsx
  visual-testing-app/src/components/info-main-page/info-main-page.visualspec.ts
  website-components-playground/src/pages/custom-form-main-page.js
  website-components-playground/src/pages/form-main-page.js
  website-components-playground/src/pages/info-main-page.js
  website/src/content/api-reference/commercetools-frontend-application-components.mdx
Labels: 🚀 Type: New Feature
