Repository commercetools/merchant-center-application-kit, pull requests merged in 2022-04, with the labels that each got.

#2561 chore: update all docs dependencies (update website banner)
  .changeset/rare-flowers-wave.md
  package.json
  playground/package.json
  website/package.json
  website/src/content/api-reference/commercetools-frontend-application-components.mdx
  website/src/content/concepts/merchant-center-proxy-router.mdx
  website/src/content/concepts/oauth-scopes-and-user-permissions.mdx
  website/src/content/development/permissions.mdx
  website/src/content/maintenance-guidelines.mdx
  website/src/releases/2022-02/release-v21.mdx
  yarn.lock
Labels: 💅 Type: Enhancement, 🤖 Type: Dependencies

#2550 feat(template-starter): add channel details page
  .changeset/fifty-fireants-judge.md
  .changeset/wise-onions-yawn.md
  @types-extensions/graphql-ctp/index.d.ts
  application-templates/starter/custom-application-config.mjs
  application-templates/starter/package.json
  application-templates/starter/src/components/channel-details/channel-details-form.js
  application-templates/starter/src/components/channel-details/channel-details.js
  application-templates/starter/src/components/channel-details/channel-details.spec.js
  application-templates/starter/src/components/channel-details/constants.js
  application-templates/starter/src/components/channel-details/conversions.js
  application-templates/starter/src/components/channel-details/index.js
  application-templates/starter/src/components/channel-details/messages.js
  application-templates/starter/src/components/channel-details/transform-errors.js
  application-templates/starter/src/components/channel-details/validate.js
  application-templates/starter/src/components/channels/channels.js
  application-templates/starter/src/components/channels/channels.spec.js
  application-templates/starter/src/helpers.js
  application-templates/starter/src/hooks/use-channels-connector/fetch-channel-details.ctp.graphql
  application-templates/starter/src/hooks/use-channels-connector/fetch-channels.ctp.graphql
  application-templates/starter/src/hooks/use-channels-connector/index.js
  application-templates/starter/src/hooks/use-channels-connector/update-channel-details.ctp.graphql
  application-templates/starter/src/hooks/use-channels-connector/use-channels-connector.js
  application-templates/starter/src/test-utils/test-data/channel/constants.js
  application-templates/starter/src/test-utils/test-data/channel/generator.js
  application-templates/starter/src/test-utils/test-data/channel/index.js
  packages/application-shell/src/components/suspended-route/index.ts
  packages/application-shell/src/components/suspended-route/suspended-route.tsx
  packages/application-shell/src/index.ts
  packages/application-shell/src/types/generated/ctp.ts
  schemas/ctp.json
  yarn.lock
Labels: 💅 Type: Enhancement

#2565 feat(codemod): add codemod CLI with transform `rename-js-to-jsx`
  .changeset/cold-ears-explode.md
  .changeset/config.json
  .vscode/spellright.dict
  package.json
  packages/codemod/.gitignore
  packages/codemod/LICENSE
  packages/codemod/README.md
  packages/codemod/bin/mc-codemod.js
  packages/codemod/package.json
  packages/codemod/src/cli.ts
  packages/codemod/src/transforms/rename-js-to-jsx.ts
  packages/codemod/src/types.ts
  packages/codemod/tsconfig.json
  scripts/build_packages.sh
  yarn.lock
Labels: 🏕 Type: Technical Exploration, 💡 Type: Idea
