Repository commercetools/merchant-center-application-kit, pull requests merged in 2022-07, with the labels that each got.

#2677 Fix i18n extract command in TS starter template
  application-templates/starter-typescript/package.json
Labels: 🚀 Status: ship it

#2699 chore: update docs-kit and gatsby dependencies
  .yarnrc.yml
  playground/package.json
  website-components-playground/package.json
  website/gatsby-config.js
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2705 chore: update TypeScript dependencies
  .changeset/eight-mayflies-search.md
  application-templates/starter-typescript/package.json
  package.json
  packages-backend/eslint-config-node/package.json
  packages-backend/express/package.json
  packages-backend/loggers/package.json
  packages/actions-global/package.json
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/browser-history/package.json
  packages/codemod/package.json
  packages/eslint-config-mc-app/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/mc-dev-authentication/package.json
  packages/mc-html-template/package.json
  packages/mc-scripts/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  packages/sdk/package.json
  packages/sentry/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2707 chore: update Apollo dependency to `v3.6.9`
  .changeset/blue-files-pull.md
  application-templates/starter-typescript/package.json
  application-templates/starter/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2704 chore: update Sentry dependencies to `v7`
  .changeset/strong-windows-hammer.md
  packages-backend/loggers/package.json
  packages/sentry/package.json
  packages/sentry/src/sentry.spec.ts
  yarn.lock
Labels: 🤖 Type: Dependencies

#2708 chore: update ESLint dependencies
  .changeset/mean-cycles-tap.md
  application-templates/starter-typescript/package.json
  application-templates/starter/package.json
  package.json
  packages-backend/eslint-config-node/package.json
  packages/eslint-config-mc-app/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2710 chore: update PostCSS and Stylelint dependencies
  .changeset/hungry-gifts-fix.md
  package.json
  packages/jest-stylelint-runner/__mocks__/css-functions-list.js
  packages/jest-stylelint-runner/package.json
  packages/jest-stylelint-runner/run.spec.js
  packages/mc-scripts/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2709 chore: update Moment and react-intl dependencies
  .changeset/spotty-books-help.md
  application-templates/starter-typescript/package.json
  application-templates/starter/package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2706 chore: update `msw` dependency to `v0.44.0`
  .changeset/fuzzy-plums-beam.md
  application-templates/starter-typescript/package.json
  application-templates/starter/package.json
  packages-backend/express/package.json
  packages/application-shell/package.json
  packages/mc-scripts/package.json
  playground/src/components/state-machines-list/state-machines-list.spec.js
  yarn.lock
Labels: 🤖 Type: Dependencies

#2703 chore: update Emotion dependencies to `v11.9.3`
  .changeset/few-cherries-rhyme.md
  packages/application-components/package.json
  packages/application-shell-connectors/package.json
  packages/application-shell/package.json
  packages/i18n/package.json
  packages/l10n/package.json
  packages/permissions/package.json
  packages/react-notifications/package.json
  visual-testing-app/package.json
  website-components-playground/package.json
  website/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#2715 docs: add example of Azure deployment with Static Web Apps
  website/src/content/deployment-examples/aws-s3-cloudfront.mdx
  website/src/content/deployment-examples/azure-static-web-apps.mdx
  website/src/content/deployment-examples/cloudflare.mdx
  website/src/content/deployment-examples/index.mdx
  website/src/content/deployment-examples/netlify.mdx
  website/src/content/deployment-examples/render.mdx
  website/src/content/deployment-examples/surge.mdx
  website/src/content/deployment-examples/vercel.mdx
  website/src/data/navigation.yaml
Labels: ✍️ Type: Documentation
