Repository commercetools/merchant-center-application-kit, pull requests merged in 2022-11, with the labels that each got.

#2868 PCM-2794: fix quick access to product list
  .changeset/proud-ants-flow.md
  packages/application-shell/src/components/quick-access/create-commands.ts
  packages/application-shell/src/components/quick-access/quick-access.spec.js
Labels: 🚀 Status: ship it

#2877 fix: to allow disabling Sentry and GTM through environment variable
  .changeset/twenty-wombats-accept.md
  packages/application-shell/src/utils/gtm.ts
  packages/sentry/src/sentry.ts
Labels: 🙏 Status: Dev Review

#2883 refactor: use global resets styles
  application-templates/starter-typescript/package.json
  application-templates/starter/package.json
  package.json
  packages/application-components/package.json
  packages/application-shell/package.json
  packages/application-shell/src/components/application-shell/global-styles.tsx
  packages/i18n/package.json
  packages/react-notifications/package.json
  playground/package.json
  visual-testing-app/index.html
  visual-testing-app/package.json
  visual-testing-app/src/application.tsx
  visual-testing-app/src/globals.css
  visual-testing-app/src/index.tsx
  website-components-playground/package.json
  website-components-playground/src/application.tsx
  website-components-playground/src/globals.css
  website-components-playground/src/index.tsx
  website/package.json
  yarn.lock
Labels: 🛑 Status: blocked
