Repository commercetools/merchant-center-application-kit, pull requests merged in 2023-01, with the labels that each got.

#2852 chore: add user event to rtl
  .changeset/kind-geese-breathe.md
  packages/application-shell/package.json
  packages/application-shell/src/test-utils/test-utils.tsx
  yarn.lock
Labels: 🚀 Status: ship it

#2926 feat(application-shell): fetch and expose user's created date for personalized guidance in mc
  .changeset/slow-suns-greet.md
  graphql-test-utils/graphql-models/user.js
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
  packages/application-shell-connectors/src/types/generated/mc.ts
  packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql
  packages/application-shell/src/test-utils/test-utils.tsx
  packages/application-shell/src/types/generated/mc.ts
  packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
  packages/permissions/src/types/generated/mc.ts
  schemas/mc.json
  test-data/types/generated/mc.ts
  website/linkinator.config.json
Labels: 🙏 Status: Dev Review, 🚀 Type: New Feature

#2944 Fct 176 redesign login layout update
  .changeset/two-forks-shout.md
  packages/application-shell/package.json
  packages/application-shell/src/components/authenticated/oidc-callback-error-page.tsx
  yarn.lock
Labels: 🙏 Status: Dev Review
