Repository commercetools/merchant-center-application-kit, pull requests merged in 2024-07, with the labels that each got.

#3560 fix: ensure page content layout columns have the correct sizes
  .changeset/khaki-icons-smoke.md
  packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.tsx
Labels: missing-jira

#3571 chore: forward application context project's isProductionProject
  .changeset/dry-eagles-sin.md
  packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx
  packages/application-shell-connectors/src/components/application-context/application-context.tsx
Labels: 🔮 Type: Chore

#3573 chore(CONTRIBUTING.md): fix typo
  CONTRIBUTING.md
Labels: ✍️ Type: Documentation, missing-jira
